# Introduction (TOR section C1 and C2)

This assessment reports the status of `r spp` (*Sebastes maliger*) off the coast of California through 2024. The \gls{pfmc} defined the California stock of `r spp` as part of the process to define stocks for management. Although the management definition for the California stock of `r spp` is statewide, the range of `r spp` in California is primarily north of central California (@fig-map).

<!-- Scientific name, distribution, the basis for the choice of stock structure, including regional differences in life history or other biological characteristics that should form the basis of management units. A map showing the scope of the assessment and depicting boundaries for fisheries or data collection strata.  -->

## Life History (TOR section C3)

`r Spp` are a demersal, relatively nearshore species within the subgenus *Pteropodus*.  The core range of `r spp` is relatively large from central California to the Gulf of Alaska, with `r spp` also found in Puget Sound. `r Spp` range from the sub-tidal (as juveniles) to depths of around 274 m [@love_rockfishes_2002]. They are commonly found in waters less than 100 m  inhabiting both low and high relief complex rocky habitat [@love_milton_probably_1996] and do not show an ontogenetic migration that a number of rockfish exhibit. @murie_comparative_1991 found `r spp` of all sizes in shallower waters, and a lack of small `r spp` in deeper depths. This pattern is similar to trends observed in the two fishery-independent studies used for this stock assessment, as well as biological data observed from the \gls{wcgop}. 

The body coloring of adult `r spp` is brown with yellow to orange blotching and light-colored dorsal saddle patches [@love_rockfishes_2002]. As their name suggests, `r spp` have long dorsal fin spines with deeply incised membranes. The diet of `r spp` consists primarily of benthic and pelagic crustaceans, e.g., coonstripe shrimp, and fish, with the proportion of fish contributing to their diet increasing with size [@murie_comparative_1991]. 

Limited studies have evaluated genetic variation in `r spp` across the U.S. West Coast. Genetic work has revealed significant differences between Puget Sound and coastal stocks of `r spp` [@seeb_gene_1998; @Stoutetal_DPS_2001], however Seeb [-@seeb_gene_1998] did not find significant differentiation in populations of `r spp` between coastal Washington and Alaska. Adult `r spp` have high site fidelity; an acoustic telemetry study displaced `r spp` 500 m from the capture location and all returned to the original capture site within 30 days [@matthews_1990_telemetric]. Other telemetry studies have found similar patterns of high site fidelity as well as small home ranges for `r spp` [@hannah_site_fidelity_2011; @tolimieri_home_2009] that could suggest isolation-by-distance as found for other rockfish species. 

`r Spp` are a long-lived rockfish with the oldest aged specimen at 95 years from British Columbia [@love_rockfishes_2002; @YamanakaandLacko_rockfish_2001]. Along their range, the oldest `r spp` from southeast Alaska was 92, 73 from Washington, 63 from Oregon, and 57 from California, which was encountered by \gls{s-ccfrp} (Claire Stuart, Cal Poly Humboldt, pers. comm). The availability of life history information for `r spp` in California, which is the most southern part of their range, is sparse. A number of studies were undertaken after the 2021 data-moderate `r spp` stock assessment to estimate growth, maturity, and fecundity for California, which are described later in this report (see @sec-biology). 

@cope_approach_2011 found `r spp` to have a vulnerability score of V = 2.222, making it a species of major concern in the productivity susceptibility analysis. This analysis calculated species specific vulnerability scores based on two dimensions: productivity characterized by the life history, and susceptibility characterized by how the stock is likely affected by fisheries. 


## Ecosystem Considerations (TOR section C4)

This stock assessment does not explicitly incorporate trophic interactions, habitat factors nor environmental factors into the assessment model, primarily due to the lack of information of the effects of these factors on `r spp`. As with most other rockfish and groundfish in the California Current, recruitment or cohort (year-class) strength appears to be highly variable for `r spp`, with only a modest apparent relationship to estimated levels of spawning output. Oceanographic and ecosystem factors are widely recognized to be key drivers of recruitment variability for most species of groundfish, as well as most elements of California Current food webs. 

## Current and Historical Fishery Information (TOR section C5)

`r Spp` is encountered in both commercial and recreational fisheries throughout its range. In waters off the coast of California, `r spp` is generally not a highly desirable species by recreational fishermen  and its value in the commercial fishery rose with the development of the live-fish fishery in the 1990s. Recreational removals are the largest source of fishing mortality and represent approximately 75% of the total removals of `r spp` across all years (@tbl-catches and @fig-catches). The majority of the commercial landings for `r spp` occurred between 1990 and 2008, with a small increase from 2016 to 2022 prior to the California stock being defined and subsequently declared overfished. 

The recreational groundfish fishery in the early part of the 20th century was focused on nearshore waters near ports, with expanded activity farther from port and into deeper depths over time [@miller_spatially_2014]. Prior to the groundfish fishery being declared a federal disaster in 2000, and the subsequent rebuilding period, there were no time or area closures for groundfish. During this period, access to deeper depths led to effort being spread over a larger area and filled bag limits with a greater diversity of species from the shelf as well as the nearshore. This resulted in lower catch rates for nearshore rockfish relative to the period after 2000 when depth restrictions starting between 20 to 50 fm were put in place in various management areas north of Point Conception where `r spp` are commonly found. This shift of effort into the nearshore kept catch levels high for nearshore rockfish, including `r spp`, despite greatly reduced seasons.

Prior to the development of the live-fish market in the 1990s, commercial catches of `r spp` were relatively low, and `r spp` were often landed dead for a relatively low ex-vessel price per pound. Most fish were caught using hook and line gear, though some were caught using traps, gill nets, and in some instances, trawl gear. Trawling within three miles of shore, where most `r spp` habitat is found, has been prohibited since 1953, and gill nets were banned within three miles of shore in 1994. Whether from directed effort in the nearshore or as incidental catch while targeting other more valuable stocks such as lingcod, catches were below 0.5 mt from 1916 to 1980, with the exception of four of the five years between 1944--1948.

With the development and expansion of the nearshore live-fish fishery during the 1990s, new entrants in this open access fishery were drawn by a premium ex-vessel price per pound for live fish, resulting in over-capitalization of the fishery. Since 2002, the \gls{cdfw} has managed 19 nearshore species in accordance with the Nearshore Fisheries Management Plan [@wilson-vandenberg_implementing_2014]. In 2003, \gls{cdfw} implemented a Nearshore Restricted Access Permit system, including the requirement of a Deeper Nearshore Fishery Species Permit to retain `r spp`. Permits were issued based on prior landings history and the overall goal of reducing the number of participants to a more sustainable level. The result was a reduction in permits issued from 1,127 in 1999 to 505 in 2003. In addition, reduced trip limits, season closures in March and April, and depth restrictions were implemented to address bycatch of overfished species and associated constraints from their low catch limits. The open access fishery is allowed to retain shelf rockfish species co-occurring with nearshore rockfish species. There is growing concern regarding increased encounters and discard mortality from the open access fleet, given that they are fishing in deeper depths. However, fishing in waters up to 60 fm may result in decrease effort for `r spp` as overall effort shifts away from waters where `r spp` are most prevalent. 


## Management History (TOR section C6)

Prior to 2000, the management of rockfish off the coast of California was limited.  The recreational bag limit (that included rockfish) was 20-fish from 1967 to 1970, 15-fish from 1970 to 2000 when it was reduced to the current day bag limit of 10 fish within  the rockfish, cabezon, and greenling (RCG) complex. The sub-bag limit for `r spp` did not change until 2022 when a 1-fish sub-bag limit was implemented, and later followed by a full closure of the fishery in August, 2023.

Between 1999 and 2002, gear regulations went from unlimited hooks and lines to one line per person with no more than two hooks, the current 10 RCG bag limit was enacted, and \gls{cdfw} created  management areas to restrict fishing shoreward of depths between 20 to 60 fm. The latitudinal boundaries of the management areas and depth closures have fluctuated since 2002, but have remained fairly consistent from 2011--2022 (@fig-rec-regs-vis).  \Gls{mpa}s instituted between 2003 and 2012 now encompass 20-30% of the rocky reef habitat within 3 miles of shore in state waters.

Prior to the adoption of the Pacific Coast Groundfish \gls{fmp} in 1982, `r spp` were managed through a regulatory process that included the \gls{cdfw}, the California State Legislature, and the Fish and Game Commission (FGC). With implementation of the Pacific Coast Groundfish \gls{fmp}, `r spp` came under the management authority of the \gls{pfmc} and were managed as part of the *Sebastes* complex. Because `r spp` had not undergone rigorous stock assessment and did not compose a large fraction of the landings it was classified and managed as part of the "Minor Nearshore Rockfish" group [@pfmc_fmp_2024]. 

Since the early 1980s, a number of federal regulatory measures have been used to manage the commercial rockfish fishery including cumulative trip limits (generally for two- month periods) and seasons. Starting in 1994 the commercial groundfish fishery sector was divided into two components: limited entry and open access with specific regulations designed for each component. Limited entry programs were designed in part to limit bottom contact gears and the open access sector includes gears not making bottom contact, e.g., hook and line. Other regulatory actions for the general rockfish categories included area closures and gear restrictions set for the four different commercial sectors - limited entry fixed gear, limited entry trawl, open access trawl, and open access non-trawl (which includes the nearshore fishery). 

In 2000, the PFMC's rockfish management structure changed significantly with the replacement of the *Sebastes* complex -north and -south areas with Minor Rockfish North (Vancouver, Columbia, and Eureka, International North Pacific Fisheries Commission (INPFC) areas) and Minor Rockfish South (Monterey and Conception INPFC areas only). The optimum yield for these two groups was further divided (between north and south of Cape Mendocino, California, at 40$^\circ$ 10' N. latitude) into nearshore, shelf, and slope rockfish categories with allocations set for limited entry and open access fisheries within each of these three categories. Species were parceled into these new categories depending on primary catch depths and geographical distribution. `r Spp` was included in the nearshore rockfish category. 

During the late 1990s and early 2000s, major changes also occurred in the way that California managed its nearshore fishery. The Marine Life Management Act (MLMA), which was passed in 1998 by the California Legislature and enacted in 1999, required that the FGC adopt an \gls{fmp} for nearshore finfish [@wilson-vandenberg_implementing_2014]. It also gave authority to the FGC to regulate commercial and recreational nearshore fisheries through FMPs and provided broad authority to adopt regulations for the nearshore fishery during the time prior to adoption of the nearshore finfish FMP. Within this legislation, the Legislature also included a requirement that commercial fishermen landing nearshore species possess a Nearshore species Fishery Permit.

Following adoption of the California Nearshore \gls{fmp} and accompanying regulations by the FGC in fall of 2002, the FGC adopted regulations in November 2002 which established a set of \gls{mpa}s around the Channel Islands in southern California (which became effective April 2003). The FGC also adopted a restricted access program in December 2002 which established the Deeper Nearshore Species Fishery Permit, to be effective starting in the 2003 fishing year. Also, since the enactment of the MLMA, the PFMC and State coordinated to develop and adopt various management specifications to keep harvest within the harvest targets, including seasonal and area closures, depth restrictions, and bag limits to regulate the recreational fishery (@fig-rec-regs-vis) and license and permit regulations, finfish trap permits, gear restrictions, seasonal and area closures, depth restrictions, trip limits, and minimum size limits to regulate the commercial fishery (@fig-com-regs-vis). The MPAs were later expanded under authority of the Marine Life Protection Act (MLPA) enacted in 1999, creating a network of MPAs which went into place in phases beginning with the central coast in 2007, north central coast in 2010, and the south and north coasts in 2012. The rockfish conservation areas (RCAs) are seasonally adjusted depth limits impacting trawl and non-trawl gears that were initially established in 2002 to protect overfished species. The RCAs also restricted catch of nearshore species to depths less than 30 fm, and in some areas along California to less than 20 fm. Thus, the MPAs, CCAs and RCAs represent three types of spatial and/or depth closures impacting rockfish.

The state of California has adopted regulatory measures to manage the nearshore fishery based on the harvest guidelines set by the \gls{pfmc} for the minor nearshore rockfish complexes north and south of 40$^\circ$ 10' N. Lat.. Each complex is managed based on a complex-level \gls{ofl} and \gls{acl} that are determined by summing the species-specific \gls{ofl} and \gls{acl} (\gls{acl}s set equal to the \gls{abc}) contributions for all stocks managed in the complex. Limits are shared among all commercial and recreational fleets with the various management procedures intended to maintain removals below the total complex total \gls{ofl} and \gls{acl} as a whole, rather than on a species by species basis. The nearshore commercial fishery is managed based on bimonthly allowable catches per vessel, that have ranged from 200 to 2,000 pounds per two months since 2000. Fishers operating in the federal open access nontrawl sector and permittees of the California Nearshore Species Fishery permit are currently subject to the same limits per pound and two month period.  However, not all federal open access participants have a California Nearshore Species Fishery permit.  Because `r spp` is a species named in the California Nearshore Species Fishery permit, those vessels without the state permit must release any `r spp` and therefore their contributions to `r spp` mortality are purely from discard.  

The 2021 assessment indicated that the California population of `r spp` was below the MSST [@Langseth_status_2021], triggering a rebuilding analysis [@langseth_rebuild_2022]. However, by the November 2021 Council meeting, \gls{nmfs} had not made an overfished declaration because `r spp` had not been identified within the \gls{fmp} as a stock or management unit for California. The \gls{pfmc}, at its March 2022 meeting, decided to pursue development of an \gls{fmp} amendment that would more clearly define those groundfish stocks and complexes in need of conservation and management. In June 2023, the \gls{pfmc} took final action on an amendment to the FMP (Amendment 31; @amendment31_2023) to describe stock definitions for a subset of groundfish species, which included removing California `r spp` from the nearshore rockfish complex. This led to the `r spp` stock off California to be declared overfished in December 2023, thereby triggering an updated rebuilding analysis [@langseth_rebuild_2024]. Despite the absence of this declaration, \gls{cdfw} along with \gls{nmfs} implemented a recreational one-fish bag limit for `r spp` and reduced commercial limits in 2021, and followed this with a complete prohibition on `r spp` retention in recreational and commercial fisheries in August 2023. This means that California Nearshore Species Fishery permittees were still subject to the same trip limits as the federal open access nontrawl sector, with the exception that any caught `r spp` could not be retained.  In order to minimize this potential source of waste and mortality for `r spp`, in February 2024 \gls{cdfw} took emergency action to create a California Groundfish Restriction Area (CGRA). The CGRA extended from 36$^\circ$ N latitude to the California-Oregon Border and from a shoreward boundary line approximating 20 fm to a seaward boundary line of the \gls{eez}. This prohibited commercial groundfish fishing between the 20 fm line and the shoreward boundary of the \gls{eez} and all non-nearshore fishing in state waters because fishery data indicate `r spp` are rarely encountered in waters shallower than 20 fm. In August 2024, \gls{cdfw} revised the emergency action southern boundary line to 37$^\circ$ 07' N. latitude (A&ntilde;o Nuevo, San Mateo County) in state waters. Similarly, depth based recreational groundfish regulations were implemented north of Point Lopez which set allowable fishing depths during open seasons seaward of either the 50 fm or 20 fm lines in different management areas to protect `r spp`. These restrictions currently remain in place.  

<!---
Summary of management history (e.g., changes in mesh sizes, trip limits, or other management actions that may have significantly altered selection, catch rates, or discards). 
--->

## Management Performance (TOR section C7)

The management of `r spp` in California changed after the 2021 assessment. When managed within the Nearshore Rockfish North and South complexes, no species-specific \gls{ofl} or \gls{acl} existed. Rather species-specific \gls{ofl} contributions as well as implied \gls{acl} contributions were used to monitor `r spp` removals. Because the 40$^\circ$ 10' N. latitude management line occurs within California waters, allocations for state specific sharing agreements provide a California specific \gls{acl} contribution by summing all of the South management contribution to 28.7% of the North management contribution (\gls{gmt}, pers. comm.). Starting in 2023, `r spp` rockfish in California were assigned a species-specific \gls{ofl}, \gls{abc}, and \gls{acl} based on the results of the 2021 rebuilding analysis [@langseth_rebuild_2022]. Past \gls{ofl} and \gls{acl} contributions during years when California `r spp` were managed within a complex, along with the California-specific \gls{acl} contribution are provided in @tbl-es-management. Also included in @tbl-es-management are California-specific \gls{ofl}, \gls{abc}, and \gls{acl} for years when `r spp` were managed individually. These values are compared to total removals and with the exception of 2024, total removals of `r spp` have been above \gls{acl} contributions and \glspl{acl}.

<!-- Management performance, including a table or tables comparing Overfishing Limit (OFL), Acceptable Biological Catch (ABC), Annual Catch Limit (ACL), landings, and catch (i.e., landings plus discard) for each area and year. Groundfish assessments that estimate dead discarded catch must include a disclaimer noting that total mortality estimates from the WCGOP and from the stock assessment may differ due to the use of different methods. Investigation into how these methods differ is beyond the scope of a benchmark assessment. The rationale for modeling discard mortality can also be provided. This should be included in all update assessments.  -->

## Foreign Fisheries (TOR section C8)

`r Spp` does not extend south to Mexico and given that the stock is defined as California only we did not consider the fisheries in Alaska or Canada. Assessments in 2021 were also done for Oregon [@langseth_ORstock_2021] and Washington [@langseth_WAstock_2021]. The Oregon assessment estimated spawning stock relative to unfished of 0.47 and was used to inform harvest levels, whereas the Washington assessment was considered too uncertain to provide status determination criteria but was used to inform harvest levels. `r Spp` in both states are managed within the nearshore rockfish north complex. Estimated total removals for Washington and Oregon `r spp` from the \gls{gemm} were highest during the last 10 years between 2017--2020, and averaged 8.9 mt during 2014--2023 and 10.2 mt during 2019--2023.  