## Fishery-dependent data

### Total Removals {#removals}

Removals (1916--2024) for `r spp` were compiled from multiple data sources. This assessment uses total removals (landings plus dead discards) for all fishing fleets. Sources for total removals are described below. In instances where separate data sources were used for landings and dead discards, each component is described separately. The values for total removals used in the base model are provided in @tbl-catches and @fig-catches.

#### Commercial Landings

Commercial landings for `r spp` were combined into a single fleet by aggregating across gear types and fish landed live vs. dead. This choice was based on similarities in the length distributions among gear types and between fish landed live versus dead within \gls{pacfin} samples.

Commercial landings data were available from 1916--2024. Historical landings (1916--1980) were obtained from the California Catch Reconstruction Project [@ralston_documentation_2010]. While all port groups were sampled, only the northern port groups of Crescent City, Eureka, and Fort Bragg had positive landings for `r spp`. Additional landings caught off the coast of Oregon or Washington but landed in California for 1948--1968 were added to the reconstruction to represent total landings at California ports. These additional landings were small in magnitude; no more than 0.08 mt was landed in any one year and approximately 0.3 mt was landed across all years. Landings for 1969--1980 came from \gls{calcom}, and were negligible for `r spp`.

Recent (1981--2024) landings were obtained from \gls{pacfin} (extracted 03/14/2025). There were no landings for `r spp` within \gls{pacfin} in 1981--1983, and 1985. Sampling occurred during these years, and so estimates of zero were not due to a lack of sampling. Given that landings in the immediately preceding years were negligible, we kept landings for `r spp` in these years at zero, rather than interpolate based on neighboring values.

#### Commercial Discards

**FROG: Not sure we want this paragraph but this provides justification for our choice of adding dead discards to landings.** Discarding can be modeled in multiple ways. Among West Coast assessments, three methods for modeling discards are commonly used. Either dead discards are added to landings to obtain total removals, dead discards are modeled as a separate fleet from landings, or dead discards are estimated through the use of a retention curve applied to the landings fleet. The first method assumes that discarded fish are similar to retained fish, whereas the later two options allow separate selectivity processes to operate on discards and landings. Biological samples of `r spp` discards from \gls{wcgop} were available 2004--2022, but very sparse for all years other than 2022. Therefore, as there was limited information with which to estimate selectivity of the discards over the majority of years, we added dead discards to landings and modeled total removals.

Commercial discard data for `r spp` are collected through \gls{noaa}'s \gls{wcgop}. Estimates of dead discards in 2002--2023 for each sector of the commercial fleet are provided in the \gls{gemm} product [@somers_gemm_2023]. Dead discards from the \gls{gemm} product were added to landings estimates from \gls{pacfin} to obtain total removals for 2002--2023. Total removals prior to 2002, for which no \gls{wcgop} data are available, were calculated based on assuming an average ratio of dead discards to landings (0.25 percent), based on data from the nearshore sector in 2002--2021. The nearshore sector was selected as it most likely represents expected fishery behavior prior to 2002, and data from 2001 to 2021 were used because the ratio of dead discards increased in 2022 and 2023, likely as a consequence of management changes to the fishery. Preliminary estimates of dead discards for 2024 were provided by \gls{nwfsc} \gls{fos} program on 3/31/2025 and added to landings in that year to obtain total removals for 2024.

#### Recreational Landings and Discards

Recreational landings data were available from 1928--2024. Historical landings (1928--1980) were obtained from the historical reconstruction [@ralston_documentation_2010]. Since 1980, recreational data sources provide estimates of total removals, which combine landings and dead discards together. Data during these years were obtained from \gls{recfin} via the \gls{mrfss} (1981--2004) and \gls{crfs} (2005--2024) sampling programs. The \gls{mrfss} sampling program also includes removals for 1980, however because @ralston_documentation_2010 considered their 1980 estimate to be more reliable than that of \gls{mrfss}, and due to survey quality problems related to 1980 being the first year of \gls{mrfss} [@Karpov1995; @cope_status_2009], landings from the historical reconstruction were preferred for 1980. Estimates of dead discards for the historical years (1928--1980) were calculated based on an average ratio of dead discards to landings (1.1 percent) from \gls{mrfss} data across all years 1980--2004. A direct breakdown of the landed and dead discarded fish by weight was not available within the \gls{mrfss} data, so the proportion by number of total dead catch that was unavailable to the sampler, which included dead discarded fish, was calculated (\gls{mrfss} column ESTHARV divided by the sum of columns ESTHARV and ESTCLAIM) and used to derive the ratio. Landings and dead discards for the historical years were then added together to obtain estimates of total removals.

A number of years with missing or incomplete estimates for recreational total removals were filled in. First, 207 \gls{crfs} catch records in \gls{recfin} between 2014--2022 had a zero estimate for dead discards by weight but not by number. Catches were based on weight, so to ensure these records were included, an average weight per fish for dead discards was calculated from records with both weight and number, and used to derive estimates of dead discards in weight. Filling in these gaps increased the estimated total removals from between 0.02 mt to at most 1.2 mt in any one year. Second, the \gls{mrfss} sampling program did not sample between 1990--1992, and did not sample the party/charter fishery north of San Luis Obispo between 1993--1995. Estimates for party/charter fishery in 1993--1995 were calculated as the average of private/charter removals among \gls{mrfss} years (1980--2004) and then added to the private/rental fishery estimates in 1993--1995 to obtain total removals for those years. Estimates of total removals for both the private/rental and private/charter modes in 1990--1992 were obtained as averages from neighboring years. Total removals in 1990 were estimated as the average of total removals from 1987--1989, total removals in 1991 as the average from 1987--1989 and 1993--1995, and total removals in 1992 as the average from 1993--1995. Estimate of total recreational removals in 1993 were some of the largest for the recreational fleet across all years. The effects of assuming an average catch in 1991 and 1992 based on the 1993 estimate was explored through sensitivity analyses (see @sec-assmt-sens).


##### Recreational Data Impacted by COVID-19 Pandemic

The COVID-19 pandemic impacted recreational port sampling in 2020 and 2021. No sampling occurred at all in April-June, 2020. \Gls{cdfw} provided proxy values for these months (M. Parker, CDFW, personal communication, 12/4/24). Total proxy values for `r spp` weight were summed across district and added to the existing estimate for 2020 from \gls{recfin}. In addition, California recreational total mortality estimates in the “rockfish genus” were inflated due to \gls{crfs} samplers being unable to closely examine catch and identify catch to species. This was a problem for both private/rental and private/charter modes in 2020 and primarily for the private/charter mode in 2021. Some of the rockfish genus mortality was reallocated to other rockfish species for these modes and years and provided by \gls{cdfw} (provided on 12/5/24). An expected value of rockfish genus mortality in 2020 and 2021 was generated by mode and year according to the average proportion to the total rockfish mortality that this category represented in 2018 and 2019, when regulations were consistent with 2020 and 2021. Mortality above this expected value was attributed to the other species also based on proportions each species represented to the total from 2018 and 2019. Calculations were made by year, mode, and district. The shore-based modes were grouped in with the PR mode. Calculations were initially made in numbers of fish because rockfish genus mortality is only recorded this way. Numbers of fish by species were then converted to weight in kilograms based on average weights of fish recorded by the \gls{crfs} program by district in 2019. Total reallocated values for `r spp` weight were summed across modes and districts and added to existing estimates, which for 2020 was the sum of the proxy value and the estimate from \gls{recfin}, and for 2021 was the estimate for \gls{recfin}.

**FROG: HOldover from last assessment. Need place for this. Should have a matching commercial description**
The recreational fishery is the main source of mortality for quillback rockfish in California (Table 1 and Figure 1). Recreational removals peaked in the late 1970s and early 1980s, with two years of exceptionally large catches in 1984 and 1993. Removals declined sharply in 1994, but increased to levels similar to the late 1970s and early 1980s in the mid 2000s and again in recent years.

### Composition Data

**FROG: Origianlly had this split into separate comm and rec sections. They duplicate a bit for the version that is output here in the report is a combination. Not sure I love it though** <!-- The biological characteristics of commercial landings of rockfish were not consistently sampled for scientific purposes until the early 1960s (Niska, 1976) **FROG: Need this reference**. Sampling programs to determine species compositions of commercially landed catches began in the late 1960s but the first rigorous monitoring programs that included routine collection of biological data (e.g., sex, age, size, maturity) began in 1980. Currently, port biologists employed by \gls{psmfc} with the \gls{ccgs} California Cooperative Groundfish Survey (CCGS) **FROG: Confirm this reference is in the glossaries** collect species-composition information and biological data from the landed catches of commercial vessels that have completed their fishing trips. The monitoring programs currently in place are generally based on stratified, multistage sampling designs. -->

<!-- The biological characteristics of recreational landings were not consistently sampled for scientific purposes until the late 1970s. The first rigorous monitoring programs that included routine collection of biological data (e.g., sex, age, size, maturity states) began in 1980 by the national \gls{mrfss} program under the \gls{psmfc} and by state sampling programs. State sampling programs replaced MRFSS in the 2003--2004 period to better support in season management. Currently, port biologists employed by \gls{cdfw} collect catch, effort, and biological data from the landed catches of recreational vessels that have completed their fishing trips. Onboard sampling also occurs on party/charter vessels. -->

The biological characteristics of landings of rockfish were not consistently sampled for scientific purposes until the early 1960s (Niska, 1976) for commercial landings and until the late 1970s for recreational landings. **FROG: Need this reference**. The first rigorous monitoring programs that included routine collection of biological data (e.g., sex, age, size, maturity) for commercial and recreational landings began in 1980 by state sampling programs (for commercial) and the national \gls{mrfss} program under the \gls{psmfc} (for recreational). State sampling programs of recreational landings replaced \gls{mrfss} in 2003--2004 to better support in season management. Currently, port biologists employed by \gls{psmfc} with the \gls{ccgs} (for commercial) and employed by \gls{cdfw} (for recreational) collect species composition information and biological data from the landed catches of vessels that have completed their fishing trips. Onboard sampling of recreational removals also occurs on party/charter vessels. The monitoring programs currently in place are generally based on stratified, multistage sampling designs.

Twenty-one bins from 10 to 50 cm were used to summarize the length frequency distributions of sources of removals. The first bin includes all observations less than 10 cm and the last bin includes all fish larger than 50 cm. Thirty-five bins from age 1 to age 60 were used to summarize the age frequency distributions of sources of catch. These ranges encapsulate all ages sampled. Conditional-age-at-length data were used for age compositions, and are described in more detail in Section 3.3.5.3. **FROG: Replace with actual section description of CAAL data** Use of marginal age data were explored through sensitivity analyses (see @sec-assmt-sens).

Length samples were nearly entirely unsexed, while all age samples included information on sex. Given the limited information in the literature of sexual dimorphism for `r spp`, and that the majority of lengths were unsexed, length frequency compositions were calculated combined across sexes.

#### Commercial Length and Age Composition

Length and age samples were collected from commercial landings and extracted from \gls{pacfin} (extracted 03/17/2025). Length samples were available starting in 1978, but were very sparse prior to 1991. Length samples were most numerous during the 1990s, and since 2002 the number of length samples has been relatively low. Age samples were available starting in 2007, but only included 1 sample in 2011 and 4 in 2012 until being consistently available starting in 2019. Length compositions were combined across gear types, primarily hook and line or longline, based on similarities in length distributions among gears in areas where they both occurred.

The raw length observations were expanded to the sample level, to allow for any fish that were not measured, then to the trip level to account for the relative size of the landing from which the sample was obtained. These expanded length observations were then combined within a year for each fleet.

The input sample sizes for the expanded commercial length data were calculated based on a combination of the number of trips and fish by year:

```{=tex}
\begin{centering}

Input effN = $N_{\text{trips}} + 0.138 * N_{\text{fish}}$ if $N_{\text{fish}}/N_{\text{trips}}< 44$

Input effN = $7.06 * N_{\text{trips}}$ if $N_{\text{fish}}/N_{\text{trips}}\geq 44$

\end{centering}
```

This same calculation was also done for age composition data when marginal distributions were used, but that was only done as a sensitivity (see @sec-assmt-sens). For the base model, conditional-age-at-length distributions were used and sample sizes were based on the total number of age samples.

The magnitude of sampling for lengths and ages from the commercial fleet each year is given in @tbl-comm_lengths and @tbl-comm_ages. These tables show both the total number of fish sampled as well as the number of trips by year over which samples were obtained. They also show the sample size for expanded length compositions as used in the base model, which was calculated using the formula above. Sparse length and age composition data occurred in several years. Years where sample size for expanded length compositions were less than or equal to 5, and years with fewer than 30 samples for conditional-age-at-length were excluded from the model during fitting. Implications of these choices were tested as a sensitivity (see @sec-assmt-sens).

Commercial length and age frequency distributions are shown in @fig-len-comm-bubbles--@fig-caal-comm. Commercial lengths initially covered a relatively broad range of sizes, approximately 20 cm to near 50 cm in 1991--2002 (@fig-len-comm-bubbles). Since 2003, the range of observed sizes has shifted away from smaller sizes, from around 30 cm to near 50 cm. This shift in observed sizes is also reflected in the mean lengths observed by year, which have increased from around 33 cm to around 43 cm between 2000--2016 (@fig-lenMean-comm). The shift in mean size could be due to shifts in fishery behavior, sampling (there was a shift to more northern port groups during the mid 2000s and early 2010s), changes in the population demographics (e.g., lack of recruitment or presence of dominant recruitment pulse), or a combination of multiple factors. Commercial ages cover a narrow period of years and range from around 5 to 45 years old (@fig-caal-comm). The range of ages within length bins can be broad, roughly covering up to 10--20 years. Given the limited timeframe over which ages were sampled, patterns in trend are not easily discernible.

#### Recreational Length Composition

Recreational length composition data were obtained from a variety of sources. The primary sources of length samples were obtained from the \gls{mrfss} sampling program for years 1980--2003 and from the \gls{crfs} sampling program for years 2004--2024 via the \gls{recfin} website (extracted on 11/22/2024 for \gls{mrfss} and 3/14/2025 for \gls{crfs}). Lengths of fish measured by samplers onboard \gls{cpfv} prior to being released (Type 3d data; n = 49) were included among the data extracted from the \gls{crfs} sampling program. California has no aged samples of `r spp` available from recreational sampling, and so only length composition data were used to sample recreational landings.

Length samples were also collected from the Deb Wilson-Vandenberg onboard \gls{cpfv} survey for 1987--1998 and were obtained from \gls{cdfw} [@reilly_onboard_1998]. Between 1987--1989 and 1993-1998 there were recreational length data for the \gls{cpfv} fleet from both \gls{mrfss} and the Deb Wilson-Vandenberg data sets. During data exploration it was determined that the lengths in \gls{mrfss} from 1997 and 1998 were also in the Deb Wilson-Vandenberg data, indicating that these data sources were duplicated for at least these years. In order to avoid known duplicate data for 1997--1998, length data from the \gls{mrfss} sampling program for private/charter mode in these years (n = 123) were excluded from the base model.

Length samples were collected from another study for 1992--1998 that was only recently made available ([@geibel_prsurvey_2025]; extracted on 1/8/2025). These lengths were limited to a single northern district (Redwood), and were sampled from private/rental vessels only. While limited in spatial scale, these data were collected as part of a robust survey design separate from other sampling programs. This study also represents a large sample size (n = 600), and provides information on a fishing mode not covered by the Deb Wilson-Vandenberg data. The data therefore were included in the length compositions for the base model.

Lastly, historical data were available from two additional sources. A dockside sampling effort was undertaken by CDFW during the 1950s--1970s to collect data from the private/rental and party/charter fleets. Data collected from 1958 to 1972 was from [@miller_ocean_1965] and [@miller1973fish], however samples of `r spp` were only available for 1959--1960. Within these years, 45 `r spp` lengths were collected from party/charter vessels and 45 from private/rental vessels. While limited in sample size, these data cover the central to northern districts and represent the lone data from this time period, and so these data were included in length compositions for the base model.

The approach to determine the input sample sizes for the recreational length data varied by data source. Some data sources had unique trip numbers within the data such as the Deb Wilson-Vandenberg data and the \gls{mrfss} sampling program. Other data sources that lacked a clear trip identifier used combinations of multiple fields to attempt to estimate unique combinations that represented the number of trips sampled. In general the number of trips was estimated based on a mix of time, location, and fishery type. The number of trips for length compositions from the \gls{crfs} sampling program was estimated using sampling date, sampling site (COUNTY_NUMBER and INTERVIEW_SITE), fishing area, and mode. The number of trips from Geibel and Collier was estimated using sampling date and sampling port. The number of trips from Miller and Gotshall was estimated using sampling year and month, sampling port, and mode. The number of trips from Miller and Geibel was estimated using sampling year, sampling county, and mode. Collectively, the estimates for the number of trips are meant to represent a reasonable starting point that generally reflects the degree of similarity of information from sampling a given number of likely similar fish within any sampling event.

The magnitude of sampling for lengths from the recreational fleet each year is given in @tbl-rec_lengths, which shows the different sampling frequencies employed over different time periods. This table shows both the total number of fish sampled as well as the number of assumed trips by year over which samples were obtained. The highest number of samples has occurred in years since 2004. As was applied for commercial composition data, years where sample size for length compositions were less than or equal to 5 were excluded from the model during fitting. Implications of this choice were tested as a sensitivity (see @sec-assmt-sens). Across all recreational data sources, length frequency data were aggregated across party/charter and private/rental modes based on similarities in length distributions in areas where they both occurred.

The recreational length frequency distribution is shown in @fig-len-rec-bubbles. The recreational fleets appears to catch slightly smaller fish relative to the commercial fleet, however covers a wider range of sizes, possibly due to the lack of size preference for the recreational fleet. The distribution of lengths of `r spp` observed by the recreational fleet have generally ranged between 20 and 50 cm across all available years. Samples in years prior to 1984 were generally of larger fish but had smaller samples sizes than in more recent years. Increases in size can be seen from the early 2000s to approximately 2015, and an influx of smaller sized fish starting around 2015. The mean length observed by year shows these patterns more clearly (@fig-lenMean-rec). Fish sizes were larger (around 40 cm) but more variable in the earliest years and declined to around 30 cm in 1990. Starting around 1995, mean length began to increase, and reached a peak slightly below 40 cm in 2013, similar to the trend in commercial lengths. Patterns since 2015 are less clear, though 2024 was a unique year given management restrictions on retaining `r spp`. The effect of including 2024 length data for the recreational fleet was explored in sensitivity analyses (see @sec-assmt-sens).


#### Growth fleet Age Composition

**FROG: Not sure where best to put the growth fleet. Since it is a comp, Id suggest here. We could also use this to describe CAAL but I think that is best in the Model structure section**


### Abundance Indices

Several data sources were explored for potential indices of abundance representing the recreational fleet.  The primary survey data sources for recreational fishing are the Marine Recreational Fisheries Statistics Survey (MRFSS) and the California Recreational Fisheries Survey (CRFS).  MRFSS was a federally administered survey that collected data from 1980 to 2003.  CRFS is administered by CDFW and has collected data since 2004.  Both have implemented surveys onboard the PC fleet as well as dockside for both PC and PR.  The frequency of quillback in both the MRFSS and CRFS PC datasets and the MRFSS PR dataset is insufficient to create indices (see Data Considered but not Used **FROG: ADD SECTION NUMBER**).  We also found that a separate CDFW survey of the PC fleet referred to as the Deb Wilson-Vandenberg survey, conducted concurrently with MRFSS, contained insufficient observations of quillback.  Therefore, the only recreational fishery-dependent index included in the model was calculated using CRFS PR data.  
Catch and effort data from the CRFS dockside sampling of private boats between 2004 and 2023 were provided by CDFW.  The data included catch by species, number of anglers contributing to the catch, angler-reported area of fishing, gear, county, port, interview site, year, month, and CRFS district.  See Appendix **FROG: ADD APPENDIX REFERENCE HERE** for details on the data filtering, processing, and model selection.  The CRFS PR index of abundance was highest in 2006 and has showed a declining trend to 2023 (**FROG:  ADD REFERENCE TO FIGURE pr_index_model_cpue_by_year.png**).  However, the 2023 value is comparable to the initial year of 2004.
