## Recreational data

<!-- Commercial fisheries landings by state, year, and gear (PacFIN is the standard source for recent domestic commercial landings), historical catch estimates, discards, recreational fisheries catches, foreign removals; sample size information for length- and age-composition data by state, year and gear, including both the number of trips and fish sampled. Description of methods to estimate abundance indices, sample size information by survey and year. Include complete tables and figures and date of data extraction. -->

#### Landings

#### Discards

#### Length Compositions

#### Age Compositions


### Abundance indices

Several data sources were explored for potential indices of abundance representing the recreational fleet.  The primary survey data sources for recreational fishing are the Marine Recreational Fisheries Statistics Survey (MRFSS) and the California Recreational Fisheries Survey (CRFS).  MRFSS was a federally administered survey that collected data from 1980 to 2003.  CRFS is administered by CDFW and has collected data since 2004.  Both have implemented surveys onboard the PC fleet as well as dockside for both PC and PR.  The frequency of quillback in both the MRFSS and CRFS PC datasets and the MRFSS PR dataset is insufficient to create indices (see Data Considered but not Used **FROG: ADD SECTION NUMBER**).  We also found that a separate CDFW survey of the PC fleet referred to as the Deb Wilson-Vandenberg survey, conducted concurrently with MRFSS, contained insufficient observations of quillback.  Therefore, the only recreational fishery-dependent index included in the model was calculated using CRFS PR data.  
Catch and effort data from the CRFS dockside sampling of private boats between 2004 and 2023 were provided by CDFW.  The data included catch by species, number of anglers contributing to the catch, angler-reported area of fishing, gear, county, port, interview site, year, month, and CRFS district.  See Appendix **FROG: ADD APPENDIX REFERENCE HERE** for details on the data filtering, processing, and model selection.  The CRFS PR index of abundance was highest in 2006 and has showed a declining trend to 2023 (**FROG:  ADD REFERENCE TO FIGURE pr_index_model_cpue_by_year.png**).  However, the 2023 value is comparable to the initial year of 2004.  
