## Fishery-Independent Data <!--(TOR section D2) -->

<!-- Fishery-independent data: Description of surveys used in the assessment, description of methods to estimate abundance indices, sample size information for length- and age- composition data by survey and year, including both the number of tows (or drops or sites for hook and line data) and fish sampled. Include complete tables and figures and date of data extraction.   -->

The base model includes relative abundance indices and length composition data from two primary sources of fishery-independent data: the \gls{s-ccfrp} hook-and-line survey and the \gls{cdfw} \gls{rov} survey. While not used for relative abundance indices or length composition data, biological samples from the \gls{s-wcgbt} were used in estimating biological relationships. 

### \acrlong{s-ccfrp}

The \gls{s-ccfrp}, is a fishery-independent hook-and-line survey designed to monitor nearshore fish populations at a series of sampling locations both inside and adjacent to \glspl{mpa} [@Wendt2009; @Starr2015]. The \gls{s-ccfrp} survey began in 2007 along the central coast of California and was designed in collaboration with academics, \gls{nmfs} scientists and fishermen. In 2017, the survey expanded beyond the four \glspl{mpa} in central California (A&ntilde;o Nuevo, Point Lobos, Point Buchon, and Piedras Blancas) to include the entire California coast. Fish are collected by volunteer anglers aboard party/charter vessels guided by one of the following academic institutions based on proximity to fishing location: Humboldt State University; Bodega Marine Laboratories; Moss Landing Marine Laboratories; Cal Poly San Luis Obispo; University of California, Santa Barbara; and Scripps Institution of Oceanography. `r Spp` were rarely observed south of the Farallon Islands and so this index represents the \glspl{mpa} and reference sites from the Farallon Islands and north. Surveys consist of fishing with hook-and-line gear for 30-45 minutes within randomly chosen 500 by 500 m grid cells within and outside \glspl{mpa}. Prior to 2017, all fish were measured for length and released or descended to depth; since then, some were sampled for otoliths and fin clips. 

### ROV Survey

\gls{rov} surveys have been used to monitor California’s mid-depth habitats (30--100 m) since 2004. While surveys have been conducted since 2004, it has been possible to conduct surveys at only a few locations each year.  Efforts to systematically select survey locations representative of the full California coastline began in 2014 and a full complement of these locations has taken three years to complete. Therefore, locations monitored in 2014--2016 and 2019--2021 are considered to represent complete surveys and were analyzed by \gls{cdfw} as two super years centered on the mid-point of each period (2015 and 2020). The survey is a collaboration between \gls{cdfw} and \gls{mare}. The survey was initially developed to assess the \gls{mpa} network. Sampling has been conducted at \glspl{mpa} along the entire California coast with 500-meter transects conducted within rocky reef habitat inside and outside each \gls{mpa}. A full description of survey methods is available in [@lauermann_rov_2017]. Data includes counts of fish by species, fish sizes, and a variety of characteristics of the transect location. 

### \acrlong{nmfs} Surveys

The \gls{s-wcgbt}, the Hook and Line survey, and the \gls{s-tri} collect data off the California coast on rockfish biology and abundance and are commonly incorporated in West Coast groundfish assessments. The \gls{s-tri} operated between 1977--2004 and \gls{s-wcgbt} has operated since 2003. None of these fishery-independent surveys had adequate sample sizes of `r spp` off California to include as abundance indices for this assessment. There were no more than ten positive tows of `r spp` in any one year coastwide in the \gls{s-wcgbt}, and only seven positive tows in California. Similarly there were no more than five positive tows of `r spp` in any one year coastwide for the \gls{s-tri}, and only one positive tow in California. No `r spp` were captured in the Hook and Line survey. Given that indices of abundance were not calculated due to small sample sizes, length composition data from the \gls{s-wcgbt} (N = 39) and Triennial Survey (N = 1) off California were not included in the base model. Biological data from the \gls{s-wcgbt} were however used in external calculations of biological parameters, as well as internal calculations of growth, as previously described for the growth fleet. No ages or weights for `r spp` were available from the \gls{s-tri}, and so its single length sample was not incorporated.

### Abundance Indices

Methods used to derive the abundance index from the \gls{s-ccfrp} for 2017--2024 are described in @sec-appendix-A. The lowest value in the index occurs in 2019 and the highest in 2024, with an increasing trend since 2021 (@fig-indices). The \gls{rov} survey relative abundance index was derived by \gls{cdfw} staff and the methods are also described in @sec-appendix-A. For both indices, index predictions for density inside and outside \glspl{mpa} are weighted by the estimated relative abundance of habitat in those areas, which is 20% for inside \gls{mpa} sites and 80% for outside \gls{mpa} sites. The \gls{rov} index indicates an increase in abundance between 2015 and 2020 (@fig-indices), which was more pronounced inside than outside \glspl{mpa}. 

An additional effort was made by staff at the \gls{swfsc} to estimate an absolute abundance estimate of `r spp` inside \gls{mpa}s from the \gls{rov} survey data to compare with model estimated abundance (T. Rogers, SWFSC, pers. comm.). The estimates from this effort are described in @sec-appendix-B.  

### Length Composition

The magnitude of sampling for lengths from fishery-independent sources is given in @tbl-survey_lengths, which shows the different sampling frequencies over time. Input sample sizes in the base model were equal to the total number of drifts (for \gls{s-ccfrp}) or transects (for \gls{rov}) that collected a `r spp`. As was done for fishery-independent sources, years with less than or equal to five samples were not included in model fitting, which only occurred in 2016 for \gls{rov} samples. 

\gls{s-ccfrp} length samples were available for years from which the index was calculated, 2017--2024. A total of 1321 length samples were collected, showing smaller sampling effort compared to the recreational fleet during the same years with the exception of 2024. Length compositions were weighted according to their sample location and the percent of habitat inside (20%) and outside (80%) of \glspl{mpa}. The length frequency distribution for \gls{s-ccfrp} is shown in @fig-len-ccfrp-bubbles. The range of sizes is wider compared to fishery-dependent sources, approximately 15--45 cm, which may be due to sampling areas both open and closed to fishing. A greater proportion of smaller sized fish was sampled after 2000, which is also shown when looking at annual mean sizes (@fig-lenMean-ccfrp). No other strong patterns are evident in the length data.   

\gls{rov} length samples were available from 2014--2021. Length composition data were included in the model as actual years rather than super years, as was done for the index. A total of 679 length samples were collected, showing smaller sampling effort compared to the recreational fleet during the same years. As was done for \gls{s-ccfrp} samples, length compositions were weighted according to their sample location and the percent of habitat inside (20%) and outside (80%) of \glspl{mpa}. The length frequency distribution for \gls{rov} is shown in @fig-len-rov-bubbles and shows a wider range of lengths than other fleets, from 10--50 cm. The length composition aggregated across all years shows a bimodal distribution with a mode of small fish between 10--25 cm. This is likely because the \gls{rov} is a visual survey, that it is able to select smaller fish than sampling with hook and line gear. The mean length of fish observed by the survey was highest in 2014, lowest in 2019, then increased through 2021 (@fig-lenMean-rov).