## Biological Parameters <!--(TOR section D3)--> {#sec-biology}

### Natural Mortality

Natural mortality was not directly measured, so life-history based empirical relationships were used. The Hamel and Cope -@hamel_development_2022 method for developing a prior on natural mortality ($M$) for West Coast groundfish stock assessments combines meta-analytic approaches relating the $M$ rate to other life-history parameters such as longevity, size, growth rate, and reproductive effort to provide a prior for $M$. They re-evaluated the data used by Then et al. [-@then_evaluating_2015] by fitting the one-parameter $A_{\text{max}}$ model under a log-log transformation such that the slope is forced to be -1 in the transformed space [@hamel_method_2015]. The point estimate and median of the prior is:

\begin{centering}

$M=\frac{5.4}{A_{\text{max}}}$

\end{centering}

\vspace{0.5cm}

where $A_{\text{max}}$ is the maximum age. The prior is defined as a log-normal distribution with parameters $\mu = ln(5.4/A_{\text{max}})$ and $\sigma = 0.31$. Using a maximum age of 80 years, the point estimate and median of the prior for $M$ is `r mod_in$ctl$MG_parms['NatM_p_1_Fem_GP_1','INIT']` per year.

The maximum age assumed for calculating natural mortality in the base model was 80 years. The value of 80 was obtained from a database of 34,564 age reads for `r spp` from California to Alaska (C. Stuart, Cal Poly Humboldt, pers. comm.) as the maximum age from inside British Columbia waters, and balances the risk associated with a choice of younger samples along the U.S. West Coast and older samples observed in the literature and sampling programs. A maximum age of 95 years for `r spp` from southern British Columbia is often referenced in the literature [@love_rockfishes_2002; @Palssonetal_2009; @YamanakaandLacko_rockfish_2001]. @YamanakaandLacko_rockfish_2001 do not include a figure of the spread of their age estimates, but @cosewic_quillback_2009 provides a figure that appears comparable, and shows the next oldest age sample as 80 years. A maximum age of 90 years from southeast Alaska is also reference among the age validation literature [@munk_agevalidation_2001; @caillet_agevalidation_2001; @kerr_agevalidation_2005]. Literature estimates were larger than the oldest aged `r spp` along the U.S. West Coast (73, 70, and 69), which were sampled from Washington in 1999, and much larger than the oldest aged `r spp` among California samples used for this assessment (57, 51, and 46). We are not aware of other species with as large of a range of ages observed from California to Alaska as is seen for `r spp`. Given that California samples are from recent years, and relatively sparse compared to samples from other regions, it may be expected that older fish would not be observed. 


### Weight-at-Length

The length-weight relationship for `r spp` was estimated outside the model using available California biological data collected from fishery-independent (\gls{s-wcgbt}) and fishery-dependent (\gls{mrfss} and \gls{crfs}) data sources (@fig-weightlength). Only measured weight and length values were used; any values from the \gls{mrfss} dataset with more than two decimal places were assumed to be calculated from another measurement and were excluded. The estimated length-weight relationship for California `r spp` was:
$$
W = `r mod_in$ctl$MG_parms['Wtlen_1_Fem_GP_1', 'INIT']`L^{`r mod_in$ctl$MG_parms['Wtlen_2_Fem_GP_1', 'INIT']`}
$$
where $L$ is fork length in cm and $W$ is weight in kg.

### Maturity

From 2019 to 2025 a total of 88 histological samples were collected from female `r spp` caught off the coast of California (16 by CCFRP and 72 by the \gls{swfsc}). The samples were read by Melissa Head at the \gls{nwfsc} for identification of microscopic functional maturity stage. Functional maturity accounts for abortive maturation and the proportion of oocytes in atresia (cellular breakdown and reabsorption), which could indicate skipped spawning (M. Head, NWFSC, pers. comm.). Seven samples were excluded due to uncertainty in whether the female was spent/resting or experienced abortive maturation, due in part to the timing of the collections during the non-spawning months. The remaining 81 samples ranged in size from 21--45 cm. The six females collected from north of Pt. Arena (Crescent City and Eureka) were all mature. The estimated maturity ogive for California `r spp` was $L_{50\%}$ = `r mod_in$ctl$MG_parms['Mat50%_Fem_GP_1', 'INIT']` cm with a slope of `r mod_in$ctl$MG_parms['Mat_slope_Fem_GP_1', 'INIT']` (@fig-maturity). This is slightly smaller than the value of $L_{50\%}$ = 29.2 used in the 2021 assessment.  

### Fecundity

The fecundity-at-length was based on ovary samples collected by the SWFSC Santa Cruz lab in 2023 and 2024. Two subsamples were collected from each female. Of the females collected during the spawning months, 24 fish were at stage 2, with pre-fertilized vitellogenic eggs.  The fecundity relationship for `r spp` was estimated to be equal to:
$$
F = `r mod_in$ctl$MG_parms['Eggs_alpha_Fem_GP_1', 'INIT']`L^{`r mod_in$ctl$MG_parms['Eggs_beta_Fem_GP_1', 'INIT']`} 
$$
where $F$ is fecundity in millions of eggs and $L$ is fork length in cm (@fig-fecundity). 

### Growth (Length-at-Age) {#sec-growth}

The majority of length-at-age data available for California `r spp` were collected in the last five years. Only 21 otoliths from the \gls{s-wcgbt} were read and available at the time of the 2021 assessment, but efforts during the subsequent reviews resulted in 122 additional age reads by the time the assessment was finalized. However, growth in the final 2021 model did not change throughout the review process and was fixed to the same external fit as the models for Washington and Oregon. Efforts since the 2021 assessment have resulted in substantially more age samples collected and read across a variety of data sources (@tbl-caal_ages). 

An additional 736 age reads were available from otoliths collected from `r spp` off the coast of California across a variety of non-commercial sources from 1985--2024. Available ages used in the external fit to growth only, and not included in the base model were from the following sources: 

* The \gls{s-wcgbt} (N = 34)
* The \gls{swfsc} Groundfish Cooperative Data Collection program during the 2022 fishing season (N = 134)
* The \gls{swfsc} life history research activities (N = 96) 
* The \gls{cdfw} purchased `r spp` from commercial vessels (N = 6)
* The \gls{cdfw} groundfish team sampled recreational private/rental vessels (N = 111) 
* Fish surrendered to \gls{crfs} samplers (N = 55) 
* The \gls{iphc} \gls{fiss} (N = 5)
* Miscellaneous sampling that could not be tracked to a specific data source (N = 9)
* Age-zero fish from Baetscher's dissertation work -@baetscher_2019_larval trapping young-of-the-year rockfish within Monterey Bay using \gls{smurf}s and divers with nets (N = 192). All of the `r spp` captured were morphologically identified as gopher, copper or kelp rockfish, but were genetically identified as `r spp`. 

External estimates of growth from ages across the range of `r spp` do not indicate sexually dimorphic growth (Claire Stuart, Cal Poly Humboldt, pers. comm.), as also found by @LenarzandEcheverria_dimorphism_1991. A number of the `r spp` collected for biological studies targeted females, and so, combined with lack of evidence for sexual dimorphism, we did not estimate dimorphic growth for the California-specific data. 

The estimated growth curve from the available data, estimated externally to the base model, was 
$$
L_{\infty} = 41.18 cm; k = 0.178; t_0 = -0.57 cm 
$$
where $L_{\infty}$ is the asymptotic average length, $K$ is the growth coefficient with units $year^{-1}$, and $t_0$ represents the time when the average length was zero  (@fig-growthdata). The external estimate of $L_{\infty}$ is comparable to literature values, while the estimate of $K$ is on the higher side of literature values which vary from 0.06--0.19 [@YamanakaandLacko_rockfish_2001; @Palssonetal_2009; @Westetal_2014]. Note that Stock Synthesis typically uses the Schnute parameterization of vonBertalanffy growth, and so $t_0$ was converted to a value of $L_{age=1}$ = 10 cm. The external estimates were used to initialize the growth curve, and differ from the growth parameters ultimately estimated internal to the base model.  

## Environmental and Ecosystem Data <!--(TOR section D4)--> 

This model does not explicitly include environmental or ecosystem data. `r Spp` are a rocky habitat associated species and the area of available habitat was considered when developing indices of abundance for the fishery-independent surveys. 





