## Data Sources Considered But Not Used

### Marine Recreational Fisheries Statistics Survey (MRFSS)
The MRFSS program was a federally administered recreational marine fisheries survey conducted between 1980 and 2003.   We explored the potential to produce a fishery-dependent index of abundance using private/rental angler interview data.  The index was ultimately not included in the model due to a very low proportion of samples with quillback  and very large standard deviations around average cpue.  See Appendix A for further detail.  

### Commercial Passenger Fishing Vessel (CPFV) Logbook
CPFV paper logbooks, collected by CDFW in their current form, began to be used in 1980.  This dataset contains individual trip records with information reported by the vessel captain including numbers of fish by species or species group, the port of landing, the 10x10 nautical mile fishing block and depth where the majority of fishing occurred, the number of contributing anglers, and the number of hours spent actively fishing, among other fields.  Captains are required to submit a log for each trip and compliance rates have varied over time.  In 2017, captains were provided with the option to use an electronic log, though the paper log is still acceptable.  Paper logs are limited in species specific fields.  Rockfish are either enumerated in a rockfish genus field that is not species-specific or individual species can be noted using a write-in field.  Most rockfish are not speciated on the paper log.  The electronic log allows for a greater number of species selections using pull-down menus.  A general genus category for rockfish also exists in the electronic log and identification to species is not legally required.  We explored this data for its potential to produce and index of abundance or to inform our understanding of CPFV effort and fishing dynamics over time in the context of quillback rockfish.

We filtered the data to focus on trips more relevant to quillback (**FROG: ADD REFERENCE TO TABLE CPFVLogFilters.csv**).  We excluded trips south of Point Conception where quillback are rare by excluding fishing blocks numbered greater than 650.  We excluded trips occurring between January and March when fishing for rockfish is prohibited.  We included only trips noting their target was rockfish and only single day trips.  Multi-day trips typically target highly migratory species.  Quillback remained rare following these filters with approximately 0.3 % of trips catching one or more quillback.  This was deemed insufficient for production of an index.  

### International Pacific Halibut Commission, Fishery-independent Setline Survey (IPHC-FISS)
The IPHC-FISS survey is designed to provide catch and biological information on Pacific halibut but does retain records on non-target species.  However, the survey is focussed in Alaska and Brittish Columbia and does not frequently extend into California waters.  CDFW is aware of 22 quillback caught in 2014 and five in 2017.  Age data are available for the five fish from 2017.  These data were considered insufficient for inclusion in length or age compositions. 

### West Coast Groundfish Bottom Trawl Survey (WCGBTS), and Triennial Survey

**FROG: This is probably best in the fish-independent data section since some data were used**
The \gls{s-wcgbt} and \gls{s-tri} collect data off the California coast on rockfish biology and abundance. The \gls{s-tri} operated 1977--2004 and \gls{s-wcgbt} has operated since 2003. There were no more than ten positive tows of `r spp` in any one year coastwide in the \gls{s-wcgbt}, and only seven positive tows in California. Similarly there were no more than five positive tows of `r spp` in any one year coastwide for the \gls{s-tri}, and only one positve tow in California. Given that indices of abundance were not calculated due to small sample sizes, length composition data from the \gls{s-wcgbt} (n = 40) and \gls{s-tri} (n = 1) off California were not included in the model. However, biological data (N = 34) from the \gls{s-wcgbt} was used for external calculations of weight-at-length relationships and is used as part of the conditional age-at-length data for the growth fleet. No ages or weights for `r spp` were available from the \gls{s-tri}.




### MRFSS PR Dockside Index of Abundance CAN ADD TO above description
**MOVE TO data sources considered, but not used with just a description and no tables or figures**
The MRFSS program was a federally administered recreational marine fisheries survey conducted between 1980 and 2003. Samplers interviewed private/rental (PR) anglers at launch ramps and other onshore sites similar to today’s CRFS program run by CDFW. We explored the potential to produce a fishery-dependent index of abundance using this PR data. Historic MRFSS records retained by CDFW were used to combine angler and trip data (type 1) with sampler examined catch data (type 3). Type 1 data includes information about fishing mode, location, number of anglers, and their primary and secondary target species for the trip. Type 3 data provides catch information by species including the numbers of fish and their lengths.\
MRFSS samplers collected data on both observed and unobserved fish. Observed fish could be identified to species by the sampler and measured. Unobserved fish were reported by the angler but unavailable to the sampler for a variety of reasons. Because quillback is a relatively rare species in California that may not be correctly identified by anglers, we used only data on observed fish. Additionally, using exclusively observed fish simplifies the calculation of effort (number of anglers) contributing to that catch. Data on observed and unobserved fish were collected on separate forms that lead to complications in accounting for all anglers contributing to a given vessel trip when adding the catch of observed and unobserved fish. The first angler interviewed has been referred to as the “leader” and all subsequent anglers as “followers”. Combining type 1 and type 3 data accounts for all observed fish caught by leaders and followers. We also included only trips with fishing effort and complete interviews.\
We further filtered this dataset to include trips more likely to catch quillback and more representative of possible quillback effort (**FROG: ADD REFERENCE TO TABLE mrfss_index_data_filters.csv**). Two fishing location fields were used to exclude inland waters such as bays and estuaries. We excluded southern California counties where quillback is rare. The time of year was organized into two-month “waves”, and we excluded the first wave representing January and February. Fishing for rockfish was prohibited in these months in 2003 for some central and northern California districts. We included only trips with angler reported primary targets of bottomfish and rockfish which also excluded years between 1980 to 1992 when species target data was not collected. Finally, we removed a trip in 1993 with an extreme outlier catch of 120 quillback. While these filters reduced the overall number of samples by an order of magnitude, quillback remained rare with only about 2.9% positive samples. The resulting average catch per angler trip (cpue) was low with large standard deviations and showed little contrast across the time series (**FROG: ADD REFERENCE TO FIGURE mrfs_pr_cpue.png** - leave out if not using). Therefore, we did not consider this data for further modeling to produce an index.