# Assessment Model

## History of Modeling Approaches <!--(TOR Section E1)-->

### 2010 Data Limited Assessment

`r Spp` was first assessed in 2010 using Depletion-Based Stock Reduction Analysis (DB-SRA) which is a data-limited approach that incorporates catch data with priors on select parameters including natural mortality, the ratio of fishing mortality at maximum sustainable yield to natural mortality, current depletion, and the depletion at maximum sustainable yield to estimate overfishing status, but not overfished status [@DickandMacCall_dbsra_2010]. `r Spp` was assessed as a single coastwide stock to generate an overall OFL (median of 14.8 mt in 2010) that was then apportioned to each management area based on the proportion of historical catches north and south of 40$^\circ$ 10' N. Lat. Assuming that current depletion was at the management target on average (e.g. 40%), the 2010 assessment found that `r spp` had a 52% chance of experiencing overfishing coastwide. 

### 2021 Data Moderate Assessment

In 2021, `r spp` was assessed using Stock Synthesis 3 [@methot_stock_2013] with separate catch and length-based (SS-CL) data-moderate models for each of the three states: Washington, Oregon, and California. These models used catch, length composition, and biological data to assess the portion of the stock within the domain of the model without making assumptions about current depletion. As such, both overfishing and overfished status were estimated. The 2021 spawning output relative to unfished in California was estimated at 0.14 [@Langseth_status_2021]. As such, the portion of the stock in California was found to be overfished and was declared overfished in December 2023 after California `r spp` was defined as a stock via Amendment 31 to the Pacific Coast Groundfish \gls{fmp} [@amendment31_2023]. The 2021 California model fixed steepness at the prior of 0.72 and natural mortality at 0.057 yr^-1^, which corresponds to a maximum age of 95 years [@Langseth_status_2021]. A primary uncertainty of the 2021 California model was the treatment of growth parameters. Given limited age samples from California, growth was fixed in the model based primarily on samples from Oregon and Washington.

The 2021 assessment was initially reviewed at the \gls{ssc} \gls{gfsc} Workshop in June 2021. Additional requests of the \gls{stat} were made during the June Council meeting related to use of additional data sources, age samples, and assumptions about selectivity. The \gls{stat} responses to these requests were presented during a follow-up review meeting in August 2021. Additional requests were made of the \gls{stat} in August related to growth data and assumptions, as well as a rebuilding analysis, and responses to these requests were presented during the mop-up review in September 2021. During the September 2021 Council meeting, the \gls{ssc} endorsed the assessment as the best scientific information available as a category 2 stock and the outcome of the September 2021 review meeting did not alter that endorsement. The \gls{ssc} endorsed the assessment for use in stock status determination and the Council adopted the assessment [@Langseth_status_2021] and rebuilding analysis [@langseth_rebuild_2022] at the November 2021 Council meeting. 

During the process of updating the 2021 rebuilding analysis for the 2023 assessment cycle, public comments were made at the November 2023 Council meeting related to the new rebuilding analysis and the 2021 assessment on which it was based. The Council requested that these comments be reviewed by the \gls{ssc} \gls{gfsc}, and the review occurred in January 2024. The \gls{gfsc}, in [their report](https://tinyurl.com/PFMC2024b), "concluded that the issues raised were considered as part of the 2021 stock assessment or not appropriate given the data limitations and \gls{tor} for data-moderate assessments at the time.... The SSC continues to recommend use of the 2021 stock assessment and the adoption of the 2023 rebuilding analysis for California `r spp`".

## Response to Most Recent STAR Panel and SSC Recommendations <!--(TOR Section E2)--> {#sec-star-recs}

A STAR panel was not convened for the review of the 2021 California `r spp` assessment. Rather, the assessment was reviewed over a series of \gls{gfsc} meetings, as described above. The following responses are a compilation from across the reviews and \gls{ssc} statements spanning 2021--2024, and include recommended research and data needs from the 2021 assessment, and recommendations on future work by the \gls{gfsc} during the January 2024 review. Requests made during the original 2021 reviews in June, August, and September were incorporated within the final 2021 stock assessment report [@Langseth_status_2021]. 


### Recommended Research and Data Needs from 2021 Assessment

**Recommendation**: At the time of the assessment due to issues in California data in PacFIN (i.e., condition code) length samples landed live vs. dead from the commercial fleet were unable to be identified. The ability to examine sample sizes and lengths from each type of landings would allow for future assessments to account for a greater range of commercial fishing behavior.

* **Response**: Condition code or disposition is now an available field in PacFIN.  For the current assessment, the commercial fleet was not split into multiple fleets based on disposition.  Comparisons of fish sold live and dead showed overlapping sizes in years where both were sold and similar frequency distributions combining all years of samples for live and dead.

**Recommendation**: Improved understanding of where recreational fishing is commonly occurring (areas and depths) and the range of sizes available by depth would better inform the selectivity form, which currently is near the shape for maturity.

* **Response**: Recreational fishing location information at the level of survey districts is available from the \gls{crfs} and \gls{mrfss} data sets. We explored both the amount of catch and the size distribution of the catch by district in these time periods and compared these to the abundance and sizes of `r spp` from the \gls{s-ccfrp} and \gls{rov} survey programs.  Recreational fishing depth is available from \gls{crfs} party/charter mode but not from the private/rental mode. Depth information is available from the fishery-independent surveys. We examined all available information on abundance and size distribution with depth as well as how these varied among regions. These explorations were used to inform selectivity forms and time blocks.  

**Recommendation**: Age data were predominantly from Oregon and Washington waters. Collecting length and otolith samples from recreational and commercial catches in California would result in samples from the entire U.S. West Coast informing growth. Otoliths from the \gls{s-wcgbt} survey would also help inform growth. California otoliths identified and aged during model reviews were insufficient to robustly estimate a separate California-specific length-age relationship given the limited sample size of young `r spp` from California. More data, particularly of young and old fish, are needed to be able to robustly estimate a California-specific growth curve and confirm whether growth of
`r spp` differs between California and Washington and Oregon.

* **Response**: Due to a large effort to collect and process `r spp` otoliths from California in the last 5 years, we were able to internally estimate a California-specific growth curve. See @sec-dat for further details. 

**Recommendation**: Recruitment patterns showed lower than average recruitment in the 2000s. Additional data to support such patterns in recruitment would provide additional support for model estimates.

* **Response**: The current base model continues to show mostly below average recruitment in the 2000s. We looked to other available recruitment deviation estimate time series for deeper nearshore species and found that both the assessment of northern copper rockfish from 2023 [@monk_status_2023] and the blue and deacon assessment from 2017 [@dick_status_2018] also showed mostly below average recruitment in that time period.  

**Recommendation**: Catches of `r spp` were particularly high in a few years for both the recreational and commercial fleet. Better understanding the factors contributing to these high catches as well as potential resolutions, should they be needed, would aid in ensuring catch time series are accurate.

* **Response**: Unusually high peaks in recreational and commercial catch estimates were investigated. Consideration was given to a variety of options for modification of the time series to explore the effect of these values on model results. Additionally, the sample data in outlier years was examined along with the expansion/estimation procedures that lead to unusually high values. Ultimately, the decision was made to not modify the time series in favor of consistent estimation procedures across all years. Sensitivity to alternative catch time series is presented in section @sec-assmt-sens.  

### Recommendations from 2024 GFSC Review

Within the GFSC's report for the January 2024 review, they provided a summary of the issues raised during the review (their [Table 1](https://tinyurl.com/PFMC2024b)). The following are a subset of the issues from Table 1 that the GFSC concluded were still potential issues:

**Recommendation**: It is not clear if the maximum age used represents the California component of the population.

* **Response**: We assumed a maximum age of 80 for the 2025 base model. This decision was based on review of the literature and masters thesis work by Claire Stuart at California State Polytechnic University at Humboldt to develop a database of all documented ages from California, Oregon, Washington, British Columbia, and Alaska.  This decision is further discussed in @sec-biology and the implications explored in @sec-profiles.

**Recommendation**: The decline in abundance appears to be driven by the estimated decline in recruitment deviates from 1990-2010, some of which may be compensating for unmodelled changes in selectivity.

* **Response**: Selectivity assumptions in the base model were carefully considered and informed by the regulatory history, comparisons of available catch and length data by region and depth, fits to the data, and likelihoods. Selectivity functional forms and time blocks used in the 2025 base model differ from the 2021 model and are detailed in @sec-structure.  Sensitivities to alternatives are presented in @sec-assmt-sens. 

**Recommendation**: The current assessment suggests that the current exploitation rate is very high, and this seems inconsistent for a stock with a significant area of its habitat closed to fishing or unfished.

* **Response**: The base model does estimate that fishing intensity was above the target for several years up through 2022 but has since fallen below target in response to regulatory changes.  We estimate that approximately 20% of rocky reef habitat within `r spp` range is protected by MPAs. Commercial and recreational season closures and depth restrictions also restrict the proportion of `r spp` subject to fishing.  It is difficult to determine what proportion of the stock has been off limits to fishing over time as these restrictions vary over time and management area and will also have more or less impact given the relative distribution of rocky habitat with depth. `r Spp` in central California have likely experienced relatively high fishing intensity given the placement of depth limits and high fishing effort from Bay Area anglers. Consideration was given to closed areas in a variety of ways. Selectivity time blocks are used in acknowledgement of potential impacts of spatial closures over time. Patterns within \gls{mpa}s are accounted for by both the \gls{s-ccfrp} and \gls{rov} survey abundance indices and length compositions. Additionally, we explored an areas-as-fleets approach to account for spatial differences in size of fish caught, which could reflect differences in management and access to fishing grounds among these regions. This approach increases complexity and results in sparse data for some fleet/time period combinations. The population trajectory with the areas-as-fleets model was similar to the results when assuming state-wide fleet structure, and are described in more detail in @sec-assmt-sens. 

The GFSC also proposed future work in their report from the January 2024 meeting. Recommendations specific to `r spp`, or to assessment teams in general, include:

**Recommendation**: The prior for h should be revisited given the results of recent assessments and recent advancements in methods for constructing h priors, such as the approach developed by Marc Mangel [e.g., @mangel_steepness_2010].

* **Response**: Steepness was fixed at 0.72 with a standard deviation of 0.16 according to the Accepted Practices Guidelines for Groundfish Stock Assessments in 2025 and 2026.

**Recommendation**: The next assessment of `r spp` in California should explore the development of a recreational and/or CCFRP-based index of abundance, comparable to those developed in recent assessments for vermilion (*S. miniatus*), copper, and other nearshore rockfish species.

* **Response**: Three abundance indices were used in the current base model, derived from the \gls{crfs} dockside private/rental, \gls{rov}, and \gls{s-ccfrp} data sets.  Detailed descriptions of these indices can be found in @sec-appendix-A.  

**Recommendation**: The meeting noted that rejecting the 2021 assessment of `r spp` would mean that OFLs would be based on DB-SRA, a “catch-only” method of stock assessment, which is known to be very inaccurate [@free_catchonly_2020]. Research should be conducted to assess what constitutes “too uncertain” given the default of returning to the last assessment, especially in the context of assessments for which there are no previous full or data-moderate assessments.

* **Response**: Stock assessment category assignments are made by the SSC based on recommendations from the \gls{star} panels.  It is possible that an assessment could be assigned a higher category given the availability of the requisite data types but in conducting and reviewing the assessment, those data types are found to be insufficiently informative.  In such cases, the \gls{star} panel may recommend application of additional uncertainty or precautionary measures and we agree that this is an area that would benefit from research. 

<!-- This is a specific to the SSC. I dont think we need to include. UPDATE during final eidts: I plan to keep this in  -->
**Recommendation**: It was noted that turning off the sum-to-zero constraint on penalty in Stock Synthesis increases the value of terminal year depletion. This issue was not raised in the earlier Public Comment, and the SSC should consider this matter when revising the terms of references and accepted practices documents.

* **Response**: The current base model uses the constraint. We explored relaxing this assumption and found that the pattern for the 2021 assessments persists under assumptions for our base model. However, if recruitment deviations start in 1990 (see @sec-assmt-sens) and the sum-to-one constraint is relaxed, model results do not deviate. Consequently, this issue is better explained as a consequence of the sparse composition data available for `r spp`.

**Recommendation**: It was noted that the estimated variances for some recruitment deviations exceeded the value of $\sigma_R$, which is unusual (though has occasionally been seen in other assessments) and unexpected, and may indicate model misspecification. This issue was not raised in the earlier Public Comment and should form the basis for further exploration and could be a diagnostic for future data-moderate assessments.

* **Response**: Several estimates for the standard deviation of recruitment deviations in the base model continue to be above $\sigma_R$, particularly in the 1980s. High uncertainty in recruitment deviations is likely a result of sparse composition data available for `r spp`. We explored starting recruitment deviations after the period of higher uncertainty, as described in @sec-assmt-sens, and results were similar to the base model.  

In addition to the responses to specific comments above, we provide some points of response to general concerns repeated over the duration of the 2021 model review:

* The SSC recommended the next `r spp` assessment be another data-moderate assessment at their June 2021 meeting, though later recommended deferring that decision at their November 2021 meeting. The present 2025 assessment is being conducted as a full benchmark assessment due to a large effort that has been made to conduct additional biological research and age reads of collected otolith samples. 
* Concern was expressed over the influence of fixed parameters on model results in 2021.  All growth parameters are estimated within the current base model. Natural mortality ($M$) and steepness ($h$) are fixed, as is common for West Coast groundfish assessments, particularly those with limited data. However, model investigations showed that $M$ can be estimated while maintaining good fits to the 2025 data. While there is uncertainty regarding the potential longevity of `r spp` in California, we considered the resulting $M$ estimate to result in unreasonably short longevity and maintained a fixed $M$ in the base model. Sensitivities and the suggested axis of uncertainty for the decision table further explore this uncertainty.  
