## Model Structure and Assumptions <!--(TOR Section E)-->

### Modeling Platform and Structure <!--(TOR Section E5)-->

This assessment was conducted using Stock Synthesis version 3.30.23.1, compiled December 5, 2024 (available [online](https://github.com/nmfs-ost/ss3-source-code/releases/tag/v3.30.23.1)). The R package `r4ss`, version 1.52.0 [@r4ss_2021], along with R version 4.4.1
[@r_2024] were used to investigate and plot model fits. The base model is a single-sex (combined across sexes) and single-area model for the coast of California, though `r spp` are rarely caught south of Point Conception. The model includes two fishery fleets (commercial and recreational), two survey fleets (the \gls{s-ccfrp} hook and line survey, and \glspl{cdfw} \gls{rov} survey), and one growth fleet used to inform estimates of growth internal to the model as well as other population dynamics. The model begins in 1916, which is the earliest year of the commercial catch reconstruction. The population was assumed to be unfished and at an equilibrium age structure at this point.

### Model Changes from the Last Assessment <!--(TOR Section E4)-->

A number of changes have been made in the base model compared to that used in the 2021 assessment [@Langseth_status_2021]. These involve changes in data, data sources used, and model assumptions. The change with the largest effect includes the addition of age data, including the use of commercial and \gls{s-ccfrp} conditional-age-at-length distributions, and also the inclusion of the growth fleet to support estimating growth internally in the model as well as other population dynamics. Additional age data were collected during extensive sampling efforts across multiple agencies since the 2021 assessment but were not incorproated in the base model. The effect of the addition of new data on model results is shown in bridging (see @sec-bridging below) and through profiles (see @sec-profiles below), and the effect of omitting some of this data on model results was explored through sensitivity analyses (see @sec-assmt-sens below).

In general, the synthesis and treatment of data has been altered for this assessment based on updated best practices and extensive work by \gls{nwfsc} to document, reproduce, and standardize data processing steps, along with extensive work by staff at \gls{cdfw} and \gls{psmfc} in providing consistent and accurate data in a more easily obtainable manner. Documenting each change is unnecessary, as these are expected to be minor, but we do highlight changes in the processing of total removals. Changes in processing catch data include different approaches to filling in missing years for commercial landings in 1981--1983 (assumed zero for this assessment rather than interpolating from neighboring years), 1990--1992 (based on average of neighboring three years rather than interpolating nearest years); and inclusion of previously omitted quantities by adding missing private/charter sampling for 1993--1995, and including estimates from recent recreational removals reported in numbers but not in weight. For discards, `r spp` in California are now separated out in the \gls{gemm} and therefore easier to add to commercial landings for obtaining total removals. The process for calculating historical dead discards resulted in a lower ratio of dead discards to landings for commercial data, and a different ratio (based on use of an alternative field) of dead discards to landings for recreational data.

New data sources were available for use in this assessment that were outside the scope of the data-moderate \gls{tor} for the 2021 assessment. Two fishery-independent data sources were added to this assessment, the \gls{s-ccfrp} and the \gls{rov} surveys. Both of these surveys were developed to monitor fish inside the network of \glspl{mpa} as well as in adjacent areas open to fishing. The assessment also includes a fishery-dependent index of abundance from the recreational private/rental mode. This is the first assessment for `r spp` to include age composition data to support estimates of growth and population dynamics within the base model. As such, ageing error is now included in this assessment. 

In addition to new data types such as age and survey data, new data sources not available at the time of the 2021 assessment were now available and used in this assessment. New sampling efforts since the 2021 assessment resulted in updated California-specific estimates for fecundity and maturity. The weight-length relationship was also updated using only California data. Historical length data for the recreational fleet from 1959--1960 was recovered from research conducted by Miller and Geibel [@miller1973fish] and Miller and Gotshall [@miller_ocean_1965], and more recent length data for the recreational fleet from 1992--1997 was made available by Miller and Collier [@geibel_prsurvey_2025]. These data were included in the length compositions in the base model.

Lastly, a number of alternative model assumptions were explored and ultimately used for the base model. These include alternative assumptions around maximum age and therefore natural mortality, alternative parameterization of dome-shaped selectivity curves (using three parameter rather than four parameter), and alternative years for blocking selectivity. In addition, data weighting was done according to the algorithm by @francis_data_2011 as opposed to @mcallister_bayesian_1997, which was the method used for the 2021 assessment. Sample sizes used for recreational sources were included as approximations of the number of trips as opposed to number of fish, which was done for the 2021 assessment. 

<!-- Description of new modeling approaches and changes made from the last assessment, with rationale. This should include bridging analyses that highlight the data and model changes that were most influential with respect to changes between the assessment being reviewed and the most recent adopted assessment.  -->

#### Model Changes During 2025 STAR Panel

At the 2025 \gls{star} panel review, changes were made to the amount of newly collected age data used within the base model. The version of the base model brought to the \gls{star} panel included commercial (@tbl-comm_ages) and additional (@tbl-caal_growth) sources of age data for `r spp`, with the additional ages included as a growth fleet. While sources of age data that fall outside normal sampling programs can be incorporated within assessment models as conditional age-at-length data for a growth fleet according to the Accepted Practices Guidelines for Groundfish Stock Assessments, the panel was concerned about the impact these data had on processes other than growth, namely recruitment. The current base model (i.e. the post-STAR base model) includes commercial ages, moved \gls{s-ccfrp} ages outside the growth fleet and into the \gls{s-ccfrp} fleet, and removed all but the Abrams collected ages from the growth fleet. The effect of the change made during the \gls{star} panel is shown in the bridging analysis (see @sec-bridging below) and the details around the effects of inclusion of age data as explored during the panel are provided in a sensitivity analysis (see @sec-assmt-sens below). Unless specifically stated otherwise, all references in this document to the base model refer to the version accepted during the \gls{star} panel review. 


### Bridging Analysis from the 2021 Data Moderate Assessment <!--(TOR Section E4)--> {#sec-bridging}

The exploration of models began by bridging from the 2021 data moderate assessment model to the newest version of Stock Synthesis, version 3.30.23.1. Using the newest Stock Synthesis version resulted in no difference in spawning output from that estimated in 2021 (@fig-bridgeSS3_bio). From there, bridging from the 2021 assessment model to the current base model followed three primary steps:

1. Update life history information to California-specific estimates including natural mortality, growth, length-weight, maturity, and fecundity. 
2. Update data inputs to reflect information currently available. Data was updated by data type (catch, compositions including length and age, and indices), which inherently meant updating data for fleets present in the 2021 assessment and then adding data from fleets added into the current base model that were not in the 2021 assessment.
3. Update selectivity blocks and shapes, and reapply data weighting practices.

To arrive at the final base model, additional revisions were made after these three steps to improve model setup and determine the best fit to the data and following standard practices. These included removing composition data with small sample sizes, making revisions to the recruitment bias adjustment and other model setup values, and then making final revisions to data weightings. Current steps were based on the version of the base model presented at the \gls{star} panel review (i.e. the pre-STAR base model). We add a final bridging run to the last step that includes the change in the model made during the \gls{star} panel review to arrive at the current base model (i.e. the post-STAR base model).  

A thorough description of the current base model is presented separately below (@sec-base-results). This section is intended only to more clearly identify where substantive changes occurred during the bridging analysis. Sensitivities to some of the components within the steps above are included in @sec-assmt-sens.

Changes in model output due to updating biological relationships are shown in Figures [-@fig-bridgeBio_comp]--[-@fig-bridgeBio_recruit]. Updating fecundity greatly increased spawning output (@fig-bridgeBio_comp), which is not surprising given the new curve assumed greater fecundity at larger sizes, but did not have a noticeable effect on spawning output relative to unfished or to summary biomass (@fig-bridgeSmryBio_comp). Updating natural mortality reduced initial spawning output and increased recent spawning output, leading to a greater degree of recovery in spawning output relative to unfished. Updating growth parameters, which at this point in the bridging analysis were entered as fixed parameters and not estimated, also increased recent spawning output, but to a greater degree than natural mortality, resulting in the largest change in spawning output relative to unfished among individual steps. Both of the fixed $L_{\infty}$ and $K$ values were lower than the fixed values used for the 2021 assessment, which were $L_{\infty}$ = 43.04 cm and $K$ = 0.199 [@Langseth_status_2021]. The pattern of change in population dynamics between the 2021 growth assumptions and the new fixed parameters, and between the values assumed for natural mortality were similar to the patterns based on sensitivities and profiles for these two relationships during the 2021 assessment. Changes to growth compressed the pattern in recruitment from the 2021 assessment (@fig-bridgeBio_recruit), which showed peaks in recruitment deviations above one across many years (1987, 1993, 1996, 1999), to large peaks in only two years (1991 and 1995). Other changes to biology did not greatly alter the pattern in recruitment. Collectively, updating the growth curve and natural mortality contributes to the large change in the degree of recovery in spawning output relative to unfished, while updating the fecundity relationship increases the scale of spawning output (though not the scale of ln($R_0$) or summary biomass). 

Changes due to updating data streams are shown in Figures [-@fig-bridgeData_comp]--[-@fig-bridgeData_recruit]. Overall, updates to data resulted in less overall change in the estimated population trajectory than did updates to the biological relationships. Updating the fishery catch and length composition data resulted in decreased spawning output across all years such that spawning output relative to unfished conditions was minimally changed (@fig-bridgeData_comp). When age composition data were included, spawning output increased, and especially so in recent years. This occurred because of increased recruitment both in the largest recruitment events, estimated at 1993 and 1995 at this point in the bridging analysis and in 2012 (@fig-bridgeData_recruit). When growth was allowed to be estimated, leading to a lower estimate of $K$ and larger estimate for $L_{\infty}$ similar to that from the 2021 assessment, recruitment increased in the early 1980s (at 1984) and coalesced around a single peak in the mid 1990s (at 1994), leading to a slightly decreased rate of increase in spawning output in later years. The direction of the change in population trajectory with the change in growth parameters is consistent with the results of the profiles from the 2021 assessment for $L_{\infty}$ but opposite to the pattern observed in the profiles for $K$ [@Langseth_status_2021]. Growth estimation internal to the model is preferred over estimating growth outside the model, although estimates may be influenced by other data types than just conditional age-at-length. Adding the index data, which includes \gls{s-ccfrp}, \gls{rov}, and the recreational private/rental indices resulted in decreases in spawning output in the 2000s relative to other steps, driven primarily by lower recruitment in the peak year (estimated in 1995 at this point in the bridging analysis). However, these data show stronger pulses of recruitment in more recent years. As was found in the biological bridging steps, including age data used in the estimation of growth, caused the largest changes in model trajectories. Collectively however, changes in data resulted in minimal impact on results compared to changes due to updating biological relationships.  

Changes due to updating how selectivity as well as reapplying data weighting procedures are shown in Figures [-@fig-bridgeOther_comp]--[-@fig-bridgeOther_recruit]. Overall, changes to selectivity from the 2021 assessment, which included changes to both the time blocks as well as to the form of selectivity (domed versus asymptotic) had limited effect on population trajectory, especially compared to changes in the previous bridging steps. Spawning output increased when selectivity was updated, though changes in spawning output relative to unfished were minimal (@fig-bridgeOther_comp). A limited effect due to changes in selectivity choices is consistent with results from explorations done throughout the review process for the 2021 assessment [@Langseth_status_2021]. Alternative selectivity treatments were extensively explored during base model selection and are described in sensitivity analyses (see @sec-assmt-sens for details). Applying weighting procedures also resulted in limited changes in both spawning output and spawning output relative to unfished. The current base model differed slightly from the pre-STAR base model. Unfished spawning output was similar, but spawning output and therefore spawning output relative to unfished in recent years was lower in the final base model compared to the pre-STAR base model due to a lower peak in recruitment in the mid 1990s (@fig-bridgeOther_recruit).