## Model Structure and Assumptions

### Modeling Platform and Structure
The assessment was conducted using Stock Synthesis version 3.30.23.1 developed by Dr. Richard Methot at the NOAA, NWFSC [@methot_stock_2013]. This most recent version was used because it included improvements and corrections to older model versions. The previous assessment also used Stock Synthesis but an earlier version, 3.30.16.00; model bridging was performed between both versions of Stock Synthesis and is discussed below. The R package r4ss, version 1.51.0, along with R version 4.4.1 were used to investigate and plot model fits.
<!-- Assessment program and its version used for the assessment (i.e., date executable program file was compiled), description of model structure, definitions of fleets and areas. Description of how the first year that is included in the model was selected and how the population state at the time is defined (e.g., B0, stable age structure). -->

### Balance of Realism and Parsimony


#### Definition of Fleets and Areas {#fleets}
This assessment represents the full California coastline, though `r spp` are rarely caught south of Point Conception. Fleets included two fishing fleets, two survey fleets, and one growth fleet.  The commercial fishing fleet combines all gear types as well as fish sold live and dead.  Comparisons of fish sold in the live and dead dispositions showed overlapping sizes in years where both were sold and similar frequency distributions combining all years of samples for live and dead.  `r Spp` commercial catches are predominatly made with hook and line.  The single recreational fleet combines private recreational (PR) along with commercial passenger fishing vessel (PC) catches.  Comparisons of size distributions between these fishing modes showed that they are very similar when analyzed within the same coastal regions.  The two survey fleets represent the CCFRP and \gls{s-rov} surveys.  The growth fleet combines age and length data from CCFRP, the \gls{s-noaa} Cooperative \gls{s-cpfv} program, \gls{s-cdfw} samples, \gls{s-swfsc} research, and thesis research by Jeff Abrams at Humboldt State University [@abrams_2014].  

#### Initialization of the Model


### Model Parameters
There were 121 estimated parameters in the base model.  This is a single sex model requiring only one of each of the life history parameters.  Estimated parameters included one parameter for $R0$, 5 parameters for growth, 97 recruitment parameters, 3 survey catchability parameters, and 15 selectivity parameters (**FROG Add table reference**).  Fixed parameters were as follows.  Steepness was fixed at 0.72, the mean of the prior.  Natural mortality was fixed at 0.068 yr-1, the median of the prior determined by the maximum age. We assumed a maximum age of 80 for the base model.  This decision was based on review of the literature and masters thesis work by Claire Stuart at California State Polytechnic University at Humboldt to develop a database of all documented ages from California, Oregon, Washington, British Columbia, and Alaska.  The oldest fish documented in California was 57 while the oldest fish in this database overall is from Alaska at 92.  While the ages of the oldest fish in California are low relative to the other west coast regions, sample size is also low and sampling has occurred following exploitation.  For these reasons, we selected a maximum age representative of the likely achievable age that is similar to the oldest fish observed in British Columbia.  Likelihood profiles for natural mortality, as well as bivariate profiles with natural mortality and steepness, are described in section 4.6.3.  Sensitivities to natural  mortality are described in section @sec-assmt-sens. When estimated, natural mortality was higher at 0.082 yr-1 but well within the prior distribution (SE = 0.31). This corresponds to a longevity of 66 years, which may be reasonable.  The consequences of alternative natural mortality values are also explored in the decision tables.  The standard deviation of recruitment deviates was fixed at 0.60 (𝜎𝑅).  A length-weight relationship was fixed at externally derived estimates as described in section 3.4.2 (**FROG Add figure reference**). Maturity-at-length was fixed as described above in Section 3.4.3 (**FROG Add figure reference**).  Fecundity was fixed as described in section 3.4.4 (**FROG Add figure reference**). This represents a departure from the fecundity parameters used for the 2021 assessment which where based on a meta-analysis conducted by @dick_meta-analysis_2017.  The updated fecundity parameters are based on new research conducted at the \gls{s-swfsc} (**FROG Was this published?**) and have a large impact on population scale.  

<!-- Model parameters: estimated and fixed parameters, constraints on parameters, selectivity assumptions, natural mortality, treatment of age reading bias and/or imprecision, and other fixed parameters, description of stock-recruitment constraints or components, critical assumptions, and consequences of assumption failures.  -->

### Key Assumptions and Structural Choices
Population dynamics in this model operate on an annual time step and are initialized from an unfished condition in 1916.  Growth and natural mortality are assumed time invariant.  Age and length structure is modeled from age 0 (recruitment age) to an accumulator age (plus group) of 60 with 1-cm population length bins ranging from 1-59 cm. Length data bins are 2 cm wide from 10-50 cm.  Growth is modeled using the Schnute parameterization of von Bertalanffy growth, with two estimated lengths (ages 0 and L(infinity))(**FROG Is this the right way to say this?**) and a growth rate coefficient ($k$).       

A key structural choice was to model a single sex.  The availability of length and age data for sexed fish in California is sparse.  Exploration of the available data showed similar growth and length-weight relationships across the sexes.  @love_rockfishes_2002 showed that `r spp` don't exhibit dimorphic growth until approximately age 30, with an estimated L(infinity) of 0.5 cm greater for females than males. @lenarz_echeverria_1991 also found limited evidence of sexual dimorphism in `r spp`.  Given the sparse data for older `r spp` and the modest difference in estimated L(infinity), growth is assumed to be the same for males and females in this assessment. 

Discuss addition of discards to retained catch?  

Another key structural choice was to model `r spp` coastwide for California using one recreational and one commercial fleet.  The rationale for combining different modes of fishing into single recreational and commercial fleets is described above.  Commercial and recreational regulations governing the harvest of nearshore rockfish have varied among spatial management regions (**FROG Insert figure references for com & rec regs visualizations**).  ROV data show that the size distributions of `r spp` vary in space.  Most notably, larger `r Spp` are heavily represented north of latitude 40 degrees, 10 seconds North, while smaller `r spp` are found in the region between Point Arena to Pigeon Point.  These differences could warrant a two-area model.  However, `r spp` is a relatively rare species and lacks the data required for that approach.  Therefore, we considered a fleets-as-areas (FAA) approach as a hybrid method which would implement two commercial and two recreational fleets representing the areas north and south of Point Arena.  Catch, length, and conditional age at length data are separated into the four fleets.  This approach assumes a single stock with common life history characteristics.  Similarly, survey indices are designed to be representative of the full stock and were therefore not split into two regionally focused indices.  In contrast, we considered the \gls{s-crfs} dockside PR index to be representative of the recreational catch fleet, and not necessarily the stock.  Therefore, we separated this index into two indices derived from data north and south of Point Arena to be associated with each of the two recreational fleets.  We explored FAA approaches splitting both recreational and commercial fleets as well as splitting only the recreational fleet.  Commercial length data sample sizes are very limited in some port regions, necessitating mirroring of selectivities for some time blocks between the commercial FAA fleets north and south of Point Arena (**FROG Do we want a figure here?**).  We considered this to somewhat defeat the purpose of the approach.   Differences in results between the base model and FAA approaches were minor relative to the large increase in complexity added and these sensitivities are presented in section @sec-assmt-sens.  

A growth fleet was used to inform the model's internal growth estimates, incorporating all available age samples that could not be associated with a catch fleet.  The growth fleet uses conditional age at length data from CCFRP, the \gls{s-noaa} Cooperative \gls{s-cpfv} program, \gls{s-cdfw} samples, \gls{s-swfsc} research, and thesis research by Jeff Abrams at Humboldt State University [@abrams_2014].  All of these data sources use hook and line collection techniques and therefore may be considered to have similar selectivity to the recreational catch fleet.  However, other criteria must also be met for samples to be considered representative of a catch fleet.  First, sample sizes per year should be greater than 50.  Second, the survey should be subject to the same spatial management restricts and not be subject to other sampling restrictions not placed on the catch fleet.  Third, fish voluntarily surrendered by anglers may be biased towards smaller sizes.  Each of these data sources met one or more of these criteria and therefore were incorporated in the growth fleet.  

<!-- Evidence of search for balance between model realism and parsimony. Key model assumptions and structural choices (e.g., asymptotic vs. domed selectivities, constant vs. time-varying selectivities). Summary of alternate model configurations that were examined but rejected. This is not required for an update assessment.### Bridging analysis -->

#### Model Likelihood Components
The largest contributor to the total likelihood is age composition data, followed by length compositions, then the survey and recruitment likelihoods (**FROG Add table reference**).  

#### Data Weighting
Recreational length composition data started with a sample size equal to the number of length samples and was not expanded by regional catches (**FROG Is this right?**).  Commercial length composition data was expanded based on both the catches of individual hauls or trips, then based on regional catches using functions within the R package pacfintools.  Sample size is equal to the number of length samples (** FROG Is this right?**).  Age composition data were input as conditional-age-at-length with input sample size equal to the number of ages.  The base model was weighted using the “Francis method”, which was based on equation TA1.8 in @francis_data_2011 which was selected based on model stability and consistency to identify the minimum likelihood estimate (MLE). This formulation looks at the mean length or age and the variance of the mean to determine if across years, the variability is explained by the model. If the variability around the mean does not encompass the model predictions, then that data source should be down-weighted. This method accounts for correlation in the data (i.e., the multinomial distribution). Length compositions were down weighted for both catch fleets and both survey fleets.  Age composition data were down-weighted for the commercial catch fleet and the growth fleets.  No age compositions were available for the other fleets.  Sensitivities were performed examining the difference in the model fits and results due to weighting using McAllister-Ianelli Harmonic Mean Weighting and the Dirichlet Multinomial Weighting (2017).

#### Priors and Constraints on Parameters
Priors were used to determine fixed parameter values for natural mortality and steepness in the base model. The prior distribution for natural mortality was based on the @hamel_development_2022 meta-analytic approach with an assumed maximum age of 80 years. The prior assumed a log normal distribution for natural mortality. The log normal prior has a median of 0.068 yr-1 and a standard error of 0.31. The prior for steepness assumed a beta distribution with mean of 0.72 and standard error of 0.16. The prior parameters are based on the Thorson-Dorn rockfish prior (commonly used in past West Coast rockfish assessments) conducted by James Thorson (personal communication, \gls{s-nwfsc}, \gls{s-noaa}), which was reviewed and endorsed by the \gls{s-ssc} in 2017. However, this approach was subsequently rejected for future analysis in 2019 when the new meta-analysis resulted in a mean value of approximately 0.95. In the absence of a new method for generating a prior for steepness the default approach reverts to the previously endorsed method, the 2017 value.

#### Selectivity assumptions
Selectivity based on size only, and not age or sex-specific selectivity, was used in the model.  Size selectivity curves represent the change in probability of capture with size.  This results from the capabilities of the gear as well as a variety of other combined fishing and ecosystem dynamics that determine what sized fish a fleet has access to. For example, spatial restrictions may increase the selectivity of small or large fish given habitat or ontogenetic patterns that drive where smaller or larger fish can be found, even if the gear itself is capable of selecting a wide range of sizes.  For `r spp`, we find that large fish are present throughout the stock's range, in both shallow and deeper waters.  Smaller fish tend to be present in the shallower portion of the species range.  This is evident in the ROV data and was also observed in British Columbia waters by @murie_comparative_1991. 

Time varying selectivity was implemented for both the commercial and recreational fleets using double normal curves.  Assumptions for the shapes of curves and timing of blocks was driven by a combination of model fits, likelihoods, and knowledge of fishery and regulatory dynamics over time.  Four time blocks for the commercial fleet allowed separate selectivity parameterizations during the periods 1916--2002, 2003--2013, 2014--2021, and 2022--2024.  The first of those four is allowed to be dome shaped by estimation of the peak, ascending width, and descending width parameters.  All other blocks estimate the peak and ascending width.  The early time period is inclusive of the 1980s and 1990s when the live rockfish fishery was most active and may have been targeting intermediate-sized fish. The periods between 2003--2013 and 2022--2024 were times of fishery restriction @fig-com_regs_vis.  A variety of new depth limits, trip limits, and permit structures were implemented around 2003.  Trip limits were markedly reduced in 2022 and further limits specific to `r Spp` occurred in 2023 and 2024.  These periods are parameterized as asymptotic curves with a peak at relatively small sized fish that is similar to the peak of the early 1916--2002 period.  In contrast, the 2014-2021 period corresponds to modest increases in trip limits and allowable fishing depths.  This may have provided greater access to deeper waters where larger fish are prevalent, thus shifting the asymptotic curve's peak to the right. 

Two time periods were estimated for the recreational fleet.  These were 1916--2016 and 2017--2024.  During the period of 2000 to 2003, recreational depth and season restrictions were being implemented for nearshore rockfish the first time in California @fig-fishing_regs_rec.  However, explorations of time blocks before and after that period did not result in meaningfully different selectivity curves and we therefore modeled consistent selectivity before and after those regulatory changes.  The asymptotic peak for the initial block is shifted to the left (i.e. smaller fish), perhaps corresponding to fishing dynamics in the very early years with anglers remaining relatively close to shore by choice or due to vessel capacity, as well as later years when they were restricted closer to shore through regulation.  In contrast, the next block representing 2017-2024 is shifted to the right (i.e. larger fish) and most years during this period correspond to a period of regulatory relaxation.  

The selectivity parameters estimated for the later time blocks of commercial and recreational selectivity are also applied to future years during forecasts.  Given that very recent restrictions in 2003 have not allowed for the collection of much data since that time, it is difficult to estimate selectivity parameters representative of that restricted period.  It is also difficult to know what selectivity dynamics will look like in the coming years, i.e. whether they will be more similar to this recent restricted period or an earlier period.  
Asymptotic selectivity parameterizations were used for both survey fleets.  The peak corresponds to selection of smaller fish for CPFV relative to ROV.  This is consistent with differences in survey depths with CCFRP operating to only 60 m depth and ROV extending as deep as 100 m.  

Sensitivities to a variety of alternative selectivity curves and time blocks are presented in section @sec-assmt-sens.  

#### Stock Recruitment Function
Year-class strength is estimated as deviations from a Beverton-Holt stock-recruitment relationship beginning in 1978 and ending in 2021. Early recruitment deviation estimation was set to begin in 1940.  As part of the tuning procedure, the first and last years of bias adjustment were set near 2002 and 2019.  