## Model Structure and Assumptions


### Model Changes from the Last Assessment

<!-- Description of new modeling approaches and changes made from the last assessment, with rationale. This should include bridging analyses that highlight the data and model changes that were most influential with respect to changes between the assessment being reviewed and the most recent adopted assessment.  -->

### Bridging Analysis from the 2021 Data Moderate Assessment

The exploration of models began by bridging from the 2021 data moderate assessment model to the newest version of Stock Synthesis, version 3.30.23.1. Using the newest Stock Synthesis version resulted in no difference in spawning output (@fig-bridgeSS3_bio). From there, bridging from the 2021 assessment model to the current base model followed three primary steps:

1. Update life history information including natural mortality, growth, length-weight, maturity, and fecundity. 
2. Update data inputs to reflect best information currently available. Data was updated by data type (catch, compositions including length and age, and indices), which inherently meant updating data for fleets present in 2021 (as well as currently) and then fleets added into the current base model that were there in the 2021 assessment.
3. Update selectivity blocks and type, and reapply data weighting practices.

To arrive at the final base model additional revisions were made after these three steps to determine the best fit to the data and following standard practices. These include removing fits to composition data with small samples sizes, adjusting the growth parameterization to use length at age 1 as a parameter instead of length at age 0, revisions to the recruitment bias-adjustment, and final revisions to data weightings.

A thorough description of the current base model is presented separately below **FROG: Add secction reference for base model**. This section is intended only to more clearly identify where substantive changes occurred from changes made from the previous data moderate assessment. Sensitivities to some of the components within the steps above are included in @sec-assmt-sens.

Changes due to updating biological relationships are shown in @fig-bridgeBio_comp. Updating fecundity greatly increased spawning output, which is not surprising given the new curve assumed greater fecundity at larger sizes, but did not have a noticeable effect on spawning output relative to unfished. Updating natural mortality reduced initial spawning output and increased recent spawning output, leading to a greater degree of recovery in spawning output relative to unfished. Updating growth parameters, which at this point in the bridging analysis were entered as fixed parameters and not estimated, also increased recent spawning output, but to a greater degree than natural mortality, resulting in the largest change in spawning output relative to unfished among individual steps. These findings were similar to those from sensitivities to these two relationships during the 2021 assessment [@Langseth_status_2021]. Collectively, updating the growth curve and natural mortality contributes to the large change in the degree of recovery in spawning output relative to unfished, while updating the fecundity relationship increases the scale of spawning output. 

Changes due to updating data streams are shown in @fig-bridgeData_comp. Overall, updates to data resulted in less overall change in the estimated population trajectory than did updates to the biological relationships. Updating the fishery catch and length composition data resulted in decreased spawning output across all years such that spawning output relative to unfished conditions were minimally changed.  When age composition data were included, spawning output increased, and especially so in recent years. This occurred because of increased recruitment both in the largest recruitment year (at this point 1996) and in 2012. When growth was allowed to be estimated, leading to a lower estimate of $K$ and larger estimate for $L_{\infty}$, the rate of increase in spawning output relative to unfished decreases in recent years. The change in population trajectory with change in growth parameters is consistent with the results of the profiles from the 2021 assessment [@Langseth_status_2021]. Adding the index data, which includes \gls{s-ccfrp}, \gls{rov}, and the recreational private/rental index resulting in decreases in recent spawning output relative to other steps, driving primarily due to lower recruitment in the peak year (at this point 1996). As was found in the biological bridging steps, biological relationships, including  Age data used in the estimation of growth cause the largest changes in model trajectories. Collectively however, changes in data result in minimal changes compared to changes due to updating biological relationships.  

Changes due to updating how selectivity was modeled as well as reapplying data weighting procedures are shown in @fig-bridgeOther_comp. Overall, changes to selectivity from the 2021 assessment, which included changes to both the blocks as well as to the form of selectivity (domed versus asymptotic) had limited effect on population trajectory. Spawning output increased when selectivity was updated, though changes in spawning output relative to unfished were minimal. A limited effect due to changes in selectivity choices is consistent with results from explorations done throughout the review process for the 2021 assessment [@Langseth_status_2021]. Alternative selectivity treatments were extensively explored and are described in sensitivity analyses (see @sec-assmt-sens for details). Applying weighting procedures resulted in negligible changes in both spawning output and spawning output relative to unfished. Various additional changes as described above result in the final base model.
