## Base Model Structure (TOR Section E5)

### Assessment Program

The assessment was conducted using Stock Synthesis version 3.30.23.1, compiled December 5, 2024 (available [online](https://github.com/nmfs-ost/ss3-source-code/releases/tag/v3.30.23.1)).

## Base Model Selection (TOR Section F1)

The base assessment model for `r spp` was developed to balance parsimony and realism, with the goal of estimating a spawning output trajectory for the population of `r spp` off `r state`. The base model represents a balance among the number of model parameters, the model fits to dat and minimizing the negative log-likelihood, as well as accurately representating the fisheries' behaviors and species' biology. The model contains many assumptions to achieve parsimony, i.e., reduction in time blocks for selectivity parameters, and balances that with new biological data representing the California stock of `r spp`.

### Key Assumptions and Structural Choices

Model specifications were informed by discussions with the Pacific Fishery Management Council’s Groundfish Management Team and Groundfish Advisory Panel advisors and through comments and discussion during the [pre-assessment workshop](https://tinyurl.com/janpfmc2025). This included a discussion of fleet structure, the potential ability to estimate growth within the model, and acknowledgement of years with high estimated catch, potential time blocks for selectivity paramaters, and the choice of maximum age that is used to estimate natural mortality.

Another key structural choice was to model `r spp` coastwide for California using one recreational and one commercial fleet.  The rationale for combining different modes of fishing into single recreational and commercial fleets is described above.  Commercial and recreational regulations governing the harvest of nearshore rockfish have varied among spatial management regions (Figures [@fig-com-regs-vis] and [@fig-rec-regs-vis]).  However, `r spp` is a relatively uncommon species and lacks the data required for that approach.  Therefore, we considered a fleets-as-areas (FAA) approach as a hybrid method which would implement two commercial and two recreational fleets representing the areas north and south of Point Arena.  Catch, length, and conditional age at length data are separated into the four fleets.  This approach assumes a single stock with common life history characteristics.  
Differences in results between the base model and FAA approaches were minor relative to the large increase in complexity added and these sensitivities are presented in section @sec-assmt-sens. 

The specifications of the assessment are listed in [tbl-model-config]. This assessment represents waters off the coast of California and population dynamics in this model operate on an annual time step, initialized from an unfished condition in 1916. Growth and natural mortality are assumed time invariant. Age and length structure is modeled from age 0 (recruitment age) to an accumulator age (plus group) of 60 with 1 cm population length bins ranging from 1-59 cm. Length data bins are 2 cm from 10--50 cm with population bins at 1 cm.  Growth is modeled using the Schnute parameterization of von Bertalanffy growth, with two estimated lengths (ages 2 and $L_{\infty}$) and a growth rate coefficient (*k*). The availability of length and age data for sexed fish in California is sparse. -@lenarz_echeverria_1991 found limited evidence of sexual dimorphism in `r spp` and all other U.S. West Coast assessments model `r spp` as a single sex. Growth is assumed to be the same for males and females in this assessment. 


The model is conditioned on landings from the commercial and recreational fleets. Noticible increases in the lengths of `r spp` caught in both fisheries north of Point Arena $38^\circ 55^\prime$ N lat. were discussed at the pre-assessment workshop and led the STAT to explore an areas-as-fleets model structure, described in @sec-assmt-sens.  Due to poor model fits and sparcity of the data, the STAT modeled California as a single area. 

The commercial fishing fleet combines all gear types as well as fish sold dead and as part of the life fish fishery. Estimated discards based on \gls{wcgop} were used to estimate discard mortality for both commercial fleets and were added to the landings to estimate total catch. Comparisons of fish sold in the live and dead dispositions showed overlapping sizes in years where both were sampled and similar frequency distributions combining all years of samples for live and dead. `r Spp` commercial catches are predominatly caught with hook-and-line gear.
 
The single recreational fishery combines cathces from the private/rental and party/charter fleets. Comparisons of size distributions between these fishing modes showed that they are very similar when analyzed within the same coastal regions. The lengths of recreational discards were avaialable from the Deb-Wilson Vandenberg and \gls{cdfw} \gls{crfs} onboard observer surveys of the party/chrater fleet. No lengths of discarded `r spp` were available from the recreational private/rental fleet. The recorded discarded fish were smaller fish than those retained prior to the one fish sub-bag for `r spp` enacted in January 2023. The recreational discard mortality available in RecFIN were combined with retained catch to estimate total recreational landings. 

Additional available age structures that could not be linked to one of the fleets above or represented a subset of information from a fleet were included in a growth fleet. The growth fleet uses conditional age at length data from \gls{s-ccfrp}, the \gls{swfsc} \gls{gcdc} program, \gls{cdfw} samples, \gls{swfsc} life history research, and thesis research by Jeff Abrams at Humboldt State University [@abrams_2014].  All of these data sources use hook-and-line collection techniques and the selectivity was set at one for all ages. Fish collected from the recreational fishery had differing length distributions than the fish sampled by \gls{recfin} and therefore we did not include these fish in the recreational fleet. The \gls{ccfrp} survey ages were limited to 30 fish per year outside of \gls{mpa}s by a scientific collecting permit and were not necessarily representative of `r spp` encountered in the survey since they did not represent fish caught within the \gls{mpa}.

The model was fit to one fishery-dependent index of abundance representing retained, sampler-observed catch from the private/renal fleet and two fishery-independent indices from the \gls{s-ccfrp} and \gls{rov} surveys. Each of the survey data sources were used to create an index of relative abundance with assumed lognormal standard error structure.

### Selectivity Assumptions

Time blocks on selectivity and selectivity forms were explored extensively when setting up the initial model structure.
Length-based selectivity curves represent the change in probability of capture with size. This results from the capabilities of the gear as well as a variety of other combined fishing and ecosystem dynamics that determine what sized fish a fleet has access to. California's fisheries are managed with depth and spatial restrictions that likely change afftec selectivity.  For `r spp`, we find that larger fish are present at all depths and smaller fish more commonly present in the shallower depths. This is evident in the ROV data and was also observed in British Columbia waters by @murie_comparative_1991. 

Time-varying selectivity was applied to both the commercial and recreational fleets using double normal curves.  Assumptions for the shapes of curves and timing of blocks was driven by a combination of model fits, likelihoods, and knowledge of fishery and regulatory dynamics over time.  Four time blocks for the commercial fleet allowed separate selectivity parameterizations during the periods 1916--2002, 2003--2013, 2014--2021, and 2022--2024.  The first of those four is allowed to be dome shaped by estimation of the peak, ascending width, and descending width parameters.  All other blocks estimate the peak and ascending width.  The early time period is inclusive of the 1980s and 1990s when the live rockfish fishery was most active and may have been targeting intermediate-sized fish. The periods between 2003--2013 and 2022--2024 were times of fishery restriction (@fig-com-regs-vis).  A variety of new depth limits, trip limits, and permit structures were implemented around 2003.  Trip limits were markedly reduced in 2022 and further limits specific to `r Spp` occurred in 2023 and 2024.  These periods are parameterized as asymptotic curves with a peak at relatively small sized fish that is similar to the peak of the early 1916--2002 period.  In contrast, the 2014-2021 period corresponds to modest increases in trip limits and allowable fishing depths.  This may have provided greater access to deeper waters where larger fish are prevalent, thus shifting the asymptotic curve's peak to the right. 

Two time periods were estimated for the recreational fleet.  These were 1916--2016 and 2017--2024.  During the period of 2000 to 2003, recreational depth and season restrictions were being implemented for nearshore rockfish the first time in California (@fig-rec-regs-vis).  However, explorations of time blocks before and after that period did not result in meaningfully different selectivity curves and we therefore modeled consistent selectivity before and after those regulatory changes.  The asymptotic peak for the initial block is shifted to the left towards smaller fish, perhaps corresponding to fishing dynamics in the very early years with anglers remaining relatively close to shore by choice or due to vessel capacity, as well as later years when they were restricted closer to shore through regulation. In contrast, the next block representing 2017-2024 is shifted to the right representing larger fish and most years during this period correspond to a period of regulatory relaxation.  

The selectivity parameters estimated for the later time blocks of commercial and recreational selectivity are also applied to future years during forecasts. Given that very recent restrictions in 2003 restricting data collection since that time, it is difficult to estimate selectivity parameters representative of that restricted period. It is also difficult to know what selectivity dynamics will look like in the coming years, i.e. whether they will be more similar to this recent restricted period or an earlier period.  

Asymptotic selectivity parameterizations were used for both survey fleets. The peak corresponds to selection of smaller fish for \gls{cpfv} relative to \gls{rov}. This is consistent with differences in survey depths with \gls{s-ccfrp} operating to only 60 m depth and \gls{rov} extending as deep as 100 m.  

Sensitivities to a variety of alternative selectivity curves and time blocks are presented in section @sec-assmt-sens.  


<!-- Evidence of search for balance between model realism and parsimony. Key model assumptions and structural choices (e.g., asymptotic vs. domed selectivities, constant vs. time-varying selectivities). Summary of alternate model configurations that were examined but rejected. This is not required for an update assessment.### Bridging analysis -->

## Model Parameters (TOR Section E5)

There were 121 estimated parameters in the base model.  This is a single sex model requiring only one of each of the life history parameters.  Estimated parameters included one parameter for $R0$, 5 parameters for growth, 97 recruitment parameters, 3 survey catchability parameters, and 15 selectivity parameters (@tbl-n-param and @tbl-pars).  Fixed parameters were as follows.  Steepness was fixed at 0.72, the mean of the prior.  Natural mortality was fixed at 0.068 yr-1, the median of the prior determined by the maximum age. We assumed a maximum age of 80 for the base model.  This decision was based on review of the literature and masters thesis work by Claire Stuart at California State Polytechnic University at Humboldt to develop a database of all documented ages from California, Oregon, Washington, British Columbia, and Alaska.  The oldest fish documented in California was 57 while the oldest fish in this database overall is from Alaska at 92.  While the ages of the oldest fish in California are low relative to the other west coast regions, sample size is also low and sampling has occurred following exploitation.  For these reasons, we selected a maximum age representative of the likely achievable age that is similar to the oldest fish observed in British Columbia.  

Likelihood profiles for natural mortality, as well as bivariate profiles with natural mortality and steepness, are described in section 4.6.3.  Sensitivities to natural  mortality are described in section @sec-assmt-sens. When estimated, natural mortality was higher at 0.082 yr-1 but well within the prior distribution (SE = 0.31). This corresponds to a longevity of 66 years, which may be reasonable.  The consequences of alternative natural mortality values are also explored in the decision tables.  The standard deviation of recruitment deviates was fixed at 0.60 (𝜎𝑅).  A length-weight relationship was fixed at externally derived estimates as described in section 3.4.2 (@fig-weightlength). Maturity-at-length was fixed as described above in Section 3.4.3 (@fig-maturity).  Fecundity was fixed as described in section 3.4.4 (@fig-fecundity). This represents a departure from the fecundity parameters used for the 2021 assessment which where based on a meta-analysis conducted by @dick_meta-analysis_2017.  The updated fecundity parameters are based on new research conducted at the \gls{swfsc} and impact on population scale.  

Year-class strength is estimated as deviations from a Beverton-Holt stock-recruitment relationship beginning in 1978 and ending in 2021. Early recruitment deviation estimation was set to begin in 1940.  As part of the tuning procedure, the first and last years of bias adjustment were set near 2002 and 2019. The recruitment deviations are constrained to sum to zero. The deviations summed to approximately five when allowed to vary freely, and the model was not as well fit.  

### Priors and Constraints on Parameters

Priors were used to determine fixed parameter values for natural mortality and steepness in the base model. The prior distribution for natural mortality was based on the @hamel_development_2022 meta-analytic approach with an assumed maximum age of 80 years. The prior assumed a log normal distribution for natural mortality. The log normal prior has a median of 0.068 yr-1 and a standard error of 0.31. 

The prior for steepness assumed a beta distribution with mean of 0.72 and standard error of 0.16. The prior parameters are based on the Thorson-Dorn rockfish prior (commonly used in past West Coast rockfish assessments) conducted by James Thorson (personal communication, \gls{nwfsc}, \gls{noaa}), which was reviewed and endorsed by the \gls{ssc} in 2017. However, this approach was subsequently rejected for future analysis in 2019 when the new meta-analysis resulted in a mean value of approximately 0.95. In the absence of a new method for generating a prior for steepness the default approach reverts to the previously endorsed method, the 2017 value.

### Data Weighting

Recreational length composition data started with a sample size equal to the number of trips and was not expanded by regional catches.  The initial input sample sizes for the commercial length composition data were based on the equation in @sec-fish-dep.  Age composition data were input as conditional-age-at-length with input sample size equal to the number of ages.  

The base model was weighted using the Francis method, which was based on equation TA1.8 in @francis_data_2011. This data weighting method was chose over the McAllister-Iannelli Harmonic Mean Weight method due to improved model fits[-@mcallister_bayesian_1997].

The Francis method looks at the mean length or age and the variance of the mean to determine if across years, the variability is explained by the model. If the variability around the mean does not encompass the model predictions, then that data source should be down-weighted. This method accounts for correlation in the data (i.e., the multinomial distribution). Three iterations of the Francis method resulted in converged estimates. 

Sensitivities were performed examining the difference in the model fits and results due to weighting using McAllister-Ianelli Harmonic Mean Weighting and the Dirichlet Multinomial Weighting (2017).