## Base Model Results (TOR section F and G) {#sec-base-results}

<!---
**FROG: Melissa, I think the time series of rec and recdev are better placed in the population trajectory section. I have the same figrues there, just commented out. Id suggested moving this first sentence to there. The largest contributor to the total likelihood is age composition data, followed by length compositions, then the survey and recruitment likelihoods.**
--->

### Parameter Estimates (TOR section F2 and G1, G4, G5, H3)

The parameter values, both fixed and estimated, along with approximate asymptotic standard errors of estimated parameters are shown in @tbl-pars and the overall likelihood components by data type are shown in @tbl-likelihood. Estimates of population size and spawning output relative to unfished over time are shown in @tbl-timeseries. 

The ln($R_0$) was estimated at `r round(mod_out$parameters['SR_LN(R0)', 'Value'], 3)`. The model estimated growth parameters and variability as 
$L_{age=1}$ = `r round(mod_out$parameters['L_at_Amin_Fem_GP_1', 'Value'], 3)` 
(CV = `r round(mod_out$parameters['CV_young_Fem_GP_1', 'Value'], 3)`) cm and 
$L_{\infty}$ = `r round(mod_out$parameters['L_at_Amax_Fem_GP_1', 'Value'], 3)` 
(CV = `r round(mod_out$parameters['CV_old_Fem_GP_1', 'Value'], 3)`) cm.  The $K$ parameter was estimated as 
`r round(mod_out$parameters['VonBert_K_Fem_GP_1', 'Value'], 3)`. The estimated $L_{\infty}$ was 1.57 cm larger than the initial externally estimated fixed value, whereas the estimated $K$ value was smaller than the initial externally estimated fixed values. These values however remain within the range of biological parameters observed for `r spp` across their range.   

Length-based selectivity curves were estimated for the fishery and survey fleets, and length-based selectivity was fixed at 1.0 starting at age 1 for the growth fleet (@fig-selex). Model explorations included parameterizing the fleets with double normal selectivity and explorations of time blocks (see @sec-assmt-sens). The survey fleets did not include time blocks and the double normal selectivity patterns were fixed to reflect asymptotic selectivity. The ROV survey observed a wider range of sizes than the CCFRP survey, though the peak size for the ROV survey was estimated higher, at
`r round(mod_out$parameters['Size_DblN_peak_CA_ROV(5)', 'Value'], 1)` cm compared to 
`r round(mod_out$parameters['Size_DblN_peak_CA_CCFRP(4)', 'Value'], 1)` cm for CCFRP. The fishery selectivities were all estimated as asymptotic except for the early time period of the commercial fleet that estimated the peak domed selectivity at `r round(mod_out$parameters['Size_DblN_peak_CA_Commercial(1)_BLK1repl_1916', 'Value'], 1)`, indicating size selection away from larger sized individuals during that period.

The catchability for each of the surveys was estimated comparing observed to expected vulnerable biomass across all years. Estimates are reported in Table [-@tbl-pars] in natural log-space. Analytical solutions for catchability to maintain a mean difference in observed versus expected of zero (described in Stock Synthesis as 'float Q') gave similar results to when estimating catchability but our preference was to include catchability as an estimated parameter. 

The estimated annual recruitment and recruitment deviations are shown in Figures [-@fig-recruits] and [-@fig-rec-devs]. The strongest recruitment event occurred in 1994 and was followed by a period of lower than average recruitment until 2010, after which the recruitment pattern has been cyclical. Years with recruitment deviations above the stock-recruit curve include 2010--2012 and 2016--2020. Recruitment prior to the period of deviations, as well as during the forecast period based on the stock-recruit curve resulting from a value of steepness fixed at 0.72 (@fig-bh-curve). Bias adjustment was applied to the annual estimates of recruitment deviations following the pattern of transformed variances as shown in @fig-recdev-var.

### Fits to the Data (TOR section F3)

#### Fits to length and age composition

The aggregated fits to the length composition are reasonable (@fig-lenfit-all) given the overall sparseness of data and variable sample sizes by year (@fig-len-pearson-all). The data weighting down weighted the length composition for both catch fleets and both survey fleets, as well as the conditional age-at-length data for the commercial fleet and the growth fleet (@tbl-compweight).

The mean lengths observed by year from the commercial fleet were uncertain but the time-varying selectivity captures the changes in mean length relatively well (i.e. fits extend through confidence intervals) for all but the year 2007 (@fig-meanlen-comm). The period of positive residuals during 2009--2017 shows that the model does not capture to the same extent the increase in size observed in the commercial length data. Commercial length samples during this time were sparse and are primarily from the two most northern ports. Sensitivities however showed the perceived lack of fit is not as pronounced when years with sparse samples sizes (< 10) were excluded (see @sec-assmt-sens). There were limited ages available for the commercial fleet from a limited number of years. There are a few remaining large Pearson residuals in individual years, but the mean age from the conditional data were generally well captured by the model (@fig-age-pearson-comm and @fig-meanage-comm).

The model fit the tails of the aggregated recreational length composition well, but expected a peak length larger than the data suggested (@fig-lenfit-all). The Pearson residuals were variable by year and showed no patterns of general misfit to the length data. Positive residuals at the edges of the distribution in years before 2004, which are some of the largest residuals, are indicative of widely spread distributions with lower sample size. Recreational length data was fit well for years in which sample sizes were large, covering the range of sizes covered by confidence internals in all years except 1983 (@fig-meanlen-rec). Variability in mean length was smaller after 2004, and more uncertain prior to 1993, generally reflecting the availability of samples. There were no regulations nor major changes in the recreational fishery prior to 1999 that would suggest the need for an additional time block to aid in fitting these data. There were no ages available from the recreational fleet collected as part of the CDFW \gls{crfs} sampling program. 

The fits to length data for the \gls{rov} and \gls{s-ccfrp} surveys were variable and patterns harder to distinguish given the limited length of the time series (@fig-len-pearson-all). The CCFRP mean length was uncertain across years with fits generally reasonable except that the increased mean length in 2019 was not captured (@fig-meanlen-ccfrp). The ROV lengths represent different areas in each of the years sampled. The ROV survey lengths were fit to the individual years of data and indicate an increase in mean size form 2019 to 2021 that was not captured by the model (@fig-meanlen-rov). The difference in mean size for CCFRP in 2017, 2018 and 2024 and slight differences in the residual pattern are likely due to sampling at the Farallon Islands where higher densities of `r spp` are observed than at other sites.

Fits to conditional age-at-length data for the growth fleet are harder to evaluate, but are generally acceptable (@fig-age-pearson-grow). There are large Pearson residuals for the growth fleet conditional ages that may be due to age reading errors or the sampling of data from the varied sources that contributed to the growth fleet. Fits to the mean age over time (@fig-meanage-growth) showed no concerning patterns nor did plots of fit to mean age along with uncertainty (see `r4ss` output material).

#### Fits to Indices of Abundance

The base model fit the overall trend in the recreational index reasonably well, capturing the confidence range of mean length in nearly all years with the exception of 2004 (@fig-log-crfs-fit). The first year of the recreational index was not fit, which may be due to it being the first year of the survey, and therefore not being as representative to the population compared to other years. The change in time varying selectivity in 2017 is evident in the fit to the survey data. Given that fits to the index showed limited residual patterns (see `r4ss` output material) and fits were within confidence intervals no extra standard deviation was included for the recreational index. 

The relative indices from the \gls{s-ccfrp} and the \gls{rov} surveys both indicated increases in the later years which the base model underestimated (@fig-log-ccfrp-fit and @fig-log-rov-fit). The decreased value in 2019 for \gls{s-ccfrp} was not captured by the model and may be a result of factors not considered in index development, i.e., higher than average catches of a midwater species. As was the case for the recreational index, both the \gls{s-ccfrp} and the \gls{rov} indices were fit well without the need to add extra standard deviation.  

### Population Trajectory (TOR section G3) 

The predicted spawning output (in millions of eggs) is given in @tbl-timeseries and plotted in @fig-ssb. The estimates of spawning output across time are uncertain with the base model estimating a spawning output of `r round(mod_out$derived_quants[mod_out$derived_quants$Label == 'SSB_2025','Value'], 2)` in 2025 with a 95 percent asymptotic confidence interval ranging from `r paste(round(mod_out$derived_quants[mod_out$derived_quants$Label == 'SSB_2025','Value'] - qnorm(1- (1-0.95) / 2) * mod_out$derived_quants[mod_out$derived_quants$Label == 'SSB_2025','StdDev'], 2), "-", round(mod_out$derived_quants[mod_out$derived_quants$Label == 'SSB_2025','Value'] + qnorm(1- (1-0.95) / 2) * mod_out$derived_quants[mod_out$derived_quants$Label == 'SSB_2025','StdDev'], 2))` millions of eggs. The population declined slowly with the onset of fishing, with three periods of large decline in years of high total removals. The population remained at lower levels during 1994--1999 before increasing during 2000--2007. Total removals increased again in 2015 and resulted in a slight decline in spawning output through 2023. The population has since increased, likely due to low removals and increased recruitment in 2016 and 2017. The estimate of total biomass over time is shown in @fig-tot-bio.

The estimated spawning output relative to unfished spawning output reached a minimum of `r round(min(mod_out$derived_quants[grep("Bratio", mod_out$derived_quants$Label), "Value"]), 3)` in 1998 and then increased over the recent time period, with an ending year estimate of   `r round(mod_out$derived_quants[mod_out$derived_quants$Label == 'Bratio_2025','Value'], 3)` in 2025 [@fig-depl]. Approximate 95% confidence interval based on the asymptotic variance estimates show that the uncertainty in the estimated spawning output in 2025 ranges between approximately `r round(mod_out$derived_quants[mod_out$derived_quants$Label == 'Bratio_2025','Value'] - qnorm(1- (1-0.95) /2) * mod_out$derived_quants[mod_out$derived_quants$Label == 'Bratio_2025','StdDev'], 2) * 100` - `r round(mod_out$derived_quants[mod_out$derived_quants$Label == 'Bratio_2025','Value'] + qnorm(1- (1-0.95) /2) * mod_out$derived_quants[mod_out$derived_quants$Label == 'Bratio_2025','StdDev'],2) * 100` percent of unfished spawning output.

