## Model Diagnostics <!--(TOR Section F2, F4, H4)-->

### Convergence <!--(TOR Section F4)-->

The maximum parameter gradient was `r signif(mod_out$maximum_gradient_component, 2)`. Proper convergence was determined by starting the minimization process from dispersed values of the maximum likelihood estimates to determine if the model found a better minimum. Starting parameters were jittered using the jitter functionality built into Stock Synthesis, using a jitter fraction of 0.5. This was repeated 100 times with 98 out of 100 runs returning to the base model likelihood. A better, lower negative log-likelihood, model fit was not found. Through the jittering and likelihood profiles, we are confident that the base model, as presented, represents the best fit to the data given the assumptions made. There were no difficulties in inverting the Hessian to obtain estimates of variability throughout initial model attempts and all explorations resulted in a positive-definite Hessian. 


### Retrospective Analysis <!--(TOR Section H4)-->

A fifteen-year retrospective analysis was conducted by successively removing years of data ranging from 2008--2023 (e.g., “Data -1 Years” corresponds to data through 2023). The estimated spawning output for all retrospectives was lower at the start of the time series and lower in the final model years except for Data -1 and Data -2 years (@fig-retro-ssb). The estimates of spawning output relative to unfished were within the asymptotic uncertainty of the base model through the first five peels, removing data through 2018 (@fig-retro-depl). A substantial amount of data were collected over the past five years for `r spp`. Removing more than 5 years of data results in a stock that is estimated within the management precautionary zone in the end year of a peeled model run. Removing 13 to 15 years of data results in changes in the recruitment patterns more dramatically than removing fewer years. When 15 years of data are removed the high recruitment pulse in 1994 is no longer estimated and recruitment is on average higher than other model runs across the entire time series (@fig-retro-panel). Estimates of Mohn's $\rho$, which measures the magnitude of retrospective bias, are provided as per-year averages [@hurtado-ferro_looking_2015]. According to @hurtado-ferro_looking_2015, Mohn's $\rho$ values on a per-year basis of less than -0.15 are not cause for concern, but should not be taken as lack of true bias. 


### Likelihood Profiles <!--(TOR Section F2)--> {#sec-profiles}

Likelihood profiles were conducted for ln($R_0$), steepness ($h$) and natural mortality values ($M$) separately, as well as bivariate profiles for steepness and natural mortality, and for growth parameters $L_{\infty}$ and $K$ separately. The priors for all parameters, including the parameter being profiled, were included in every likelihood model. For example, including the prior on natural mortality across the profiled values of natural mortality provides information on the likelihood contribution of that prior as if it were estimated in the model.  

The negative log-likelihood was minimized at a value for ln($R_0$) of `r round(mod_out$parameters["SR_LN(R0)", "Value"], 3)` and was supported most strongly by the recruitment and length data (Figures [-@fig-r0-profile]--[-@fig-r0-piner]). The age composition data supported lower values of ln($R_0$) relative to the base model, at the minimum value profiled, 3.4. The length composition for the recreational fishery supported a ln($R_0$) around 3.6 and the survey data supported higher values around 4.0. The final year estimated fraction unfished ranged from 0.39 to 0.69 for the range of values of ln($R_0$) from 3.4 to 4.3.

Across the negative log-likelihood profile for values of steepness all data types except for the age-composition supported a higher value of steepness at 0.9, which was higher than the base model that fixed steepness at 0.72 (Figures [-@fig-h-profile]--[-@fig-h-piner]). The final year estimated fraction unfished was as low as 0.36 with steepness fixed at 0.5 and above the management target of 0.40 for all values greater than and equal to 0.60. There was little overall change in the trajectory across steepness values, particularly for values above 0.72.

The profile over natural mortality suggested the negative log-likelihood was minimized at around $M$ = 0.08 yr$^{-1}$, suggesting a lower maximum age than assumed in the base model with fixed natural mortality at $M$ = `r round(mod_out$parameters["NatM_uniform_Fem_GP_1","Value"], 3)` yr$^{-1}$ (Figures [-@fig-m-profile]--[-@fig-m-profile_param-panel]). The final year estimated fraction unfished was above the management target for values of natural mortality of 0.065 and higher. None of the data indicate a strong minimum across the values profiled from 0.20 to 1.0 (@fig-m-piner). From values of $M$ of 0.065 to 1.0, the negative log-likelihood changed by less than two points. 

A bivariate profile of 192 models over all combinations of natural mortality from 0.04--0.15 and steepness from 0.25--1.0 indicates that the base model is within two negative log-likelihood points of the model with the minimum negative log-likelihood (@fig-Mh-NLL).  There are a range of models with a combination of values of $M$ and $h$ that are within the range of acceptable models according to the likelihood (@fig-Mh-contour), likely due to data limitations and moderate uncertainty in the base model. 

The profile over $L_{\infty}$ indicates the negative log-likelihood was minimized at the value estimated in the model and was supported by the age and length data, especially ages from the \gls{s-ccfrp} fleet, and lengths from the recreational and \gls{rov} fleets (Figures [-@fig-linf-profile]--[-@fig-linf-piner]). Age and length data supported similar values of $L_{\infty}$ between 41--45 cm. The final year estimated fraction unfished ranged from 0.36 to 0.57 for the range of values of $L_{\infty}$ from 40 to 46 cm. Note that for this profile all other growth parameters were estimated, and thus the effects of changes in $L_{\infty}$ also account for corresponding changes in the other estimated growth parameters.

The profile over $K$ indicates the negative log-likelihood was minimized at the value estimated in the model and was supported by the age data, especially ages from the \gls{s-ccfrp} fleet, and the length data, especially lengths from the recreational and \gls{rov} fleets (Figures [-@fig-k-profile]--[-@fig-k-piner]). Age data supported slightly lower estimates of $K$ from 0.09--0.16, while length data supported slightly higher estimates between 0.10--0.17. The final year estimated fraction unfished ranged from 0.37 to 0.54 for the range of values of $K$ from 0.08 to 0.2. This reflects an opposite pattern to the profile observed during the 2021 stock assessment [@Langseth_status_2021], which did not include age data. Note that for the $K$ profile reported herein, all other growth parameters were estimated, and thus the effects of changes in $K$ also account for corresponding changes in the other estimated growth parameters.
