### Sensitivity Analyses <!--(TOR section H1 - H2)--> {#sec-assmt-sens}

The base model contains substantial uncertainty in both how data were processed, and structural assumptions made. We tested sensitivity to many of these assumptions. Sensitivities were conducted as a single exploration from the base model assumptions and/or data, and were not performed in a cumulative fashion unless specifically noted. In general, structural assumptions regarding population productivity led to the largest changes in model outputs (@fig-sens-overall). Most sensitivities, with the exception of those related to omitting age or length data, or alternative structures like areas-as-fleets or no recruitment deviations, led to relatively similar estimates of growth parameters, indicating growth is consistently estimated in the model (Tables [-@tbl-sens-productivity]--[-@tbl-sens-selectivity]). We divide the sensitivities into four sections: sensitivities to choices affecting population productivity, choices on data weighting and understanding relative contributions of data sources, choices related to how data are prepared, and assumptions around selectivity. We also describe sensitivities done but not included in the document. 

#### Population Productivity

The base model makes a number of structural assumptions related to population productivity. These assumptions are known to be influential and drive how quickly a population will recover from fishing. In addition, new biological information impacts productivity as was discussed during bridging (see @sec-bridging). The following sensitivity models fall under population productivity:

-   Estimate $h$: Estimate steepness of the stock-recruit relationship.

-   Estimate $M$: Estimate natural mortality.

-   Estimate $M$ and $h$: Estimate both natural mortality and steepness of the stock-recruit relationship.

-   Recdevs in 1990: Turn off estimation of recruitment deviations until 1990, which corresponds roughly to when deviations become informative. 

-   No recdevs: Turn off estimation of recruitment deviations for all years, which assumes recruitment follows the stock recruitment curve. 

-   Fix growth at external estimates from 2021 assessment: Fix all growth parameters at the values assumed in the 2021 assessment. This includes $L_{\infty}$ = 43.04 cm and $L_{age=1}$ = 8.23 cm, as well as the variability in length at these ages (set to 0.1), and $K$ = 0.199. This sensitivity is exploratory and is intended to explore implications of assumptions around productivity, in this case growth. 

-   Fix growth at external estimates from 2021 assessment but without age data: This sensitivity is the same as the one prior but excludes the ages from the model likelihood. This sensitivity emulates the conditions of the 2021 assessment where age data was not fit within the model. This sensitivity is also exploratory and is intended to explore implications of assumptions around productivity, in this case growth, and how age data inform population productivity.

Structural assumptions in the model that determine population productivity, particularly natural mortality as well as the information available to determine productivity (i.e. age data), were strongly influential on the population trajectory (@fig-sens-productivity and @tbl-sens-productivity). Natural mortality was estimated to be around 0.08, whether steepness was also estimated or not, and resulted in a greater increase in recovery of the population in the 2000s, which led to a higher value for spawning output relative to unfished in 2025 that was outside the range of uncertainty from the base model. The improvement in total likelihood when estimating natural mortality or steepness was approximately one likelihood unit, with the greatest increase being 1.6 likelihood units when both parameters were estimated. Not estimating recruitment deviations resulted in increased spawning output for all years, but relatively more in recent years than in past years, resulting in higher spawning output relative to unfished in 2025 that was near to the range of uncertainty from the base model. Not estimating recruitment deviation led to degradation in fits to both length and age composition data, as well as in fits to indices, based on likelihood components. Starting recruitment deviations in 1990 led to modest degradation in model fit of around six likelihood units and resulted in little change in population trajectory. While the number of parameters saved would indicate this is a reasonable choice based on an information theoretic approach (i.e. \gls{aic}), we kept the start time for main recruitment deviations to be 1978. We did this to allow the early and initial main recruitment deviations to inform the size structure of the population, which, given length composition data for the recreational fleet in 1980--1990 showing a large decline, along with a significant amount of total removals having occurred by 1990, would not be at equilibrium. Fixing growth at estimates from the 2021 assessment resulted in an greater increase in the recovery of the population in the 2000s similar to that of estimating $M$ or removing recruitment deviations. Model fit however was severely degraded. Interestingly, the magnitude of recovery depends on the information available in the age data. When age data are not included in the model under the same growth parameter values, the recovery of the population is severely reduced and the population never extends above the \gls{msst} after the early 1990s. This pattern is due to the different direction of the $K$ profile for this assessment (see @sec-profiles), which includes age data, compared to the direction of the $K$ profile for the 2021 assessment, which does not include age data [@Langseth_status_2021]. This suggests that productivity comes from more than just model parameter values but also from the information available to the model from data within the constrains of the parameter values.

#### Data Weighting and Contributions

The assessment model contains data from a variety of sources, some of which are expected to be more informative than others. Sampling units from these different data sources are not necessarily comparable (e.g., an observation from a survey index versus an observation of a fish length). Data weighting procedures are objective algorithms that can be used to assign weights to different data sources to optimize the fit of the model to the data. Increased uncertainty or emphasis factors also weight the relative contribution of datasets and can be used to influence contributions of various data types. The following sensitivity models fall under data weighting and contributions:

-   McAllister-Ianelli data weighting: Use the algorithm suggested by @mcallister_bayesian_1997 instead of @francis_data_2011

-   Dirichlet-multinomial data weighting: Apply the algorithm suggested by @thorson_model-based_2017 instead of @francis_data_2011

-   Extra SD: Estimate an extra standard deviation for all survey indices, which include the recreational, \gls{s-ccfrp}, and \gls{rov} indices. This allows each index to be down-weighted to allow for better fitting of other data sources.

-   Remove fleet lengths: Remove contributions from length composition data from the commercial and recreational fleet by setting the emphasis factors for these two elements to zero.

-   Remove conditional age at length: Remove contributions from conditional age at length data from the commercial and growth fleet by setting the emphasis factors for these two elements to zero. 

-   Remove indices: Remove contributions from index data for the recreational, \gls{s-ccfrp}, and \gls{rov} fleets by setting the emphasis factors for these three elements to zero. 

The model was robust to the range of alternative weighting and data contribution sensitivities, with the exception of exclusion of conditional age at length data (@fig-sens-contributions and @tbl-sens-contributions). Excluding age data resulted in a higher estimate for equilibrium spawning output, and lower estimate for recent spawning output, due to reduced magnitude of recruitment deviations and higher $L_{\infty}$ and $K$, leading to lower values for spawning output relative to unfished. While excluding length data for the fleet also resulted in differing estimates of growth parameters, $L_{\infty}$ was estimated to be lower while $K$ higher than base model estimates, offsetting effects on the population trajectory, which was similar to that of the base model. Other sensitivity scenarios showed limited difference from the base model trajectory. While total likelihoods cannot be compared across scenarios, individual components of unchanged data types can be. When excluding age or length data contributions, survey likelihood components are similar to that of the base models. Similarly, when adjusting the contribution of survey data, age and length likelihood components are similar to that of the base model. This indicates that the survey indices provided limited signal compared to other data sources.


#### Data Choices

Compiling data for the assessment model required a number of choices and assumptions. The following sensitivity models fall under data choices:

-   Remove ageing error: assume no ageing imprecision when reading age samples.

-   Reduce large catches: catch estimates for the commercial fleet in 1991 and for the recreational fleet in 1983 and 1993 were particularly large compared to other years. Catch estimates in these years were assumed as averages from nearby years for this scenario. For 1983 and 1991, the average was from the three years before and after; for 1993, the average was from the three years after. Note that adjusting recreational catches in 1993 resulted in changes to values in 1990--1992.

-   Smooth catches: catch estimates for the commercial fleet in 1991 and for the recreational fleet in 1984 and 1993 were particularly large compared to other years. However, some years could also be abnormally low compared to other years, but not as noticeably different. For this model a five year moving average (two years on either side) was applied to smooth total removals for all but the first and last two years. 

-   Areas-as-fleets: structure data for the recreational fleet following an areas-as-fleets approach [@punt_spatial_2019]. A pattern of larger lengths of `r spp` caught in the recreational and commercial fleets, and \gls{rov} survey north of Point Arena $38^\circ 55^\prime$ N. latitude was discussed at the pre-assessment workshop, suggesting possible differences between regions. In this scenario data from northern districts (Redwood and Wine) were treated as a separate fleet from data from southern districts (all others). This also applied to length composition data. New CRFS dockside private/rental indices pertaining to the two recreational fleet areas were applied to their respective regions. The CCFRP and ROV surveys were not split because as indices these are tracking populations trends, and areas-as-fleets still assumes one population. Only the recreational fleet was split (compared to the commercial fleet) because data was present in both areas across the time series, whereas for the commercial fleet length composition data in the south was sparse and present only in a few years outside of the 1990s while age composition data was only sampled in the north. Due to the difference in data structure for this sensitivity, reweighting was applied.

Choices around inclusion or exclusion of individual data or treatment of how to process and include total removals in the model had generally limited effect on population trajectory and quantities (@fig-sens-data and @tbl-sens-data). Estimates of spawning output in recent years are consistent across scenarios, but estimates of unfished spawning output vary, although they remain within the uncertainty bounds of the base model. When large catch values were reduced, unfished spawning output declined, as expected. However, given that estimates of spawning output in recent years were more similar to the base model, lower estimates of unfished spawning output led to higher values for spawning output relative to unfished in 2025. When catch values were smoothed, such that the overall removals across years were not altered, population trajectory was nearly identical to the base model. The areas-as-fleets scenario resulted in generally similar trajectory to the base model, but with estimates for $L_{\infty}$ higher and estimates for $K$ lower than the base model. The selectivity structure of the areas-as-fleets scenario was different from the base model, and used a greater number of blocks that included the ability to estimate dome-shaped selectivity. The southern recreational fleet was estimated with dome-shaped selectivity whereas the northern fleet was estimated as asymptotic. More numerous and flexible blocks were used because early explorations for areas-as-fleets showed poor fits when using the base model blocks, although model results were similar. The updated blocks were not further refined however, as would be expected for candidate base models, because there was limited difference in population trajectory from the model without areas-as-fleets. When reweighting the areas-as-fleets model, some of the selectivity estimates indicated greatly altered patterns, indicating some model instability. Given this instability, the similar population trajectory to that from the model without areas-as-fleets, and that the spatial coverage of the commercial data was not ideal for a areas-as-fleets approach, we did not think continued exploration of areas-as-fleets worthwhile. 

#### Selectivity 

There are many possible ways to parameterize selectivity in a stock assessment model, and its parameterization is generally a major source of structural uncertainty. Parameterization can relate to the number and years of selectivity blocks, where changes in length or age composition data is reflective of changes to the fishery as opposed to changes in the population, or the type of selectivity form, often either asymptotic or dome-shaped. The following sensitivity models fall under selectivity, with the first two dealing with both the number and year of blocks as well as the type of selectivity, and the remaining dealing with the type of selectivity: 

-   Full blocking of the recreational and commercial fleets, allowing for dome shaped selectivity. This scenario assumes the greatest number of blocks, and therefore parameters, among all the selectivity scenarios and was based on discussions with \gls{cdfw} staff and advisory panel members from the \gls{gmt} and \gls{gap}. Blocks for the commercial fleet were assumed for 1916--2002, 2003--2013, 2014--2021, and 2022--2024. Blocks for the recreational fleet were assumed for 1916--2000, 2001--2016, 2017--2022, and 2023--2024. The rational for these blocks were described previously (see @sec-structure)

-   Full blocking of the recreational fleet, allowing for dome shaped selectivity in all blocks except the first, which was assumed asymptotic. The first block was fixed as asymptotic because the estimated descending parameter (parameter 4) in the previous scenario was approximately asymptotic. Blocks for the commercial fleet matched the base model.

-   Selectivity allowed to be domed for all fleets, both catch and survey fleets, using the blocking structure from the base model. 

-   Selectivity allowed to be domed for all the commercial fleet using the blocking structure from the base model.

-   Selectivity allowed to be domed for all the recreational fleet using the blocking structure from the base model.

-   Selectivity allowed to be domed for survey fleets.

-   Selectivity assumed to be asymptotic for all fleets, both catch and survey fleets, using the blocking structure from the base model. 

-   Selectivity assumed to be asymptotic for all fleets and without any blocks for the catch fleets. 

Parameterization of selectivity, including the number and years of blocks, as well as the type of selectivity generally had limited effect on model trajectory (@fig-sens-selectivity and @tbl-sens-selectivity). Simpler blocking designs were preferred over more complicated blocking designs based on information theory, and dome-shaped selectivity did not meaningfully improve model fit compared to asymptotic selectivity for nearly all blocks and fleets across scenarios (@tbl-sens-selectivity). Nearly all scenarios were within the range of model uncertainty from the base model, with the exception of two scenarios. These two scenarios either allowed all selectivity types to be dome-shaped or applied a single selectivity block for each of the recreational and commercial fleets that was asymptotic. For the dome-shaped scenario, although all fleets and blocks were allowed to be dome-shaped, further explorations showed that the combination of allowing dome-shape for the \gls{s-ccfrp} and recreational fleet contributed most to changes in spawning output relative to unfished. Model fit improved slightly when all fleets were allowed to be domed (slightly more than two likelihood units for six additional parameters), with the largest changes occurring when commercial and survey selectivity was allowed to be domed (individually these improved model fit by less than one likelihood unit). For the scenario without selectivity blocks, unfished spawning output was lower than the base model, though spawning output relative to unfished was generally comparable to the base model.


#### Sensitivities Not Included in this Document

Many more explorations around data use and modeling choices were conducted but are not included in this report. Among data scenarios, using marginal age composition data for the commercial fleet instead of conditional age at length data, including length and conditional age at length compositions in years with sparse sample size (<5 for lengths and <30 for ages), excluding the most recent year of recreational length composition data given the difference in the operation of the fleet, excluding sample sizes less than 10 for commercial length composition data, and increasing uncertainty in catch estimates all had minimal impacts on model outputs and are not included. Similarly, among selectivity scenarios, alternative years for blocking the commercial fleet using 2018 instead of 2014 (due to fully realizing increased access to deeper depths for southern port groups made throughout 2017, transferable deeper nearshore permits for 2018, and noticeable changes in mean sizes between 2017 and 2018) had minimal impacts on model outputs and are not included. Sensitivities around estimates of alternative values for longevity, or use of biological relationships from the 2021 assessment were also explored, but given these are shown elsewhere in the report via profiles or bridging, they are not duplicated in this section. 


### Historical Analysis <!--(TOR Section H5)-->
<!-- Time-series of total biomass, summary biomass, and spawning biomass (and/or spawning output), depletion relative to B0, recruitment and fishing mortality (1-SPR) (or exploitation rate estimates if fishing mortality not available) (table and figures).  -->

The estimated summary age 3+ biomass and estimated spawning output of the population and relative fraction unfished compared to the 2021 assessment are shown in [@fig-historical]. The estimated spawning output from the 2021 assessment for California `r spp` compared to the base model throughout the bridging process is shown in Figures [-@fig-bridgeSS3_bio]--[-@fig-bridgeOther_comp]. The estimated spawning output of the population and relative fraction of spawning output both increased in the 2025 base model compared to the 2021 assessment. Estimated age 3+ biomass also increased relative to the 2021 assessment to a level just above the 95% confidence interval of the 2021 model. The compilation of updated life history parameters and data drove the changes in population dynamics. 
