## Unresolved Problems and Major Uncertainties <!--(TOR section J)-->

<!-- Describe any special issues (e.g., unbalanced or questionable data, missing survey data) that complicate scientific assessment, questions about the best model scenario. -->

The primary area of uncertainty for this assessment is the parameters influencing population productivity and ultimately scale in recent years. Bridging from the 2021 assessment (see @sec-bridging) provides a detailed progression of changes in spawning output and spawning output relative to unfished between the 2021 and present assessments. Updating biological parameters and data had a large effect on results and had a much greater impact than other changes such as selectivity. Updating the growth curve and natural mortality contributed to the large change in the degree of recovery in spawning output relative to unfished. The updates to growth were derived from recent research that was unavailable at the time of the 2021 assessment. This new research provides a considerable improvement in our understanding of `r spp`. This highlights the importance of basic life history research and that continued work to refine these estimates and monitor for potential change over time is critical. Despite these improvements to data collection, data are still relatively sparse, and we also still face uncertainty in population scale as it relates to estimates of natural mortality, as is shown by model profiles across this parameter both individually and in combination with steepness. Understanding the reasons for differences in scale observed between this assessment and analysis of \gls{rov} survey data (see @sec-appendix-B) may also help inform questions about scale but more work is needed to understand the extrapolation to a population-wide based estimate.   

Catches of `r spp` were particularly high in a few years for both the recreational and commercial fleets. Although not affecting estimates of depletion, averaging out these high years of catches affected model scale and therefore estimates of sustainable yield. Averaging out all years however showed little change in model results indicating the overall scale of removals matters more so than increases and decreases around a common mean over time. Changes to catches affecting model scale is true of all models that assume catch is well known, however for `r spp` in `r state` the magnitude of the reduction in catch for these years was approximately 20% of the total removals. Resolution on these high catches, should they be needed, would aid in increasing accuracy of catch time series and resulting estimates of sustainable yields.

Lastly, patterns in observed length data showed larger fish in northern areas of California than in southern areas. No single reason for this is known and is likely be due to many reasons including differences in fishing activities, sampling efforts, population growth, or some other underlying biological or environmental process. We explored this effect as it relates to differences in sizes of fish observed in the fishery, and found limited effect on population trajectory, but did not explore potential effects due to differences in population characteristics. While there is no clear evidence to indicate differences in `r spp` populations in these regions, further understanding of the reasons for these observed differences may suggest future directions for exploration. Regardless of the reason, increased sampling in these areas and across California as a whole would aid in better understanding `r spp` rockfish dynamics. 