# Management 

## Reference Points <!--(TOR section I1-I5)-->

Reference points were calculated using the estimated selectivities and catch distribution among fleets from the final year of the model, `r mod_out$endyr`. Derived quantities along with reference points at the three management targets for the population at 40% of unfished spawning output, at spawners-per-recruit (SPR) of 50%, and at the internal model estimated \gls{msy} are shown in @tbl-ref-points-es. The equilibrium yield curve in shown in @fig-yield.   

The 2025 `r spp` spawning output relative to unfished spawning output is above the target at `r round(100*mod_out$current_depletion, 1)`% though the 95% confidence interval based on the asymptotic variance estimate ranges into the management precautionary zone (@fig-depl). The fishing intensity (1 − SPR) first reached the target around 1980 and has varied since. Fishing mortality most recently exceeded the target of 0.5 during 2017--2021 but has recently decreased to below 0.5 (@fig-spr).

## Harvest Projections and Decision Tables <!--(TOR section K1-K3)-->

The 2025 stock assessment for `r spp` off California was supported as a category 1 determination by the \gls{star} panel review. A ten-year projection of the base model with total removals equal to the estimated \gls{acl} based on the category 1 time-varying $\sigma$ (0.5) and $P^*$ = 0.45 (i.e., termed the "buffer") for years 2027--2036 is shown in @tbl-projections. Average recruitment was assumed during the projection period and selectivity of each fleet was assumed to equal the estimated selectivity in the final year of the model. Total removals were apportioned to each fleet based on the relative fishing morality among fleets in the last four years of the model (i.e. 2021--2024). The removals in 2025 and 2026 were set equal to the recommended fleet-specific values as provided by the \gls{gmt} (T. Banez, \gls{cdfw}, pers. comm., 5/14/2025). Catches from 2027 onward assume full attainment of the \gls{abc}, assuming the \gls{acl} is equal to the \gls{abc}. 

The axis of uncertainty in the decision table is based on the uncertainty around natural mortality (@tbl-decision). Alternative values for natural mortality (M) were used to identify the low ($M$ = 0.0525) and high ($M$ = 0.08) states of nature, where the base model is assigned a 50% probability of being the true state of nature and both the low and high states of nature are assigned a 25% probability. The choices for the low and high values for natural mortality were made during the \gls{star} panel review and were based on values that approximated the 12.5 and 87.5 percentiles of the estimated OFL in 2025 from the base model. The proposed decision table assumes full ACL removal during the projection period under alternative catch streams based on a $P^*$ = 0.45.


## Evaluation of Scientific Uncertainty <!--(TOR section L)-->

The model estimated uncertainty around the `r mod_out$endyr+1` spawning output for `r spp` is $\sigma$ = `r round(mod_out$Pstar_sigma,2)` and the uncertainty around the OFL in `r mod_out$endyr+1` is $\sigma$ = `r round(mod_out$OFL_sigma, 2)`. Both of these underestimate overall uncertainty due to the necessity to fix several population dynamics parameters (e.g., steepness, recruitment deviation variance, natural mortality) and because there is no explicit incorporation of model structural uncertainty (although see the decision table for alternative states of nature). Estimated uncertainty values are less than the default \gls{ssc} value of 0.5 for a category 1 assessment (although this determination has not yet been made for this assessment), so harvest projections assume an initial $\sigma$ of 0.5, with an increase over time at a rate of 0.075 times the baseline sigma (0.0375 per year).

Based on the considerations, explorations, and diagnostics described previously, we conclude that different treatments and assumptions regarding data preparation, data weightings, and decisions around selectivity blocks and type have limited relative impact on estimates of population scale and status for `r spp`, particularly in recent years, compared to choices around stock productivity. Estimates of stock status are sensitive to assumptions regarding the biological parameters that govern productivity and the yield curve, especially the natural mortality rate and the choice to estimate growth in the model. We therefore recommend that biological data, particularly ages, be continued to be collected, ideally as part of established fishery sampling programs, and future research prioritize better understanding of natural mortality for `r spp` across the eastern Pacific Ocean.


### Risk Table

A risk table for California `r spp` is provided in @tbl-es-risk. Risk tables are divided into ecosystem and environmental conditions, assessment data inputs, and assessment model fits and structural uncertainty. These tables are intended to provide information across these factors in a transparent manner, based on the framework outlined by the \gls{cciea} team [@Golden2024], so as to inform values for scientific uncertainty. Information on the influence of environmental conditions on California `r spp` is lacking. As such, no determination on a level to inform uncertainty for the ecosystem and environmental conditions was made. Determinations for other factors are based on the assumption of a category 1 assessment determination.  

Assessment data inputs are described in the data sections of this report, and are visible from model outputs. Some uncertainties exist in values from the historical catch reconstructions and there are some gaps in catch estimates for years or for portions of the fleet since 1980. Age data are an important data input in the base model yet there was limited samples suitable for use in compositions. Instead, the majority of age samples would best be incorporated as a growth fleet, even though only a subset were ultimately included in the base model. While length compositions covered a broader range of years, there was some patchiness in regions where samples were available. Indices were available for some fishery-independent surveys, but the duration over which these covered was short. These inputs suggest an unfavorable categorization. In contrast to uncertainty in available data for the fleets and survey, which is not uncommon for nearshore rockfish species, biological samples were collected in California in recent years and used to derive estimates of fecundity and maturity. These inputs suggest a favorable categorization. Overall, we preferentially weight the many uncertainties in catch, ages, and length data higher than the local species specific estimates of fecundity and maturity, and therefore consider uncertainties in assessment data warrant an unfavorable determination. 

Assessment model fits and structural uncertainties are described in the assessment model section of this report. Overall, elements within this factor suggest a range of criteria. Models fits to the data were generally good, including fits to composition and index data. Many parameters that govern productivity including recruitment and growth were estimated internally in the model, and steep profiles and stable jitters suggests these are well-estimated. However, natural mortality and steepness were fixed based on existing priors, and profiles suggest a range of values for these parameters were plausible. There was also uncertainty in the strength of recruitment deviations particularly in the mid 1990s, and insufficient information beyond larger sizes of fish in northern areas by which to determine spatiotemporal variation in biology. Lastly, there was evidence of a strong retrospective bias in the model that aligns with the removal of age data that influence estimates of recruitment. Collectively, these factors suggest a range of categorizations from favorable to unfavorable. As such, we consider uncertainties in assessment models fits and structural uncertainties warrant a neutral determination.  


## Regional management considerations <!--(TOR section M)-->

Regional management differences exist across the U.S. West Coast based on various state-specific management measures. Spatial closures, bag limits, and depth restrictions can influence the effect of fishing on populations of a species that can vary by region. Spatial closures are expected to increase the spatial heterogeneity in abundance and size or age structure of fished stocks. This greater spatial variability can complicate the assumptions made in stock assessment models, particularly the assumption that the densities and demographic structure of assessed populations are relatively homogeneous. Although a wide range of factors above and beyond spatial management measures can also lead to violations of those assumptions, the challenge can be particularly important for longer lived populations with lower movement rates, such as `r spp`. While spatially explicit assessment models provide a means of more explicitly addressing these challenges, such models are computationally intensive, require robust data from the specific areas being modeled, and may also require detailed information regarding movement and dispersal rates [@mcgilliard_accounting_2015; @berger_space_2017; @cadrin_defining_2020].

For this assessment, we used a single area statewide model and did not split fleets by management areas in the base model nor explicitly model separate areas by latitude or for areas open versus closed to fishing. Nonetheless, information on closed areas, including both \gls{mpa}s and closures due to management changes, were incorporated within the base model. Data from \gls{mpa}s were included within the abundance index and length composition for \gls{s-ccfrp} and the \gls{rov}. Selectivity blocks were applied within the base model to explain changes in length compositions due to management action restricting certain areas from fishing. Collectively, this is the information available for `r spp` to incorporate area closures. Modeling spatial closures more explicitly would require more detailed information from the fishery on where catches and biological samples occur in relation to areas closed in earlier time periods or in relation to areas that will be closed in later time periods, and this information is not available.

We explored the use of an area-as-fleets approach to account for observed differences in the sizes of fish caught in northern areas. Such regional differences can induce spatial structure, and an areas-as-fleets approach can perform well in modeling it when the underlying population is uniform, but can be biased when it is not [@bosley_mismatch_2022]. The assumed areas corresponded to the northern most port groups and districts compared to more southerly locations. This split did not directly align with the 40$^\circ$ 10' N. latitude management line utilized for the nearshore rockfish complex in the past but occurred farther south, near Point Arena (38$^\circ$ 55' N. latitude). Ultimately, we did not use the areas-as-fleets approach for the base model because the data for the commercial fleet had limited spatial and temporal coverage across both regions in all years, early explorations of the areas-as-fleets sensitivity indicated concerns around model stability, and the results between the current base model and the areas-as-fleets sensitivity were generally similar (see @sec-assmt-sens). Consequently, while the sizes of fish caught differed in regions, modeling this difference did not greatly alter conclusions about the population. This approach assumes a single stock with common life history characteristics. A more complicated structural assumption of explicitly modeling separate spatial areas was not explored due to a lack of other evidence indicating different populations, and that the increased complexity in doing so would either result in sparse data (if assuming separate models) or require additional assumptions around recruitment allocation and movement among populations (if assuming spatial models).   

Federal management of the nearshore rockfish complex, which historically included `r spp`, is based on areas north and south of 40$^\circ$ 10' N. latitude. Since the `r spp` stock was defined for California south of 42$^\circ$ N. latitude [@amendment31_2023], and declared overfished in 2023, California `r spp` have been managed as their own species. Therefore, yield estimates from the base model are appropriate to the scale of management for `r spp` in California. 