## Research and Data Needs (TOR section N)

<!-- 1. Describe progress on Research and Data Needs items identified in the most recent previous stock assessment document and associated STAR panel report.  -->
<!-- 2. Describe new research and data needs and specify their priority (high, medium, low).  -->

Progress on research and data collection recommendations from the last assessment are provided in @sec-star-recs. To improve our understanding of the `r spp` stock in California waters, research and data collection recommendations for this assessment are listed below in general categories. The categories are offered in order of priority while also considering feasibility, as are the elements within each category.

Data sampling needs:

* There are limited age data for `r spp` across California arising from fishery-dependent sources. Establishing regular collections of otoliths from the recreational fishery, a large source of mortality, would support future assessments and would improve the understanding of the population structure and life history of `r spp`. Several fishery-independent programs have made efforts to collect otoliths but sample sizes are sparse and spatial distributions patchy when considered individually. Expansion of these programs or mimicking of their sampling designs would better allow use of age data in association with a fishing or survey fleet as opposed to a growth fleet. Priority: High

* The assessment area has a mixture of observations from areas experiencing variable fishing mortality. In the region there are likely a mixture of areas: open access rocky reefs that are close to port that are heavily fished, open access rocky reefs that are inaccessible via day-trips that are fished but at lower levels, and rocky reefs that fall within marine protected areas (MPAs) or below depth restrictions. A spatially-explicit assessment model may be able to capture this complexity but will require data from each region, including indices of abundance, composition data, and information on rates of movement between them. Priority: Medium for increased data sampling.  

* Future deeper nearshore assessments would benefit from fishery-independent surveys which can increase information available to estimate population trends for these species. A key element for these types of data are the length of time over which they are available.   Efforts have been made by \gls{cdfw} and \gls{swfsc} staff to estimate absolute abundance for the entire `r spp` stock as well as the portion within \gls{mpa}s using \gls{rov} data (see @sec-appendix-B), but more research is needed to understand methods to extrapolate from the sampling domain to the population scale. Priority: Medium for increased fishery-independent surveys.


Research to better understand population scale:

* Potential maximum longevity of `r spp` in California waters is uncertain. The oldest fish observed in California are younger than those along the rest of the U.S. West Coast. This may be due to low sample size in combination with exploitation. Increased age sampling, as well as comparison with proxy species, across their ranges, may help to resolve some of this uncertainty. Priority: High

<!-- * `r Spp` may exhibit latitudinal variation in fecundity.  Fecundity can be an important determinant of population scale.  -->

* The catch history for `r spp` shows extreme high catches in some years.  Continued improvement of historical catch reconstructions as well as the effects of quantifying uncertainty on model results is needed. Priority: Medium

* High resolution interpreted substrate maps for areas outside state waters are needed.  This would allow for estimation of rocky substrate by fishing district and inside and outside closed areas and use of this information for construction of abundance indices. Priority: Low


Research to better understand population processes:

* Recruitment deviations were variable over time, and in the early years uncertain. Information on the environmental influences on `r spp` recruitment would help to validate recruitment deviation estimates. Priority: Medium

* Survey data indicate that large `r spp` are distributed across shallow and deeper habitat, while smaller individuals are mainly in the shallow portion of the `r spp` range.  Further research into the distribution of `r spp` by size and the relationship of size to depth, other habitat features, and distance from port may help to better understand assumptions around selectivity shape. Priority: Low

<!-- NOTE: This is covered in the general spatial recommendation -->
<!-- * It was not possible to fully implement an areas-as-fleets approach for this assessment due to a lack of commercial size data south of Point Arena.  Increased size and age sampling is needed if future assessments are to explore this approach.  -->

* More detailed information on recreational effort and fishing targets is needed, particularly for the private/rental mode. Explorations of time varying selectivity showed in some cases when depth limits relaxed (moved deeper) catch of `r spp` went down and the selectivity pattern became dome shaped. This is contrary to depth-based expectations for `r spp` and may reflect shifts in fishing targets. Information of fishing targets would better inform whether this is the case. Priority: Low



