# Tables {#sec-tables}


```{r} 
#| label: 'set-rda-dir-tbls'
#| echo: false 
#| warning: false 
#| eval: true 
#| include: false
#library(flextable)
#rda_dir <- here::here("documents", "rda_files")
library(tidyr)
library(gt)
library(here)
library(knitr)
library(kableExtra)
``` 


## Data

```{r}
#| label: tbl-catches
#| echo: false
#| warning: false
#| tbl-cap: "Total removals (mt) of quillback rockfish in California for the commercial and recreational fleets as used in the assessment model. See text for description of sources."

catches <- read.csv(here::here("data", "CAquillback_total_removals.csv"), check.names = FALSE) |>
  dplyr::select(c(Year, com_tot, rec_tot)) 
catches[is.na(catches)] <- 0


kableExtra::kable(
  catches,
  format = "latex", 
  col.names = c("Year", "Commercial", "Recreational"), 
  longtable = TRUE,
  booktabs = TRUE,
  linesep = "",
  padding = 0) |>
  kableExtra::kable_styling(
    latex_options = "repeat_header",
    font_size = 11,
    full_width = FALSE)


```

{{< pagebreak >}}


```{r}
#| label: tbl-comm_lengths
#| echo: false
#| warning: false
#| tbl-cap: "Summary of the number of commercial length samples and number of trips available for use in the assessment model. Also included is the input sample size used in the assessment model following the formula described in the text. Lengths in years that had an input sample size of less than 5 were excluded from final model fits, as described in the text."

commlengths <- read.csv(here::here('data', "SampleSize_length.csv"), check.names = FALSE) |>
  dplyr::select(c(Year, pacfin_Nfish, pacfin_Ntrip)) |>
  dplyr::mutate(pacfin_Ninput = 
                  ifelse(pacfin_Nfish/pacfin_Ntrip < 44, 
                         pacfin_Ntrip + 0.138 * pacfin_Nfish,
                         7.06 * pacfin_Ntrip)) |>
  dplyr::filter(!is.na(pacfin_Ninput))
commlengths|>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
cols_label(
    Year = "Year",
    pacfin_Nfish = "N Lengths",
    pacfin_Ntrip = "N Trips",
    pacfin_Ninput = "N Input"
  ) |>
  as_latex()
```

{{< pagebreak >}}

```{r}
#| label: tbl-comm_ages
#| echo: false
#| warning: false
#| tbl-cap: "Summary of the number of commercial age samples and number of trips available for use in the assessment model as conditionals. The number of ages was used as the input sample size in the assessment model. Ages in years that had fewer than 30 samples were excluded from final model fits, as described in the text."

commages <- read.csv(here::here('data', "SampleSize_age.csv"), check.names = FALSE) |>
  dplyr::select(c(Year, pacfin_Nfish, pacfin_Ntrip)) |>
  dplyr::filter(!is.na(pacfin_Nfish))
commages|>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
 cols_label(
    Year = "Year",
    pacfin_Nfish = "N Ages",
    pacfin_Ntrip = "N Trips"
  ) |>
  as_latex()
```

{{< pagebreak >}}


```{r}
#| label: tbl-rec_lengths
#| echo: false
#| warning: false
#| tbl-cap: "Summary of the number of recreational length samples and number of trips available for use in the assessment model. The number of trips was used as the input sample size in the assessment model. Duplicate private/charter mode lengths from the MRFSS sampling program in 1997-1998 are not included. Lengths in years with the number of trips fewer than 5 were excluded from final model fits, as described in the text."

reclengths <- read.csv(here::here('data', "SampleSize_length.csv"), check.names = FALSE) 
reclengths <- reclengths |> 
  dplyr::mutate(tot_Nfish = rowSums(reclengths[,c("recfin_Nfish", "mrfss_Nfish", "deb_Nfish", "GeiCol_Nfish", "MilGei_Nfish", "MilGot_Nfish")], na.rm = TRUE)) |>
  dplyr::mutate(tot_Ntrip = rowSums(reclengths[,c("recfin_Ntrip", "mrfss_Ntrip", "deb_Ntrip", "GeiCol_Ntrip", "MilGei_Ntrip", "MilGot_Ntrip")], na.rm = TRUE)) |> 
  dplyr::select(c(Year, tot_Nfish, tot_Ntrip)) |>
  dplyr::filter(tot_Nfish!=0)
reclengths |>
  gt() |>
  tab_options(
    table.font.size = 11,
    latex.use_longtable = TRUE
  ) |>
cols_label(
    Year = "Year",
    tot_Nfish = "N Lengths",
    tot_Ntrip = "N Trips"
  ) |>
  as_latex()
```

{{< pagebreak >}}

```{r}
#| label: tbl-survey_lengths
#| echo: false
#| warning: false
#| tbl-cap: "Summary of the number of fishery-independent length samples, along with the number of drifts or transects or tows, available for use in the assessment model. See text for description of data sources. The number of drifts or transects was used as the input sample size in the assessment model. Data from the WCGBTS were too sparse to use as length compositions in the assessment model. Lengths in years with input sample size fewer than 5 for each other source were excluded from final model fits, as described in the text. "

ccfrplengths <- read.csv(here::here('data', "SampleSize_length_CCFRP.csv"), check.names = FALSE)
lengths <- read.csv(here::here('data', "SampleSize_length.csv"), check.names = FALSE) |>
  dplyr::select(Year, trawl_Nfish, trawl_Ntrip)
rovlengths <-  read.csv(here::here('data', "SampleSize_length_ROV.csv"), check.names = FALSE)

temp <- merge(ccfrplengths, rovlengths, by = "Year", all = TRUE)
fi_lengths <- merge(lengths[lengths$Year >= 2007,], temp, by = "Year", all = TRUE) %>%
  dplyr::select(Year, CCFRP_Nfish, CCFRP_Ndrift, rov_Nfish, rov_Ntrip, trawl_Nfish,
                trawl_Ntrip)
fi_lengths |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  cols_label(
    Year = "Year",
    CCFRP_Nfish = "N Lengths CCFRP",
    CCFRP_Ndrift = "N Drifts CCFRP",
    rov_Nfish = "N Lengths ROV",
    rov_Ntrip = "N Transect ROV",
    trawl_Nfish = "N Lengths WCGBTS",
    trawl_Ntrip = "N Haul WCGBTS"
  ) |>
  gt::cols_width(
    tidyselect::everything() ~ px(75)
  ) |>
  gt::sub_missing(
    columns = tidyselect::everything(),
    missing_text = "---"
  ) |>
  as_latex()
```

{{< pagebreak >}}

::: {.landscape}

```{r}
#| label: tbl-caal_ages
#| echo: false
#| warning: false
#| tbl-cap: "Summary of the number of age samples available for use in the assessment model (except commercial, which is shown in @tbl-comm_ages). See text for description of data sources. All data were used to initialize growth parameters. Only ages from Abrams were used in the assessment model as conditional age-at-length for the growth fleet, and ages from CCFRP were used in the assessment model as conditional age-at-length for the CCFRP fleet. For Abrams and CCFRP, the number of ages was used as the input sample size."

growthCAAL <- read.csv(here::here('data', "SampleSize_ageGrowth.csv"), check.names = FALSE) |>
  dplyr::mutate(misc = calcom_Nfish + comm85_Nfish,
                CCFRP = CCFRPFarallons_Nfish + CCFRPNotFarallons_Nfish) |>
                dplyr::select(-c('calcom_Nfish', 'comm85_Nfish' , 'CCFRPFarallons_Nfish', 'CCFRPNotFarallons_Nfish'))
growthCAAL <- rbind(growthCAAL, colSums(growthCAAL))
growthCAAL[nrow(growthCAAL), 1] <- "Total"
colnames(growthCAAL) <- c("Year", "Abrams", "CRFS Surrendered" , "CDFW commercial", "SWFSC Coop", "IPHC" ,"CDFW Gfish", "SWFSC Research", "WCGBTS", "Misc.", "CCFRP")

growthCAAL <- growthCAAL |> dplyr::relocate("CCFRP", .after = "Abrams")
growthCAAL <- replace(growthCAAL, growthCAAL==0, "---")



growthCAAL |>
kableExtra::kable(
  format = "latex", 
  longtable = TRUE,
  booktabs = TRUE,
  linesep = "",
  align = 'r',
  padding = 0) |>
  kableExtra::kable_styling(
    latex_options = "repeat_header",
    font_size = 11,
    full_width = FALSE) |># |>
  row_spec(15, bold=T)
  #kableExtra::column_spec(
  #  column = 1:3,
  #  width = "1in")

```

:::

{{< pagebreak >}}

## Assessment Model

```{r}
#| label: tbl-model-config
#| warning: false
#| echo: false
#| tbl-cap: !expr if(eval_tables) config_cap

config_table |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```



```{r}
#| label: tbl-n-param
#| warning: false
#| echo: false
#| tbl-cap: !expr if(eval_tables) parcount_cap

parcount_table |>
  dplyr::filter(Count > 0) |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

::: {.landscape}

```{r}
#| label: tbl-compweight
#| warning: false
#| echo: false
#| tbl-cap: !expr if(eval_tables) compweight_cap

compweight_table |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```


```{r}
#| label: tbl-pars
#| warning: false
#| echo: false
#| tbl-cap: !expr if(eval_tables) pars_cap
#| 
pars_table1 <- pars_table |>
  mutate(SD = ifelse(Status == 'fixed', NA, SD)) |> tibble::remove_rownames()

  kableExtra::kable(
  pars_table1,
  row.names = FALSE,
  format = "latex", 
  longtable = TRUE,
  booktabs = TRUE,
  caption = pars_cap) |>
  kableExtra::kable_styling(
    latex_options = c("repeat_header", "hold_position"),
    font_size = 8) |>
  kableExtra::column_spec(
   column = 1,
   width = "3in"
  ) |>
  kableExtra::column_spec(
   column = 2:6,
   width = "0.6in"
  ) |>
  kableExtra::column_spec(
   column = 7,
   width = "1.2in"
  )
  #gt() |>
  #sub_missing(missing_text = '') |>
  #tab_options(
  #  table.font.size = 12,
  #  latex.use_longtable = TRUE
  #) |>
  #as_latex()

```
:::

```{r}
#| label: tbl-likelihood
#| warning: false
#| echo: false
#| tbl-cap: "Likelihood components by source."

like <- mod_out$likelihoods_used 
like |>
  dplyr::mutate("source" = rownames(like)) |>
  dplyr::select(source, values) |>
  gt::gt() |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::fmt_number(
    columns = c(2),
    decimals = 2
  ) |>
  as_latex()
```

```{r, results = "asis"}
#| label: tbl-timeseries
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) time_series_cap 
#| tbl-pos: H

time_series_table |>
kableExtra::kable(
  format = "latex", 
  longtable = TRUE,
  booktabs = TRUE,
  caption = "Time series of population estimates from the base model.",
  linesep = "") |>
  kableExtra::kable_styling(
    latex_options = "repeat_header",
    font_size = 8) |>
  kableExtra::column_spec(
    column = 1:9,
    width = "0.5in"
  )
```


::: {.landscape}
```{r}
#| label: tbl-sens-productivity
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: "Productivity sensitivities. Values of negative log-likelihood, estimates of key parameters, and estimates of derived quantities between the base model and several alternative models (columns) relative to productivity. See main text for details on each sensitivity analysis."

#table_sens(here::here("report/tables/sens_productivity_table.csv"))
sens <- read.csv(here::here("report/tables/sens_productivity_table.csv"), check.names = FALSE) |>
  dplyr::slice(-1) |> #remove Npar %>%
  mutate_at(2:9, round, 3)

sens |>
kableExtra::kable(
  format = "latex", 
  longtable = TRUE,
  booktabs = TRUE,
  linesep = "") |>
  column_spec(2:9, width = "0.7in") |>
  kableExtra::kable_styling(font_size = 8,
    latex_options=c("scale_down", "hold_position"))

#sens |>
#  gt() |>
#  tab_options(table.font.size = 12)
#   |>
#  as_latex()
``` 

\pagebreak

```{r}
#| label: tbl-sens-contributions
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: "Data weighting and contribution sensitivities. Values of negative log-likelihood, estimates of key parameters, and estimates of derived quantities between the base model and several alternative models (columns) relative to data weighting. See main text for details on each sensitivity analysis. Because of differences in the relative contributions of data for these sensitivities, likelihoods are generally not comparable."
#| tbl-pos: H
#table_sens(here::here("report/tables/sens_weighting_table.csv"))
sens <- read.csv(here::here("report/tables/sens_data_contribution_table.csv"), check.names = FALSE) |>
  dplyr::slice(-1) %>% #remove Npar
  mutate_at(vars(-1), round, 3)
sens |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
``` 

\pagebreak

```{r}
#| label: tbl-sens-star
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: "Contributions from age data sensitivities. Values of negative log-likelihood, estimates of key parameters, and estimates of derived quantities between the base model and several alternative models (columns) related to age data. See main text for details on each sensitivity analysis. Because of differences in the relative contributions of data for these sensitivities, likelihoods are generally not comparable."
#| tbl-pos: H
sens <- read.csv(here::here("report/tables/sens_star_table.csv"), check.names = FALSE) |>
  dplyr::slice(-1) %>% #remove Npar
  mutate_at(vars(-1), round, 3)
sens |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
``` 

\pagebreak

```{r}
#| label: tbl-sens-data
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: "Data choice sensitivities. Values of negative log-likelihood, estimates of key parameters, and estimates of derived quantities between the base model and several alternative models (columns) relative to alternative data choices. See main text for details on each sensitivity analysis. Because of differences in data for these sensitivities, likelihoods are generally not comparable."

#table_sens(here::here("report/tables/sens_data_table.csv"))
sens <- read.csv(here::here("report/tables/sens_data_table.csv"), check.names = FALSE) |>
  dplyr::slice(-1) %>% #remove Npar
    mutate_at(vars(-1), round, 3)
sens |>
kableExtra::kable(
  format = "latex", 
  longtable = TRUE,
  booktabs = TRUE,
  linesep = "") |>
  kableExtra::kable_styling(font_size = 8,
    latex_options=c("scale_down", "hold_position"))
``` 

```{r}
#| label: tbl-sens-selectivity
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: "Selectivity sensitivities. Number of parameters, values of negative log-likelihood, estimates of key parameters, and estimates of derived quantities between the base model and several alternative models (columns) relative to selectivity. See main text for details on each sensitivity analysis."
#| tbl-pos: H
#table_sens(here::here("report/tables/sens_selectivity_table.csv"))
sens <- read.csv(here::here("report/tables/sens_selectivity_table.csv"), check.names = FALSE) %>%
  mutate_at(vars(-1), round, 3)

kableExtra::kable(
  sens,
  format = "latex", 
  booktabs = TRUE,
  linesep = "") |>
  kableExtra::kable_styling(font_size = 8, latex_options = "HOLD_position") |>
  kableExtra::column_spec(1, width = "3.5cm") |>
  kableExtra::column_spec(2:10, width = "1.5cm") 
``` 

:::

{{< pagebreak >}}

<!-- ## Management -->

<!-- \pagebreak -->

<!-- ```{r, results = "asis"} -->
<!-- #| label: tbl-projections -->
<!-- #| warning: false -->
<!-- #| echo: false -->
<!-- #| eval: !expr eval_tables  -->
<!-- #| tbl-cap: !expr if(eval_tables) projections_cap  -->
<!-- #| tbl-pos: H -->

<!-- projections_table |> -->
<!--   gt::gt() |> -->
<!--   gt::fmt_number( -->
<!--     columns = c(2:5, 7:9), -->
<!--     decimals = 0 -->
<!--   ) |> -->
<!--   gt::fmt_number( -->
<!--     columns = c(6, 10), -->
<!--     decimals = 3, -->
<!--     drop_trailing_zeros = FALSE, -->
<!--   ) |> -->
<!--   gt::fmt_number( -->
<!--     columns = c(4, 5, 7, 8), -->
<!--     decimals = 2, -->
<!--     drop_trailing_zeros = FALSE, -->
<!--   ) |> -->
<!--   gt::tab_options( -->
<!--     table.font.size = 12, -->
<!--     latex.use_longtable = TRUE  -->
<!--   ) |> -->
<!--   gt::sub_missing( -->
<!--     columns = tidyselect::everything(), -->
<!--     missing_text = "---" -->
<!--   ) |> -->
<!--   gt::cols_align( -->
<!--     align = "center" -->
<!--   ) |> -->
<!--   gt::cols_width( -->
<!--     tidyselect::everything() ~ px(75) -->
<!--   ) |> -->
<!--   gt::as_latex() -->

<!-- ``` -->



<!-- ```{r, results = "asis"} -->
<!-- #| label: tbl-risk -->
<!-- #| echo: false -->
<!-- #| warning: false -->
<!-- #| tbl-cap: "Risk Table for California quillback rockfish to document ecosystem and environmental factors, as well as data driven factors potentially affecting stock productivity and uncertainty or other concerns arising from the stock assessment. Level 1 is a favorable ranking, Level 2 neutral, and Level 3 unfavorable." -->

<!-- risk <-read.csv("Tables/RiskTable_quill.csv")  -->
<!-- risk|> -->
<!--   gt::gt() |> -->
<!--   gt::tab_options( -->
<!--     table.font.size = 12, -->
<!--     latex.use_longtable = TRUE -->
<!--   ) |> -->
<!--   gt::cols_label( -->
<!--     Ecosystem.and.environmental.conditions = "Ecosystem and environmental conditions", -->
<!--     Assessment.data.inputs = "Assessment data inputs", -->
<!--     Assessment.model.fits.and.structural.uncertainty = "Assessment model fits and structural uncertainty" -->
<!--   ) |> -->
<!--   gt::cols_width( -->
<!--     Ecosystem.and.environmental.conditions ~ px(150), -->
<!--     Assessment.data.inputs ~ px(300), -->
<!--     Assessment.model.fits.and.structural.uncertainty ~ px(150) -->
<!--   ) |> -->
<!--   gt::as_latex() -->
<!-- ``` -->

<!-- {{< pagebreak >}} -->