# Appendix B: Population scale within MPAs {#sec-appendix-B}

In addition to the relative index of abundance across sampling sites from the \gls{rov} survey, an estimate of absolute abundance aggregated across super years for only sites within no-take \gls{mpa}s was calculated and provided by the \gls{swfsc} (T. Rogers, pers. comm., 3/31/2025). The estimate was constrained to only areas within \gls{mpa}s to align with the design of the \gls{rov} survey in monitoring California \gls{mpa}s. The estimate was intended to serve as a reference point with which to compare with the scale estimated by the base model. Given \gls{mpa}s occur across a subset of the total `r spp` habitat in California, the base model estimate is expected to be higher than that from samples in \gls{mpa}s. Details of the \gls{rov} survey, and the relative abundance index across all sampling sites that was used in the base model have already been provided (see @sec-appendix-A). A detailed document describing the analysis for the absolute abundance estimate for sampling sites in no-take \gls{mpa} is available upon request from \gls{swfsc} and on the PFMC stock assessment meeting material website.  

The total abundance estimate for `r spp` in no-take \gls{mpa}s is 151,934 individuals with a 95% confidence interval of 118,204 -- 195,289 for 2015, and 317,274 individuals with a 95% confidence interval of 273,983 -- 367,405 for 2020. While not estimated to numbers at size, based on the lengths observed from sampling within \gls{mpa} sites (as small as 8 cm, which is approximately age 1), the abundance estimate could be expected to cover most ages. While the depth range of survey sampling sites covers 20--100 m, and therefore omits the shallowest areas between 0--20 m, the available depths are expected to capture much of the expected `r spp` habitat.

Abundance estimates from the base model were larger than those from the \gls{mpa} only estimate. For 2015, the estimate from the base model was 354,574 individuals across ages 1+, and 321,841 individuals across ages 3+. For 2020, the estimate from the base model was 533,052 individuals across ages 1+, and 423,641 individuals across ages 3+. Based on assuming numbers for age 3+ individuals, the base model estimates represent a factor of 2.12 and 1.34 times greater than the \gls{mpa} only estimates for 2015 and 2020, respectively. 

<!-- DO not plan to include this section which talks more about the 5x assumption.** -->
<!-- If the distribution of abundance of `r spp` is uniform across space, the proportion of potential `r spp` habitat in \gls{mpa}s can be used to scale the \gls{mpa} only estimate to the scale of the entire population. This assumption is unrealistic and would likely overestimate the assumed total population size, given that protected areas often consist of high quality habitat, and that population density within protected areas is thought to be greater than the density in areas open to extraction. Nonetheless, the exact value is unknown, and this assumption is a start. \Gls{mpa}s along the California coast cover approximately 20 percent of the available `r spp` habitat. The assessment model could match the expected total population size for 2015 if catches were approximately 2.3 times the amount of those used in the base model. The assessment model could also match this expected total population size for 2015 if natural mortality were changed to values at or above $M$ = 0.095. Changes to $h$ could not obtain this level of population size for 2015 even when set to the highest value ($h$ = 0.95) among the profiles explored. -->