---
title: 'Status of the Quillback rockfish stock in U.S. waters off the coast of California in 2025'
author:
  - name: 'Brian J. Langseth'
    affiliations:
      - name: 'NOAA Fisheries Northwest Fisheries Science Center'
        address: '2725 Montlake Boulevard East'
        city: 'Seattle, WA'
        state: 'WA'
        postal-code: '98112'
  - name: 'Melissa H. Monk'
    affiliations:
      - name: 'NOAA Fisheries Southwest Fisheries Science Center'
        address: '110 McAllister Way'
        city: 'Santa Cruz, CA'
        state: 'CA'
        postal-code: '95060'
  - name: 'Julia H. Coates'
    affiliations:
      - name: 'California Department of Fish and Wildlife Marine Region'
        address: '1933 Cliff Drive, Suite 9'
        city: 'Santa Barbara, CA'
        state: 'CA'
        postal-code: '93109'
date: today
lang: en 
keep-tex: true 
cover: figures/cover_photo_recfin.jpg
pdf-engine: lualatex
format: 
  pdf: 
    documentclass: scrartcl
    number-sections: true
    template-partials:
      - 'support_files/before-body.tex'
      - 'support_files/_titlepage.tex'
    include-in-header:
      - 'support_files/in-header.tex'
      - 'support_files/pfmc.tex'
    toc: true
    lof: false
    lot: false
    mainfont: 'Cambria'
    sansfont: 'Cambria'
    titlepage-geometry: 
      - top=2in
      - bottom=1in
      - right=1in
      - left=1in
    link-citations: true
    fig-pos: 'H'
output-file: 'Quillback_rockfish_SAR_2025' 
params:
   office: 'SWFSC'
   species: 'Quillback rockfish'
   spp_latin: 'Sebastes maliger'
   region: 'California'
   cf: 'Commercial fleet'
   rf: 'Recreational fleet'
bibliography: 
-  asar_references.bib
csl: 'canadian-journal-of-fisheries-and-aquatic-sciences.csl'
---


```{r}
#| label: 'read_base_model'
#| eval: true
#| echo: false
#| message: false
#| warning: false

library(here)
library(dplyr)

#source(here('Rscripts/table_sens.R'))

base_model <- '5_1_3_preStarBase'
mod_in <- r4ss::SS_read(here('models', base_model))
mod_out <- r4ss::SS_output(here('models', base_model), verbose = FALSE, printstats = FALSE)

setwd(here('report'))
```


```{r} 
#| label: 'output_and_quantities'
#| echo: false 
#| warning: false 
#| eval: true 
# load converted output from asar::convert_output() 
output <- utils::read.csv("ca_qlbk_std_output.csv")
# Call reference points and quantities below 
output <- output |> 
  dplyr::mutate(estimate = as.numeric(estimate), 
    uncertainty = as.numeric(uncertainty)) 
start_year <- as.numeric(min(output$year, na.rm = TRUE)) 
end_year <- (output |> 
  dplyr::filter(!(year %in% c('Virg', 'Init', 'S/Rcurve', 'INIT')), 
    !is.na(year)) |> 
  dplyr::mutate(year = as.numeric(year)) |> 
  dplyr::summarize(max_val = max(year)) |> 
  dplyr::pull(max_val))-10
# subset output to remove quantities that are split by factor 
output2 <- output |> 
  dplyr::filter(is.na(season), 
    is.na(fleet), 
    is.na(sex), 
    is.na(area), 
    is.na(growth_pattern), 
    is.na(subseason), 
    is.na(age))
# terminal fishing mortality 
Fend <- output2 |> 
  dplyr::filter(c(label == 'fishing_mortality' & year == end_year) | c(label == 'terminal_fishing_mortality' & is.na(year))) |>
  dplyr::pull(estimate)
# fishing mortality at msy 
# please change target if desired 
Ftarg <- output2 |>
  dplyr::filter(grepl('f_target', label) | grepl('f_msy', label) | c(grepl('fishing_mortality_msy', label) & is.na(year))) |>
  dplyr::pull(estimate)
# Terminal year F respective to F target 
F_Ftarg <- Fend / Ftarg
# terminal year biomass 
Bend <- output2 |>
  dplyr::filter(grepl('mature_biomass', label) | grepl('^biomass$', label),
    year == end_year) |>
  dplyr::pull(estimate)
# target biomass (msy) 
# please change target if desired 
Btarg <- output2 |>
  dplyr::filter(c(grepl('biomass', label) & grepl('target', label) & estimate >1) | label == 'biomass_msy') |>
  dplyr::pull(estimate)
# total catch in the last year 
total_catch <- output |>
  dplyr::filter(grepl('^catch$', label), 
  year == end_year,
    is.na(fleet),
    is.na(age),
    is.na(area),
    is.na(growth_pattern)) |>
  dplyr::pull(estimate)
# total landings in the last year 
total_landings <- output |>
  dplyr::filter(grepl('landings_weight', label), year == end_year,
    is.na(fleet),
    is.na(age)) |>
  dplyr::pull(estimate)
# spawning biomass in the last year
sbend <- output2 |>
  dplyr::filter(grepl('spawning_biomass', label), year == end_year) |>
  dplyr::pull(estimate) |>
    unique()
# overall natural mortality or at age 
M <- output |>
  dplyr::filter(grepl('natural_mortality', label)) |>
  dplyr::pull(estimate)
# Biomass at msy 
# to change to another reference point, replace msy in the following lines with other label 
Bmsy <- output2 |>
  dplyr::filter(c(grepl('biomass', label) & grepl('msy', label) & estimate >1) | label == 'biomass_msy') |>
  dplyr::pull(estimate)
# target spawning biomass(msy) 
# please change target if desired 
SBtarg <- output2 |>
  dplyr::filter(c(grepl('spawning_biomass', label) & grepl('msy$', label) & estimate >1) | label == 'spawning_biomass_msy$') |>
  dplyr::pull(estimate)
# steepness 
h <- output |> 
  dplyr::filter(grepl('steep', label)) |> 
  dplyr::pull(estimate)
# recruitment 
R0 <- output |> 
  dplyr::filter(grepl('R0', label) | grepl('recruitment_virgin', label)) |> 
  dplyr::pull(estimate)
# female SB (placeholder)

# Add our own calls
spp <- "quillback rockfish"
Spp <- "Quillback rockfish"
state <- "California"
``` 

{{< pagebreak >}} 

Please cite this publication as: 

Langseth, B.J., M.H. Monk, J.H. Coates, 2025. Status of the Quillback rockfish stock in U.S. waters off the coast of California in 2025. Pacific Fishery Management Council, Portland, OR. Available from https://www.pcouncil.org/stock-assessments-and-fishery-evaluation-safe-documents/.

 {{< pagebreak >}} 
 
```{r, results='asis'}
#| label: 'disclaimer'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('01a_disclaimer.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 



```{r, results='asis'}
#| label: 'load_tables'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('002_load_tables.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

  {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'executive_summary'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('01_executive_summary.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}}

```{r, results='asis'}
#| label: 'introduction'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('02_introduction.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'data'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('03_data.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'data-fish-depend'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('03a_data_fishery_dependent.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'data-surveys'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('03c_data_surveys.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'data-bio'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('03d_data_bio.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'data-notused'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('03e_data_notused.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}}

```{r, results='asis'}
#| label: 'model-history'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04a_model_history.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'model-structure'
#| eval: true
#| echo: false
#| warning: false
#a <- knitr::knit_child('04b_model_structure.qmd', quiet = TRUE)
#cat(a, sep = '\n')
```

 {{< pagebreak >}} 
 
```{r, results='asis'}
#| label: 'model-bridging'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04c_model_bridging.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 
 
```{r, results='asis'}
#| label: 'model-results'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04d_model_results.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 
 
```{r, results='asis'}
#| label: 'model-diagnostics'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04e_model_diagnostics.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'model-sensitivity'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04f_model_sensitivity.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}}
 
```{r, results='asis'}
#| label: 'uncertainties'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04g_uncertainties.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}}

```{r, results='asis'}
#| label: 'management'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('05_management.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'research-needs'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('05b_research_needs.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'acknowledgments'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('06_acknowledgments.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'references'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('07_references.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'tables'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('08_tables.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'figures-data'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('09_figures_data.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

{{< pagebreak >}} 

```{r, results='asis'}
#| label: 'figures-model'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('09_figures_model.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'appendix-a'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('11a_appendix_A.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'appendix-b'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('11b_appendix_B.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'appendix-c'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('11c_appendix_C.qmd', quiet = TRUE)
cat(a, sep = '\n')
```