## Biological Parameters

 FROG NAMED MELISSA

### Natural Mortality


Natural mortality was not directly measured, so life-history based empirical relationships were used. The @hamel_development_2022 method for developing a prior on natural mortality for West Coast groundfish stock assessments combines meta-analytic approaches relating the $M$ rate to other life-history parameters such as longevity, size, growth rate, and reproductive effort to provide a prior for $M$. The @hamel_development_2022 method re-evaluated the data used by Then et al. [-@then_evaluating_2015] by fitting the one-parameter $A_{\text{max}}$ model under a log-log transformation (such that the slope is forced to be -1 in the transformed space [@hamel_method_2015], the point estimate and median of the prior for $M$ is:

\begin{centering}

$M=\frac{5.4}{A_{\text{max}}}$

\end{centering}

\vspace{0.5cm}

where $A_{\text{max}}$ is the maximum age. The prior is defined as a log-normal distribution with parameters $\mu = ln(5.4/A_{\text{max}})$ and $\sigma = 0.438$. Using a maximum age of 95 years, the point estimate and median of the prior for $M$ is `r model$parameters["NatM_p_1_Fem_GP_1","Value"]` per year.

The maximum age assumed for calculating natural mortality in the base model was 80 years. FROG


### Weight-at-length


### Maturity

From 2019 to 2025 a total of 88 histological samples were collected from female quillback rockfish caught off the coast of California (16 by CCFRP and 72 by the SWFSC). The samples were read by Melissa Head at the NWFSC to for identification of microscopic functional maturity stage. Functional maturity accounts abortive manturation and the proportion of oocytes in atresia (cellular breakdown and reabsorption), which could indicate skipped spawning (Melissa Head, personal communication, NWFSC, NOAA). Seven samples were excluded due to uncertainy in whether the female was spent/resting or experienced abortive maturation, due in part to the timeinin of the collections during the non-spawning months.  

The remaining 81 samples ranged in size from 21-45 cm.  The six females collected from north of Pt. Arena (Crescent City and Eureka) were all mature.  The SWFSC collected 22 females in January 2025 that contributed to our estimate of maturity-at-length, but are not included in the growth fleet.  The 2021 quillback rockfish estimates used the estimates from Oregon of L50 = 29.3 cm. 
Our estimate of maturity for California quillback is L50 = 28.5 (SE = 0.506).  






We used a total of 232 individual histological samples of aged female yellowtail rockfish to estimate maturity for the assessment. These samples were all collected north of $40.167^\circ$ N. The 232 samples were collected over the period 2016—2023, though more samples were collected earlier in these years (n = 111 in 2016, 52 in 2017, 31 in 2018, 17 in 2021, 9 in 2022, 13 in 2023). Previous assessments of yellowtail estimated length-based maturity (L50 = 42.49cm in 2017 assessment); however, we switched to an age-based model for the current assessment. For many species, energy is reallocated toward maturation from growth, and as a result growth rates slow during the juvenile to adult transition period. Thus, length at 50% maturity will represent a range of ages, providing a less accurate understanding of the spawning population. We treated maturity as a binomial response, and considered a variety of models with temporal and spatial covariates, using a logit link and generalized linear mixed model framework, implemented using the R package \gls{sdmtmb} [@Anderson_2024_SRP]. Briefly, we considered models that included (1) temporal year effects (either estimated as a random walk intercept, or smooth term), (2) spatial random fields (using a mesh cutoff distance of 50km), and (3) spatially varying coefficients of age, following the model adopted by @grandin_status_2024. Models that converged were compared by examining QQ plots, AUC metrics, and AIC scores. Likely because of the uneven temporal distribution of sampling, and general sparsity, we did not find support for including temporal or spatial effects, and decided on the simpler null model (equivalent to a logistic regression). For the age-based model, we estimated an intercept of -6.70 (SE = 0.99) and slope of 0.67 (SE = 0.10), equivalent to an A50 of 10.0 years (@fig-maturity). For a more direct comparison to the previous assessment, we used these same 232 samples to fit an equivalent length-based model, which resulted in an estimated L50 = 42.5 cm, essentially identical to the value used in 2017.



### Fecundity

The fecundity-at-length was based on ovary samples collected by the SWFSC Santa Cruz lab in 2023 and 2024. The fecundity relationship for `r spp` was estimated to be equal to `r format(model$MGparmAdj$Eggs_scalar_Fem[1], scientific = TRUE)`$L$^`r round(model$MGparmAdj$Eggs_exp_len_Fem[1],2)`^ in millions of eggs where $L$ is fork length in cm. Fecundity-at-length is shown in Figure \ref{fig:fecundity}.

### Growth (Length-at-Age)

Melissa FROG

Uncertainty surrounding the age-reading process for `r spp` was incorporated by estimating ageing error by age. Age composition data used in the model were from break-and-burn otolith reads. Aged `r spp` used in the assessment were aged by the Cooperative Ageing Project (CAP) in Newport, Oregon. Within-lab ageing error was estimated by the CAP based on one primary age reader and a second reader producing double reads from 418 otoliths collected from California (Figure \ref{fig:age-error-dist}). 

An ageing error estimate was made based on these double reads using an ADMB computational tool specifically developed for estimating ageing error [@punt_quantifying_2008] and using release 1.3.1 of the R package \href{https://github.com/pfmc-assessments/nwfscAgeingError}{nwfscAgeingError} [@thorson_nwfscageingerror_2012] for input and output diagnostics. A series of 24 ageing error models were run to look across the suite of bias and ageing precision. The model selected by AIC (and used in the assessment) assumes the first reader was unbiased and a constanct coefficient of variation, i.e., sigma is a linear fuction of true age (Figures \ref{fig:age-error} and \ref{fig:age-error-matrix}). 


## Environmental and ecosystem data

This model does not explicityl include envrionmental or ecosystem data.  `r Spp` are a rocky habitat associated species and the area of available habitat was consdiered when developing indices of abundance for the fishery-independent survyes. 

<!-- Environmental or ecosystem data or model products used in the stock assessment model and/or in the preparation of data or estimation of biological parameters. If environmental or ecosystem data are incorporated in the stock assessment model, provide a report of consultations with technical teams that evaluate ecosystem data or methodologies used in  -->




