## Data Sources Considered But Not Used

### Marine Recreational Fisheries Statistics Survey (MRFSS)
The MRFSS program was a federally administered recreational marine fisheries survey conducted between 1980 and 2003.   We explored the potential to produce a fishery-dependent index of abundance using private/rental angler interview data.  The index was ultimately not included in the model due to a very low proportion of samples with quillback  and very large standard deviations around average cpue.  See Appendix A for further detail.  

### CPFV Logbook
CPFV paper logbooks, collected by CDFW in their current form, began to be used in 1980.  This dataset contains individual trip records with information reported by the vessel captain including numbers of fish by species or species group, the port of landing, the 10x10 nautical mile fishing block and depth where the majority of fishing occurred, the number of contributing anglers, and the number of hours spent actively fishing, among other fields.  Captains are required to submit a log for each trip and compliance rates have varied over time.  In 2017, captains were provided with the option to use an electronic log, though the paper log is still acceptable.  Paper logs are limited in species specific fields.  Rockfish are either enumerated in a rockfish genus field that is not species-specific or individual species can be noted using a write-in field.  Most rockfish are not speciated on the paper log.  The electronic log allows for a greater number of species selections using pull-down menus.  A general genus category for rockfish also exists in the electronic log and identification to species is not legally required.  We explored this data for its potential to produce and index of abundance or to inform our understanding of CPFV effort and fishing dynamics over time in the context of quillback rockfish.

We filtered the data to focus on trips more relevant to quillback (**FROG: ADD REFERENCE TO TABLE CPFVLogFilters.csv**).  We excluded trips south of Point Conception where quillback are rare by excluding fishing blocks numbered greater than 650.  We excluded trips occurring between January and March when fishing for rockfish is prohibited.  We included only trips noting their target was rockfish and only single day trips.  Multi-day trips typically target highly migratory species.  Quillback remained rare following these filters with approximately 0.3 % of trips catching one or more quillback.  This was deemed insufficient for production of an index.  

### International Pacific Halibut Commission, Fishery-independent Setline Survey (IPHC-FISS)
The IPHC-FISS survey is designed to provide catch and biological information on Pacific halibut but does retain records on non-target species.  However, the survey is focussed in Alaska and Brittish Columbia and does not frequently extend into California waters.  CDFW is aware of 22 quillback caught in 2014 and five in 2017.  Age data are available for the five fish from 2017.  These data were considered insufficient for inclusion in length or age compositions.  