### CPFV Onboard Observer Index of Abundance {#onboard-cpfv-index}

There are two data sets containing fishing stop specific information on for the CPFV fleet.  The survey known as the Deb Wilson-Vandenberg survey was conducted by CDFW in California north of Point Conception from 1987-1998 and referred to as the Deb Wilson-Vandenberg onboard, @reilly_onboard_1998. In 1999, CDFW began a statewide onboard observer survey of the CPFV fleet that became part of CRFS in 2004[@monk_documentation_2014]. 


During an onboard observer trip the sampler rides along on the CPFV and records location-specific catch and discard information to the species level for a subset of anglers onboard the vessel. The subset of observed anglers is usually a maximum of 15 people and the observed anglers change during each fishing stop.The catch cannot be linked to an individual, but rather to a specific fishing location. The sampler also records the starting and ending time, number of anglers observed, starting and ending depth, and measures discarded fish. The fine-scale catch and effort data allow us to better filter the data for indices to fishing stops within suitable habitat for `r spp`. 


A large effort was made by the SWFSC to recover the Deb Wilson-Vandenberg data from the original data 
sheets for this survey and develop a relational database @monk_documentation_2016. 
For this portion of the survey, specific fishing locations at each fishing stop were recorded at a finer 
scale than the catch data for this survey. We aggregated the relevant location 
information (time and number of observed anglers) to match the available catch 
information. Between April 1987 and July 1992 the number of observed anglers 
was not recorded for each fishing stop, but the number of anglers aboard the 
vessel is available.  We imputed the number of observed anglers using the number 
of anglers aboard the vessel and the number of observed anglers at each fishing 
stop from the August 1992-December 1998 data. In 1987, trips were only observed in Monterey, CA and were therefore excluded from the analysis (Table \@ref(tab:deb-filter)). Sampling mainly
targeted areas of central California.  Of the 2,256 trips observed, only 12 of 
those launched from port in District 6, the most northern district in California.



Each fishing location was assigned to a reef based on the on the bathymetric maps 
and interpretation of hard bottom was extracted from 
the [California Seafloor Mapping Project](http://seafloor.otterlabs.org/index.html).
Reefs were aggregated to four regions to produce adequate sample sizes; 
the California/Oregon border to San Francisco (V1), San Francisco to Moss Landing (V2), 
Moss Landing to Big Sur (V3), and San Luis Obispo county to Point Conception (V4).  The ports in San 
Luis Obispo county were sampled more frequently than other regions and the arithmetic 
mean of CPUE by year was also higher in this area (Figure \@ref(fig:deb-regioncpue))


The filters also included removal of the number of observed anglers and time fished at the tail 
ends of the distributions and removal of drifts occurring in depths outside copper rockfish's range 
(Table \@ref(tab:deb-filter) and Figure \@ref(fig:deb-depths)). 
We retained 5,546 drifts for index standardization, with 
1,389 fishing locations encountering copper rockfish.  
Tables of the number of samples and positive observations can be found in Table \@ref(tab:deb-percentpos).


We modeled catch per angler hour fished (CPUE) by fishing stop where the angler 
hours were summed across drifts at a fishing stop. To explore weighting of the onboard observer survey index by the available 
rocky substrate within a region, each drift was assigned to the closest area 
of rocky habitat. Hard bottom was extracted from 
the [California Seafloor Mapping Project](http://seafloor.otterlabs.org/index.html), 
along the mainland coast of southern California. These data 
were collected in state waters at a resolution of two meters, but did not extend into state waters 
past the mainland coast. Additional interpreted bathymetric data classifying the bottom type as 
rock or soft bottom were compiled by analysts at the University of California Santa Cruz and are now
also available from CDFW's website. We used the available interpreted rocky substrate data to expand the 
known area of rocky substrate to areas in southern California that lack substrate type. This 
expansion of the estimated rocky substrate assumes that the proportions of rocky substrate within 
and outside state waters are similar.


The covariates explored for model selection included year, four categorical region levels, and continuous depth and depth-squared.  
Trends in the average CPUE by region were similar 
in the filtered data set (Figure \@ref(fig:deb-regioncpue)). A year and region interaction 
was included after visualizing the trends in average CPUE over time, but was not significant 
(Figure \@ref(fig:deb-average_cpue_by_region)). The full model was selected by AICc and 
included year, depth, depth squared and region
(Table \@ref(tab:deb-model_selection)). 

Indices were fit via MLE from the sdmTMB package in R. The Q-Q plot for the negative binoimal 
model indicated a poor fit to the data, which as not surprising given the low percent of 
observed drifts encountering copper rockfish. A delta-gamma
was selected over a delta-lognormal by a delta AIC of 43.  The Q-Q plot indicated a much 
improved fit compared to the negative binomial model (Table \@ref(fig:onboard-qq)).
The relative abundance indicates a decreasing trend during the time series (Table \@ref(tab:deb-index) 
and Figure \@ref(fig:deb-index)). 
